
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.batch;

import com.sap.cloud.sdk.datamodel.odata.helper.batch.FluentHelperServiceBatch;


/**
 * Interface to the batch object of an {@code com.sap.cloud.sdk.tutorial.datamodel.odata.services.APIPRODUCTIONORDER2SRVService APIPRODUCTIONORDER2SRVService} service.
 * 
 */
public interface APIPRODUCTIONORDER2SRVServiceBatch
    extends FluentHelperServiceBatch<APIPRODUCTIONORDER2SRVServiceBatch, APIPRODUCTIONORDER2SRVServiceBatchChangeSet>
{


}
