
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.link;

import javax.annotation.Nonnull;
import com.sap.cloud.sdk.datamodel.odata.helper.EntityLink;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmObject;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrderItems;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.selectable.ProductionOrderItemsSelectable;


/**
 * Template class to represent entity navigation links of {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrderItems ProductionOrderItems} to other entities. Instances of this object are used in query modifier methods of the entity
 * fluent helpers. Contains methods to compare a field's value with a provided value.
 * 
 * Use the constants declared in each entity inner class. Instantiating directly requires knowing the underlying OData
 * field names, so use the constructor with caution.
 * 
 * @param <ObjectT>
 * Entity type of subclasses from {@link com.sap.cloud.sdk.datamodel.odata.helper.VdmObject VdmObject}.
 * 
 */
public class ProductionOrderItemsLink<ObjectT extends VdmObject<?> >
    extends EntityLink<ProductionOrderItemsLink<ObjectT> , ProductionOrderItems, ObjectT>
    implements ProductionOrderItemsSelectable
{


    /**
     * Use the constants declared in each entity inner class. Instantiating directly requires knowing the underlying OData field names, so use with caution.
     * 
     * @param fieldName
     *     OData navigation field name. Must match the field returned by the underlying OData service.
     */
    public ProductionOrderItemsLink(final String fieldName) {
        super(fieldName);
    }

    private ProductionOrderItemsLink(final EntityLink<ProductionOrderItemsLink<ObjectT> , ProductionOrderItems, ObjectT> toClone) {
        super(toClone);
    }

    @Nonnull
    @Override
    protected ProductionOrderItemsLink<ObjectT> translateLinkType(final EntityLink<ProductionOrderItemsLink<ObjectT> , ProductionOrderItems, ObjectT> link) {
        return new ProductionOrderItemsLink<ObjectT>(link);
    }

}
