
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv;

import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmComplex;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * <p>Original complex type name from the Odata EDM: <b>FunctionMessage</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class FunctionMessage
    extends VdmComplex<FunctionMessage>
{

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property from the Odata EDM: <b>SystemMessageType</b></p>
     * 
     * @param messageType
     *     
     * @return
     *     Message Type
     */
    @SerializedName("SystemMessageType")
    @JsonProperty("SystemMessageType")
    @Nullable
    @ODataField(odataName = "SystemMessageType")
    private String messageType;
    /**
     * Constraints: Not nullable, Maximum length: 20 <p>Original property from the Odata EDM: <b>SystemMessageIdentification</b></p>
     * 
     * @param messageClass
     *     
     * @return
     *     Message Class
     */
    @SerializedName("SystemMessageIdentification")
    @JsonProperty("SystemMessageIdentification")
    @Nullable
    @ODataField(odataName = "SystemMessageIdentification")
    private String messageClass;
    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property from the Odata EDM: <b>SystemMessageNumber</b></p>
     * 
     * @param messageNumber
     *     
     * @return
     *     Message Number
     */
    @SerializedName("SystemMessageNumber")
    @JsonProperty("SystemMessageNumber")
    @Nullable
    @ODataField(odataName = "SystemMessageNumber")
    private String messageNumber;
    /**
     * Constraints: Not nullable, Maximum length: 220 <p>Original property from the Odata EDM: <b>SystemMessageLongText</b></p>
     * 
     * @param messageText
     *     
     * @return
     *     Message Text
     */
    @SerializedName("SystemMessageLongText")
    @JsonProperty("SystemMessageLongText")
    @Nullable
    @ODataField(odataName = "SystemMessageLongText")
    private String messageText;
    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property from the Odata EDM: <b>SystemMessageVariable1</b></p>
     * 
     * @param messageVariable
     *     
     * @return
     *     Message Variable
     */
    @SerializedName("SystemMessageVariable1")
    @JsonProperty("SystemMessageVariable1")
    @Nullable
    @ODataField(odataName = "SystemMessageVariable1")
    private String messageVariable;
    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property from the Odata EDM: <b>SystemMessageVariable2</b></p>
     * 
     * @param messageVariable_2
     *     
     * @return
     *     Message Variable
     */
    @SerializedName("SystemMessageVariable2")
    @JsonProperty("SystemMessageVariable2")
    @Nullable
    @ODataField(odataName = "SystemMessageVariable2")
    private String messageVariable_2;
    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property from the Odata EDM: <b>SystemMessageVariable3</b></p>
     * 
     * @param messageVariable_3
     *     
     * @return
     *     Message Variable
     */
    @SerializedName("SystemMessageVariable3")
    @JsonProperty("SystemMessageVariable3")
    @Nullable
    @ODataField(odataName = "SystemMessageVariable3")
    private String messageVariable_3;
    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property from the Odata EDM: <b>SystemMessageVariable4</b></p>
     * 
     * @param messageVariable_4
     *     
     * @return
     *     Message Variable
     */
    @SerializedName("SystemMessageVariable4")
    @JsonProperty("SystemMessageVariable4")
    @Nullable
    @ODataField(odataName = "SystemMessageVariable4")
    private String messageVariable_4;

    @Nonnull
    @Override
    public Class<FunctionMessage> getType() {
        return FunctionMessage.class;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("SystemMessageType", getMessageType());
        values.put("SystemMessageIdentification", getMessageClass());
        values.put("SystemMessageNumber", getMessageNumber());
        values.put("SystemMessageLongText", getMessageText());
        values.put("SystemMessageVariable1", getMessageVariable());
        values.put("SystemMessageVariable2", getMessageVariable_2());
        values.put("SystemMessageVariable3", getMessageVariable_3());
        values.put("SystemMessageVariable4", getMessageVariable_4());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("SystemMessageType")) {
                final Object value = values.remove("SystemMessageType");
                if ((value == null)||(!value.equals(getMessageType()))) {
                    setMessageType(((String) value));
                }
            }
            if (values.containsKey("SystemMessageIdentification")) {
                final Object value = values.remove("SystemMessageIdentification");
                if ((value == null)||(!value.equals(getMessageClass()))) {
                    setMessageClass(((String) value));
                }
            }
            if (values.containsKey("SystemMessageNumber")) {
                final Object value = values.remove("SystemMessageNumber");
                if ((value == null)||(!value.equals(getMessageNumber()))) {
                    setMessageNumber(((String) value));
                }
            }
            if (values.containsKey("SystemMessageLongText")) {
                final Object value = values.remove("SystemMessageLongText");
                if ((value == null)||(!value.equals(getMessageText()))) {
                    setMessageText(((String) value));
                }
            }
            if (values.containsKey("SystemMessageVariable1")) {
                final Object value = values.remove("SystemMessageVariable1");
                if ((value == null)||(!value.equals(getMessageVariable()))) {
                    setMessageVariable(((String) value));
                }
            }
            if (values.containsKey("SystemMessageVariable2")) {
                final Object value = values.remove("SystemMessageVariable2");
                if ((value == null)||(!value.equals(getMessageVariable_2()))) {
                    setMessageVariable_2(((String) value));
                }
            }
            if (values.containsKey("SystemMessageVariable3")) {
                final Object value = values.remove("SystemMessageVariable3");
                if ((value == null)||(!value.equals(getMessageVariable_3()))) {
                    setMessageVariable_3(((String) value));
                }
            }
            if (values.containsKey("SystemMessageVariable4")) {
                final Object value = values.remove("SystemMessageVariable4");
                if ((value == null)||(!value.equals(getMessageVariable_4()))) {
                    setMessageVariable_4(((String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        return result;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property from the Odata EDM: <b>SystemMessageType</b></p>
     * 
     * @param messageType
     *     Message Type
     */
    public void setMessageType(
        @Nullable
        final String messageType) {
        rememberChangedField("SystemMessageType", this.messageType);
        this.messageType = messageType;
    }

    /**
     * Constraints: Not nullable, Maximum length: 20 <p>Original property from the Odata EDM: <b>SystemMessageIdentification</b></p>
     * 
     * @param messageClass
     *     Message Class
     */
    public void setMessageClass(
        @Nullable
        final String messageClass) {
        rememberChangedField("SystemMessageIdentification", this.messageClass);
        this.messageClass = messageClass;
    }

    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property from the Odata EDM: <b>SystemMessageNumber</b></p>
     * 
     * @param messageNumber
     *     Message Number
     */
    public void setMessageNumber(
        @Nullable
        final String messageNumber) {
        rememberChangedField("SystemMessageNumber", this.messageNumber);
        this.messageNumber = messageNumber;
    }

    /**
     * Constraints: Not nullable, Maximum length: 220 <p>Original property from the Odata EDM: <b>SystemMessageLongText</b></p>
     * 
     * @param messageText
     *     Message Text
     */
    public void setMessageText(
        @Nullable
        final String messageText) {
        rememberChangedField("SystemMessageLongText", this.messageText);
        this.messageText = messageText;
    }

    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property from the Odata EDM: <b>SystemMessageVariable1</b></p>
     * 
     * @param messageVariable
     *     Message Variable
     */
    public void setMessageVariable(
        @Nullable
        final String messageVariable) {
        rememberChangedField("SystemMessageVariable1", this.messageVariable);
        this.messageVariable = messageVariable;
    }

    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property from the Odata EDM: <b>SystemMessageVariable2</b></p>
     * 
     * @param messageVariable_2
     *     Message Variable
     */
    public void setMessageVariable_2(
        @Nullable
        final String messageVariable_2) {
        rememberChangedField("SystemMessageVariable2", this.messageVariable_2);
        this.messageVariable_2 = messageVariable_2;
    }

    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property from the Odata EDM: <b>SystemMessageVariable3</b></p>
     * 
     * @param messageVariable_3
     *     Message Variable
     */
    public void setMessageVariable_3(
        @Nullable
        final String messageVariable_3) {
        rememberChangedField("SystemMessageVariable3", this.messageVariable_3);
        this.messageVariable_3 = messageVariable_3;
    }

    /**
     * Constraints: Not nullable, Maximum length: 50 <p>Original property from the Odata EDM: <b>SystemMessageVariable4</b></p>
     * 
     * @param messageVariable_4
     *     Message Variable
     */
    public void setMessageVariable_4(
        @Nullable
        final String messageVariable_4) {
        rememberChangedField("SystemMessageVariable4", this.messageVariable_4);
        this.messageVariable_4 = messageVariable_4;
    }

}
