
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv;

import java.util.Map;
import javax.annotation.Nonnull;
import com.google.common.collect.Maps;
import com.sap.cloud.sdk.datamodel.odata.helper.FluentHelperByKey;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.selectable.ProductionOrderOperationsSelectable;


/**
 * Fluent helper to fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations ProductionOrderOperations} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. 
 * 
 */
public class ProductionOrderOperationsByKeyFluentHelper
    extends FluentHelperByKey<ProductionOrderOperationsByKeyFluentHelper, ProductionOrderOperations, ProductionOrderOperationsSelectable>
{

    private final Map<String, Object> key = Maps.newHashMap();

    /**
     * Creates a fluent helper object that will fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations ProductionOrderOperations} entity with the provided key field values. To perform execution, call the {@link #executeRequest executeRequest} method on the fluent helper object.
     * 
     * @param entityCollection
     *     Entity Collection to be used to fetch a single {@code ProductionOrderOperations}
     * @param servicePath
     *     Service path to be used to fetch a single {@code ProductionOrderOperations}
     * @param orderInternalID
     *     Order Internal ID<p>Constraints: Not nullable, Maximum length: 10</p>
     * @param operationInternalID
     *     Internal Identifier of an Operation or Activity<p>Constraints: Not nullable, Maximum length: 8</p>
     */
    public ProductionOrderOperationsByKeyFluentHelper(
        @Nonnull
        final String servicePath,
        @Nonnull
        final String entityCollection, final String orderInternalID, final String operationInternalID) {
        super(servicePath, entityCollection);
        this.key.put("OrderInternalBillOfOperations", orderInternalID);
        this.key.put("OrderIntBillOfOperationsItem", operationInternalID);
    }

    @Override
    @Nonnull
    protected Class<ProductionOrderOperations> getEntityClass() {
        return ProductionOrderOperations.class;
    }

    @Override
    @Nonnull
    protected Map<String, Object> getKey() {
        return key;
    }

}
