
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Lists;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.cloudplatform.connectivity.Destination;
import com.sap.cloud.sdk.datamodel.odata.client.exception.ODataException;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmEntity;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import com.sap.cloud.sdk.s4hana.datamodel.odata.annotation.Key;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.field.ProductionOrderItemsField;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.link.ProductionOrderItemsLink;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.selectable.ProductionOrderItemsSelectable;
import com.sap.cloud.sdk.typeconverter.TypeConverter;
import io.vavr.control.Option;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;


/**
 * Production Order Items<p></p><p>Original entity name from the Odata EDM: <b>A_ProductionOrderItem_2Type</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class ProductionOrderItems
    extends VdmEntity<ProductionOrderItems>
{

    /**
     * Selector for all available fields of ProductionOrderItems.
     * 
     */
    public final static ProductionOrderItemsSelectable ALL_FIELDS = () -> "*";
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>ManufacturingOrder</b></p>
     * 
     * @return
     *     Production Order
     */
    @Key
    @SerializedName("ManufacturingOrder")
    @JsonProperty("ManufacturingOrder")
    @Nullable
    @ODataField(odataName = "ManufacturingOrder")
    private String productionOrder;
    /**
     * Use with available fluent helpers to apply the <b>ManufacturingOrder</b> field to query operations.
     * 
     */
    public final static ProductionOrderItemsField<String> PRODUCTION_ORDER = new ProductionOrderItemsField<String>("ManufacturingOrder");
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>ManufacturingOrderItem</b></p>
     * 
     * @return
     *     Manufacturing Order Item ID
     */
    @Key
    @SerializedName("ManufacturingOrderItem")
    @JsonProperty("ManufacturingOrderItem")
    @Nullable
    @ODataField(odataName = "ManufacturingOrderItem")
    private String manufacturingOrderItem;
    /**
     * Use with available fluent helpers to apply the <b>ManufacturingOrderItem</b> field to query operations.
     * 
     */
    public final static ProductionOrderItemsField<String> MANUFACTURING_ORDER_ITEM = new ProductionOrderItemsField<String>("ManufacturingOrderItem");
    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>ManufacturingOrderCategory</b></p>
     * 
     * @return
     *     Manufacturing Order Category
     */
    @SerializedName("ManufacturingOrderCategory")
    @JsonProperty("ManufacturingOrderCategory")
    @Nullable
    @ODataField(odataName = "ManufacturingOrderCategory")
    private String orderCategory;
    /**
     * Use with available fluent helpers to apply the <b>ManufacturingOrderCategory</b> field to query operations.
     * 
     */
    public final static ProductionOrderItemsField<String> ORDER_CATEGORY = new ProductionOrderItemsField<String>("ManufacturingOrderCategory");
    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>ManufacturingOrderType</b></p>
     * 
     * @return
     *     Manufacturing Order Type
     */
    @SerializedName("ManufacturingOrderType")
    @JsonProperty("ManufacturingOrderType")
    @Nullable
    @ODataField(odataName = "ManufacturingOrderType")
    private String orderType;
    /**
     * Use with available fluent helpers to apply the <b>ManufacturingOrderType</b> field to query operations.
     * 
     */
    public final static ProductionOrderItemsField<String> ORDER_TYPE = new ProductionOrderItemsField<String>("ManufacturingOrderType");
    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>IsCompletelyDelivered</b></p>
     * 
     * @return
     *     "Delivery Completed" Indicator
     */
    @SerializedName("IsCompletelyDelivered")
    @JsonProperty("IsCompletelyDelivered")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "IsCompletelyDelivered")
    private Boolean deliveryCompleted;
    /**
     * Use with available fluent helpers to apply the <b>IsCompletelyDelivered</b> field to query operations.
     * 
     */
    public final static ProductionOrderItemsField<Boolean> DELIVERY_COMPLETED = new ProductionOrderItemsField<Boolean>("IsCompletelyDelivered");
    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>Material</b></p>
     * 
     * @return
     *     Material Number for Order
     */
    @SerializedName("Material")
    @JsonProperty("Material")
    @Nullable
    @ODataField(odataName = "Material")
    private String material;
    /**
     * Use with available fluent helpers to apply the <b>Material</b> field to query operations.
     * 
     */
    public final static ProductionOrderItemsField<String> MATERIAL = new ProductionOrderItemsField<String>("Material");
    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>ProductionPlant</b></p>
     * 
     * @return
     *     Production Plant
     */
    @SerializedName("ProductionPlant")
    @JsonProperty("ProductionPlant")
    @Nullable
    @ODataField(odataName = "ProductionPlant")
    private String productionPlant;
    /**
     * Use with available fluent helpers to apply the <b>ProductionPlant</b> field to query operations.
     * 
     */
    public final static ProductionOrderItemsField<String> PRODUCTION_PLANT = new ProductionOrderItemsField<String>("ProductionPlant");
    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>Plant</b></p>
     * 
     * @return
     *     Planning Plant for an Order
     */
    @SerializedName("Plant")
    @JsonProperty("Plant")
    @Nullable
    @ODataField(odataName = "Plant")
    private String planningPlant;
    /**
     * Use with available fluent helpers to apply the <b>Plant</b> field to query operations.
     * 
     */
    public final static ProductionOrderItemsField<String> PLANNING_PLANT = new ProductionOrderItemsField<String>("Plant");
    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>MRPArea</b></p>
     * 
     * @return
     *     MRP Area
     */
    @SerializedName("MRPArea")
    @JsonProperty("MRPArea")
    @Nullable
    @ODataField(odataName = "MRPArea")
    private String mRPArea;
    /**
     * Use with available fluent helpers to apply the <b>MRPArea</b> field to query operations.
     * 
     */
    public final static ProductionOrderItemsField<String> MRP_AREA = new ProductionOrderItemsField<String>("MRPArea");
    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>QuantityDistributionKey</b></p>
     * 
     * @return
     *     MRP Distribution Key
     */
    @SerializedName("QuantityDistributionKey")
    @JsonProperty("QuantityDistributionKey")
    @Nullable
    @ODataField(odataName = "QuantityDistributionKey")
    private String distributionKey;
    /**
     * Use with available fluent helpers to apply the <b>QuantityDistributionKey</b> field to query operations.
     * 
     */
    public final static ProductionOrderItemsField<String> DISTRIBUTION_KEY = new ProductionOrderItemsField<String>("QuantityDistributionKey");
    /**
     * Constraints: Not nullable, Precision: 3, Scale: 0 <p>Original property name from the Odata EDM: <b>MaterialGoodsReceiptDuration</b></p>
     * 
     * @return
     *     Goods Receipt Processing Duration in Days
     */
    @SerializedName("MaterialGoodsReceiptDuration")
    @JsonProperty("MaterialGoodsReceiptDuration")
    @Nullable
    @ODataField(odataName = "MaterialGoodsReceiptDuration")
    private BigDecimal gRProcessingTime;
    /**
     * Use with available fluent helpers to apply the <b>MaterialGoodsReceiptDuration</b> field to query operations.
     * 
     */
    public final static ProductionOrderItemsField<BigDecimal> GR_PROCESSING_TIME = new ProductionOrderItemsField<BigDecimal>("MaterialGoodsReceiptDuration");
    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>StorageLocation</b></p>
     * 
     * @return
     *     Storage Location
     */
    @SerializedName("StorageLocation")
    @JsonProperty("StorageLocation")
    @Nullable
    @ODataField(odataName = "StorageLocation")
    private String storageLocation;
    /**
     * Use with available fluent helpers to apply the <b>StorageLocation</b> field to query operations.
     * 
     */
    public final static ProductionOrderItemsField<String> STORAGE_LOCATION = new ProductionOrderItemsField<String>("StorageLocation");
    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>Batch</b></p>
     * 
     * @return
     *     Batch Number
     */
    @SerializedName("Batch")
    @JsonProperty("Batch")
    @Nullable
    @ODataField(odataName = "Batch")
    private String batch;
    /**
     * Use with available fluent helpers to apply the <b>Batch</b> field to query operations.
     * 
     */
    public final static ProductionOrderItemsField<String> BATCH = new ProductionOrderItemsField<String>("Batch");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>InventoryUsabilityCode</b></p>
     * 
     * @return
     *     Inventory Usability Code
     */
    @SerializedName("InventoryUsabilityCode")
    @JsonProperty("InventoryUsabilityCode")
    @Nullable
    @ODataField(odataName = "InventoryUsabilityCode")
    private String inventoryUsability;
    /**
     * Use with available fluent helpers to apply the <b>InventoryUsabilityCode</b> field to query operations.
     * 
     */
    public final static ProductionOrderItemsField<String> INVENTORY_USABILITY = new ProductionOrderItemsField<String>("InventoryUsabilityCode");
    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>GoodsRecipientName</b></p>
     * 
     * @return
     *     Goods Recipient
     */
    @SerializedName("GoodsRecipientName")
    @JsonProperty("GoodsRecipientName")
    @Nullable
    @ODataField(odataName = "GoodsRecipientName")
    private String goodsRecipient;
    /**
     * Use with available fluent helpers to apply the <b>GoodsRecipientName</b> field to query operations.
     * 
     */
    public final static ProductionOrderItemsField<String> GOODS_RECIPIENT = new ProductionOrderItemsField<String>("GoodsRecipientName");
    /**
     * Constraints: Not nullable, Maximum length: 25 <p>Original property name from the Odata EDM: <b>UnloadingPointName</b></p>
     * 
     * @return
     *     Unloading Point
     */
    @SerializedName("UnloadingPointName")
    @JsonProperty("UnloadingPointName")
    @Nullable
    @ODataField(odataName = "UnloadingPointName")
    private String unloadingPoint;
    /**
     * Use with available fluent helpers to apply the <b>UnloadingPointName</b> field to query operations.
     * 
     */
    public final static ProductionOrderItemsField<String> UNLOADING_POINT = new ProductionOrderItemsField<String>("UnloadingPointName");
    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>StockSegment</b></p>
     * 
     * @return
     *     Stock Segment
     */
    @SerializedName("StockSegment")
    @JsonProperty("StockSegment")
    @Nullable
    @ODataField(odataName = "StockSegment")
    private String stockSegment;
    /**
     * Use with available fluent helpers to apply the <b>StockSegment</b> field to query operations.
     * 
     */
    public final static ProductionOrderItemsField<String> STOCK_SEGMENT = new ProductionOrderItemsField<String>("StockSegment");
    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>MfgOrderItemPlndDeliveryDate</b></p>
     * 
     * @return
     *     Delivery Date From Planned Order
     */
    @SerializedName("MfgOrderItemPlndDeliveryDate")
    @JsonProperty("MfgOrderItemPlndDeliveryDate")
    @Nullable
    @JsonSerialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeSerializer.class)
    @JsonDeserialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeDeserializer.class)
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeAdapter.class)
    @ODataField(odataName = "MfgOrderItemPlndDeliveryDate", converter = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeCalendarConverter.class)
    private LocalDateTime plannedDelivery;
    /**
     * Use with available fluent helpers to apply the <b>MfgOrderItemPlndDeliveryDate</b> field to query operations.
     * 
     */
    public final static ProductionOrderItemsField<LocalDateTime> PLANNED_DELIVERY = new ProductionOrderItemsField<LocalDateTime>("MfgOrderItemPlndDeliveryDate");
    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>MfgOrderItemActualDeliveryDate</b></p>
     * 
     * @return
     *     Actual Delivery/Finish Date
     */
    @SerializedName("MfgOrderItemActualDeliveryDate")
    @JsonProperty("MfgOrderItemActualDeliveryDate")
    @Nullable
    @JsonSerialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeSerializer.class)
    @JsonDeserialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeDeserializer.class)
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeAdapter.class)
    @ODataField(odataName = "MfgOrderItemActualDeliveryDate", converter = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeCalendarConverter.class)
    private LocalDateTime actualDeliveryDate;
    /**
     * Use with available fluent helpers to apply the <b>MfgOrderItemActualDeliveryDate</b> field to query operations.
     * 
     */
    public final static ProductionOrderItemsField<LocalDateTime> ACTUAL_DELIVERY_DATE = new ProductionOrderItemsField<LocalDateTime>("MfgOrderItemActualDeliveryDate");
    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>ProductionUnit</b></p>
     * 
     * @return
     *     Production Unit of Measure
     */
    @SerializedName("ProductionUnit")
    @JsonProperty("ProductionUnit")
    @Nullable
    @ODataField(odataName = "ProductionUnit")
    private String productionUnit;
    /**
     * Use with available fluent helpers to apply the <b>ProductionUnit</b> field to query operations.
     * 
     */
    public final static ProductionOrderItemsField<String> PRODUCTION_UNIT = new ProductionOrderItemsField<String>("ProductionUnit");
    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>ProductionUnitISOCode</b></p>
     * 
     * @return
     *     ISO Code for Unit of Measurement
     */
    @SerializedName("ProductionUnitISOCode")
    @JsonProperty("ProductionUnitISOCode")
    @Nullable
    @ODataField(odataName = "ProductionUnitISOCode")
    private String iSOCode;
    /**
     * Use with available fluent helpers to apply the <b>ProductionUnitISOCode</b> field to query operations.
     * 
     */
    public final static ProductionOrderItemsField<String> ISO_CODE = new ProductionOrderItemsField<String>("ProductionUnitISOCode");
    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>ProductionUnitSAPCode</b></p>
     * 
     * @return
     *     Unit of Measurement, Internal SAP Code (No Conversion)
     */
    @SerializedName("ProductionUnitSAPCode")
    @JsonProperty("ProductionUnitSAPCode")
    @Nullable
    @ODataField(odataName = "ProductionUnitSAPCode")
    private String internalSAPCode;
    /**
     * Use with available fluent helpers to apply the <b>ProductionUnitSAPCode</b> field to query operations.
     * 
     */
    public final static ProductionOrderItemsField<String> INTERNAL_SAP_CODE = new ProductionOrderItemsField<String>("ProductionUnitSAPCode");
    /**
     * Constraints: Not nullable, Precision: 13, Scale: 3 <p>Original property name from the Odata EDM: <b>MfgOrderItemPlannedTotalQty</b></p>
     * 
     * @return
     *     Order Item Planned Total Quantity
     */
    @SerializedName("MfgOrderItemPlannedTotalQty")
    @JsonProperty("MfgOrderItemPlannedTotalQty")
    @Nullable
    @ODataField(odataName = "MfgOrderItemPlannedTotalQty")
    private BigDecimal totalQuantity;
    /**
     * Use with available fluent helpers to apply the <b>MfgOrderItemPlannedTotalQty</b> field to query operations.
     * 
     */
    public final static ProductionOrderItemsField<BigDecimal> TOTAL_QUANTITY = new ProductionOrderItemsField<BigDecimal>("MfgOrderItemPlannedTotalQty");
    /**
     * Constraints: Not nullable, Precision: 13, Scale: 3 <p>Original property name from the Odata EDM: <b>MfgOrderItemPlannedScrapQty</b></p>
     * 
     * @return
     *     Order Item Planned Scrap Quantity
     */
    @SerializedName("MfgOrderItemPlannedScrapQty")
    @JsonProperty("MfgOrderItemPlannedScrapQty")
    @Nullable
    @ODataField(odataName = "MfgOrderItemPlannedScrapQty")
    private BigDecimal plannedScrap;
    /**
     * Use with available fluent helpers to apply the <b>MfgOrderItemPlannedScrapQty</b> field to query operations.
     * 
     */
    public final static ProductionOrderItemsField<BigDecimal> PLANNED_SCRAP = new ProductionOrderItemsField<BigDecimal>("MfgOrderItemPlannedScrapQty");
    /**
     * Constraints: Not nullable, Precision: 13, Scale: 3 <p>Original property name from the Odata EDM: <b>MfgOrderItemGoodsReceiptQty</b></p>
     * 
     * @return
     *     Quantity of Goods Received for the Order Item
     */
    @SerializedName("MfgOrderItemGoodsReceiptQty")
    @JsonProperty("MfgOrderItemGoodsReceiptQty")
    @Nullable
    @ODataField(odataName = "MfgOrderItemGoodsReceiptQty")
    private BigDecimal goodsReceiptQuantity;
    /**
     * Use with available fluent helpers to apply the <b>MfgOrderItemGoodsReceiptQty</b> field to query operations.
     * 
     */
    public final static ProductionOrderItemsField<BigDecimal> GOODS_RECEIPT_QUANTITY = new ProductionOrderItemsField<BigDecimal>("MfgOrderItemGoodsReceiptQty");
    /**
     * Constraints: Not nullable, Precision: 13, Scale: 3 <p>Original property name from the Odata EDM: <b>MfgOrderItemActualDeviationQty</b></p>
     * 
     * @return
     *     Expected Surplus/Deficit For Goods Receipt
     */
    @SerializedName("MfgOrderItemActualDeviationQty")
    @JsonProperty("MfgOrderItemActualDeviationQty")
    @Nullable
    @ODataField(odataName = "MfgOrderItemActualDeviationQty")
    private BigDecimal expectedDeviation;
    /**
     * Use with available fluent helpers to apply the <b>MfgOrderItemActualDeviationQty</b> field to query operations.
     * 
     */
    public final static ProductionOrderItemsField<BigDecimal> EXPECTED_DEVIATION = new ProductionOrderItemsField<BigDecimal>("MfgOrderItemActualDeviationQty");
    /**
     * Navigation property <b>to_ProdnOrderItemSerialNumber</b> for <b>ProductionOrderItems</b> to multiple <b>ProductionOrderSerialNumbers</b>.
     * 
     */
    @SerializedName("to_ProdnOrderItemSerialNumber")
    @JsonProperty("to_ProdnOrderItemSerialNumber")
    @ODataField(odataName = "to_ProdnOrderItemSerialNumber")
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private List<ProductionOrderSerialNumbers> toProdnOrderItemSerialNumber;
    /**
     * Use with available fluent helpers to apply the <b>to_ProdnOrderItemSerialNumber</b> navigation property to query operations.
     * 
     */
    public final static ProductionOrderItemsLink<ProductionOrderSerialNumbers> TO_PRODN_ORDER_ITEM_SERIAL_NUMBER = new ProductionOrderItemsLink<ProductionOrderSerialNumbers>("to_ProdnOrderItemSerialNumber");

    @Nonnull
    @Override
    public Class<ProductionOrderItems> getType() {
        return ProductionOrderItems.class;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>ManufacturingOrder</b></p>
     * 
     * @param productionOrder
     *     Production Order
     */
    public void setProductionOrder(
        @Nullable
        final String productionOrder) {
        rememberChangedField("ManufacturingOrder", this.productionOrder);
        this.productionOrder = productionOrder;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>ManufacturingOrderItem</b></p>
     * 
     * @param manufacturingOrderItem
     *     Manufacturing Order Item ID
     */
    public void setManufacturingOrderItem(
        @Nullable
        final String manufacturingOrderItem) {
        rememberChangedField("ManufacturingOrderItem", this.manufacturingOrderItem);
        this.manufacturingOrderItem = manufacturingOrderItem;
    }

    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>ManufacturingOrderCategory</b></p>
     * 
     * @param orderCategory
     *     Manufacturing Order Category
     */
    public void setOrderCategory(
        @Nullable
        final String orderCategory) {
        rememberChangedField("ManufacturingOrderCategory", this.orderCategory);
        this.orderCategory = orderCategory;
    }

    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>ManufacturingOrderType</b></p>
     * 
     * @param orderType
     *     Manufacturing Order Type
     */
    public void setOrderType(
        @Nullable
        final String orderType) {
        rememberChangedField("ManufacturingOrderType", this.orderType);
        this.orderType = orderType;
    }

    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>IsCompletelyDelivered</b></p>
     * 
     * @param deliveryCompleted
     *     "Delivery Completed" Indicator
     */
    public void setDeliveryCompleted(
        @Nullable
        final Boolean deliveryCompleted) {
        rememberChangedField("IsCompletelyDelivered", this.deliveryCompleted);
        this.deliveryCompleted = deliveryCompleted;
    }

    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>Material</b></p>
     * 
     * @param material
     *     Material Number for Order
     */
    public void setMaterial(
        @Nullable
        final String material) {
        rememberChangedField("Material", this.material);
        this.material = material;
    }

    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>ProductionPlant</b></p>
     * 
     * @param productionPlant
     *     Production Plant
     */
    public void setProductionPlant(
        @Nullable
        final String productionPlant) {
        rememberChangedField("ProductionPlant", this.productionPlant);
        this.productionPlant = productionPlant;
    }

    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>Plant</b></p>
     * 
     * @param planningPlant
     *     Planning Plant for an Order
     */
    public void setPlanningPlant(
        @Nullable
        final String planningPlant) {
        rememberChangedField("Plant", this.planningPlant);
        this.planningPlant = planningPlant;
    }

    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>MRPArea</b></p>
     * 
     * @param mRPArea
     *     MRP Area
     */
    public void setMRPArea(
        @Nullable
        final String mRPArea) {
        rememberChangedField("MRPArea", this.mRPArea);
        this.mRPArea = mRPArea;
    }

    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>QuantityDistributionKey</b></p>
     * 
     * @param distributionKey
     *     MRP Distribution Key
     */
    public void setDistributionKey(
        @Nullable
        final String distributionKey) {
        rememberChangedField("QuantityDistributionKey", this.distributionKey);
        this.distributionKey = distributionKey;
    }

    /**
     * Constraints: Not nullable, Precision: 3, Scale: 0 <p>Original property name from the Odata EDM: <b>MaterialGoodsReceiptDuration</b></p>
     * 
     * @param gRProcessingTime
     *     Goods Receipt Processing Duration in Days
     */
    public void setGRProcessingTime(
        @Nullable
        final BigDecimal gRProcessingTime) {
        rememberChangedField("MaterialGoodsReceiptDuration", this.gRProcessingTime);
        this.gRProcessingTime = gRProcessingTime;
    }

    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>StorageLocation</b></p>
     * 
     * @param storageLocation
     *     Storage Location
     */
    public void setStorageLocation(
        @Nullable
        final String storageLocation) {
        rememberChangedField("StorageLocation", this.storageLocation);
        this.storageLocation = storageLocation;
    }

    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>Batch</b></p>
     * 
     * @param batch
     *     Batch Number
     */
    public void setBatch(
        @Nullable
        final String batch) {
        rememberChangedField("Batch", this.batch);
        this.batch = batch;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>InventoryUsabilityCode</b></p>
     * 
     * @param inventoryUsability
     *     Inventory Usability Code
     */
    public void setInventoryUsability(
        @Nullable
        final String inventoryUsability) {
        rememberChangedField("InventoryUsabilityCode", this.inventoryUsability);
        this.inventoryUsability = inventoryUsability;
    }

    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>GoodsRecipientName</b></p>
     * 
     * @param goodsRecipient
     *     Goods Recipient
     */
    public void setGoodsRecipient(
        @Nullable
        final String goodsRecipient) {
        rememberChangedField("GoodsRecipientName", this.goodsRecipient);
        this.goodsRecipient = goodsRecipient;
    }

    /**
     * Constraints: Not nullable, Maximum length: 25 <p>Original property name from the Odata EDM: <b>UnloadingPointName</b></p>
     * 
     * @param unloadingPoint
     *     Unloading Point
     */
    public void setUnloadingPoint(
        @Nullable
        final String unloadingPoint) {
        rememberChangedField("UnloadingPointName", this.unloadingPoint);
        this.unloadingPoint = unloadingPoint;
    }

    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>StockSegment</b></p>
     * 
     * @param stockSegment
     *     Stock Segment
     */
    public void setStockSegment(
        @Nullable
        final String stockSegment) {
        rememberChangedField("StockSegment", this.stockSegment);
        this.stockSegment = stockSegment;
    }

    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>MfgOrderItemPlndDeliveryDate</b></p>
     * 
     * @param plannedDelivery
     *     Delivery Date From Planned Order
     */
    public void setPlannedDelivery(
        @Nullable
        final LocalDateTime plannedDelivery) {
        rememberChangedField("MfgOrderItemPlndDeliveryDate", this.plannedDelivery);
        this.plannedDelivery = plannedDelivery;
    }

    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>MfgOrderItemActualDeliveryDate</b></p>
     * 
     * @param actualDeliveryDate
     *     Actual Delivery/Finish Date
     */
    public void setActualDeliveryDate(
        @Nullable
        final LocalDateTime actualDeliveryDate) {
        rememberChangedField("MfgOrderItemActualDeliveryDate", this.actualDeliveryDate);
        this.actualDeliveryDate = actualDeliveryDate;
    }

    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>ProductionUnit</b></p>
     * 
     * @param productionUnit
     *     Production Unit of Measure
     */
    public void setProductionUnit(
        @Nullable
        final String productionUnit) {
        rememberChangedField("ProductionUnit", this.productionUnit);
        this.productionUnit = productionUnit;
    }

    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>ProductionUnitISOCode</b></p>
     * 
     * @param iSOCode
     *     ISO Code for Unit of Measurement
     */
    public void setISOCode(
        @Nullable
        final String iSOCode) {
        rememberChangedField("ProductionUnitISOCode", this.iSOCode);
        this.iSOCode = iSOCode;
    }

    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>ProductionUnitSAPCode</b></p>
     * 
     * @param internalSAPCode
     *     Unit of Measurement, Internal SAP Code (No Conversion)
     */
    public void setInternalSAPCode(
        @Nullable
        final String internalSAPCode) {
        rememberChangedField("ProductionUnitSAPCode", this.internalSAPCode);
        this.internalSAPCode = internalSAPCode;
    }

    /**
     * Constraints: Not nullable, Precision: 13, Scale: 3 <p>Original property name from the Odata EDM: <b>MfgOrderItemPlannedTotalQty</b></p>
     * 
     * @param totalQuantity
     *     Order Item Planned Total Quantity
     */
    public void setTotalQuantity(
        @Nullable
        final BigDecimal totalQuantity) {
        rememberChangedField("MfgOrderItemPlannedTotalQty", this.totalQuantity);
        this.totalQuantity = totalQuantity;
    }

    /**
     * Constraints: Not nullable, Precision: 13, Scale: 3 <p>Original property name from the Odata EDM: <b>MfgOrderItemPlannedScrapQty</b></p>
     * 
     * @param plannedScrap
     *     Order Item Planned Scrap Quantity
     */
    public void setPlannedScrap(
        @Nullable
        final BigDecimal plannedScrap) {
        rememberChangedField("MfgOrderItemPlannedScrapQty", this.plannedScrap);
        this.plannedScrap = plannedScrap;
    }

    /**
     * Constraints: Not nullable, Precision: 13, Scale: 3 <p>Original property name from the Odata EDM: <b>MfgOrderItemGoodsReceiptQty</b></p>
     * 
     * @param goodsReceiptQuantity
     *     Quantity of Goods Received for the Order Item
     */
    public void setGoodsReceiptQuantity(
        @Nullable
        final BigDecimal goodsReceiptQuantity) {
        rememberChangedField("MfgOrderItemGoodsReceiptQty", this.goodsReceiptQuantity);
        this.goodsReceiptQuantity = goodsReceiptQuantity;
    }

    /**
     * Constraints: Not nullable, Precision: 13, Scale: 3 <p>Original property name from the Odata EDM: <b>MfgOrderItemActualDeviationQty</b></p>
     * 
     * @param expectedDeviation
     *     Expected Surplus/Deficit For Goods Receipt
     */
    public void setExpectedDeviation(
        @Nullable
        final BigDecimal expectedDeviation) {
        rememberChangedField("MfgOrderItemActualDeviationQty", this.expectedDeviation);
        this.expectedDeviation = expectedDeviation;
    }

    @Override
    protected String getEntityCollection() {
        return "A_ProductionOrderItem_2";
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        result.put("ManufacturingOrder", getProductionOrder());
        result.put("ManufacturingOrderItem", getManufacturingOrderItem());
        return result;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("ManufacturingOrder", getProductionOrder());
        values.put("ManufacturingOrderItem", getManufacturingOrderItem());
        values.put("ManufacturingOrderCategory", getOrderCategory());
        values.put("ManufacturingOrderType", getOrderType());
        values.put("IsCompletelyDelivered", getDeliveryCompleted());
        values.put("Material", getMaterial());
        values.put("ProductionPlant", getProductionPlant());
        values.put("Plant", getPlanningPlant());
        values.put("MRPArea", getMRPArea());
        values.put("QuantityDistributionKey", getDistributionKey());
        values.put("MaterialGoodsReceiptDuration", getGRProcessingTime());
        values.put("StorageLocation", getStorageLocation());
        values.put("Batch", getBatch());
        values.put("InventoryUsabilityCode", getInventoryUsability());
        values.put("GoodsRecipientName", getGoodsRecipient());
        values.put("UnloadingPointName", getUnloadingPoint());
        values.put("StockSegment", getStockSegment());
        values.put("MfgOrderItemPlndDeliveryDate", getPlannedDelivery());
        values.put("MfgOrderItemActualDeliveryDate", getActualDeliveryDate());
        values.put("ProductionUnit", getProductionUnit());
        values.put("ProductionUnitISOCode", getISOCode());
        values.put("ProductionUnitSAPCode", getInternalSAPCode());
        values.put("MfgOrderItemPlannedTotalQty", getTotalQuantity());
        values.put("MfgOrderItemPlannedScrapQty", getPlannedScrap());
        values.put("MfgOrderItemGoodsReceiptQty", getGoodsReceiptQuantity());
        values.put("MfgOrderItemActualDeviationQty", getExpectedDeviation());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("ManufacturingOrder")) {
                final Object value = values.remove("ManufacturingOrder");
                if ((value == null)||(!value.equals(getProductionOrder()))) {
                    setProductionOrder(((String) value));
                }
            }
            if (values.containsKey("ManufacturingOrderItem")) {
                final Object value = values.remove("ManufacturingOrderItem");
                if ((value == null)||(!value.equals(getManufacturingOrderItem()))) {
                    setManufacturingOrderItem(((String) value));
                }
            }
            if (values.containsKey("ManufacturingOrderCategory")) {
                final Object value = values.remove("ManufacturingOrderCategory");
                if ((value == null)||(!value.equals(getOrderCategory()))) {
                    setOrderCategory(((String) value));
                }
            }
            if (values.containsKey("ManufacturingOrderType")) {
                final Object value = values.remove("ManufacturingOrderType");
                if ((value == null)||(!value.equals(getOrderType()))) {
                    setOrderType(((String) value));
                }
            }
            if (values.containsKey("IsCompletelyDelivered")) {
                final Object value = values.remove("IsCompletelyDelivered");
                if ((value == null)||(!value.equals(getDeliveryCompleted()))) {
                    setDeliveryCompleted(((Boolean) value));
                }
            }
            if (values.containsKey("Material")) {
                final Object value = values.remove("Material");
                if ((value == null)||(!value.equals(getMaterial()))) {
                    setMaterial(((String) value));
                }
            }
            if (values.containsKey("ProductionPlant")) {
                final Object value = values.remove("ProductionPlant");
                if ((value == null)||(!value.equals(getProductionPlant()))) {
                    setProductionPlant(((String) value));
                }
            }
            if (values.containsKey("Plant")) {
                final Object value = values.remove("Plant");
                if ((value == null)||(!value.equals(getPlanningPlant()))) {
                    setPlanningPlant(((String) value));
                }
            }
            if (values.containsKey("MRPArea")) {
                final Object value = values.remove("MRPArea");
                if ((value == null)||(!value.equals(getMRPArea()))) {
                    setMRPArea(((String) value));
                }
            }
            if (values.containsKey("QuantityDistributionKey")) {
                final Object value = values.remove("QuantityDistributionKey");
                if ((value == null)||(!value.equals(getDistributionKey()))) {
                    setDistributionKey(((String) value));
                }
            }
            if (values.containsKey("MaterialGoodsReceiptDuration")) {
                final Object value = values.remove("MaterialGoodsReceiptDuration");
                if ((value == null)||(!value.equals(getGRProcessingTime()))) {
                    setGRProcessingTime(((BigDecimal) value));
                }
            }
            if (values.containsKey("StorageLocation")) {
                final Object value = values.remove("StorageLocation");
                if ((value == null)||(!value.equals(getStorageLocation()))) {
                    setStorageLocation(((String) value));
                }
            }
            if (values.containsKey("Batch")) {
                final Object value = values.remove("Batch");
                if ((value == null)||(!value.equals(getBatch()))) {
                    setBatch(((String) value));
                }
            }
            if (values.containsKey("InventoryUsabilityCode")) {
                final Object value = values.remove("InventoryUsabilityCode");
                if ((value == null)||(!value.equals(getInventoryUsability()))) {
                    setInventoryUsability(((String) value));
                }
            }
            if (values.containsKey("GoodsRecipientName")) {
                final Object value = values.remove("GoodsRecipientName");
                if ((value == null)||(!value.equals(getGoodsRecipient()))) {
                    setGoodsRecipient(((String) value));
                }
            }
            if (values.containsKey("UnloadingPointName")) {
                final Object value = values.remove("UnloadingPointName");
                if ((value == null)||(!value.equals(getUnloadingPoint()))) {
                    setUnloadingPoint(((String) value));
                }
            }
            if (values.containsKey("StockSegment")) {
                final Object value = values.remove("StockSegment");
                if ((value == null)||(!value.equals(getStockSegment()))) {
                    setStockSegment(((String) value));
                }
            }
            if (values.containsKey("MfgOrderItemPlndDeliveryDate")) {
                final Object value = values.remove("MfgOrderItemPlndDeliveryDate");
                if ((value == null)||(!value.equals(getPlannedDelivery()))) {
                    setPlannedDelivery(((LocalDateTime) value));
                }
            }
            if (values.containsKey("MfgOrderItemActualDeliveryDate")) {
                final Object value = values.remove("MfgOrderItemActualDeliveryDate");
                if ((value == null)||(!value.equals(getActualDeliveryDate()))) {
                    setActualDeliveryDate(((LocalDateTime) value));
                }
            }
            if (values.containsKey("ProductionUnit")) {
                final Object value = values.remove("ProductionUnit");
                if ((value == null)||(!value.equals(getProductionUnit()))) {
                    setProductionUnit(((String) value));
                }
            }
            if (values.containsKey("ProductionUnitISOCode")) {
                final Object value = values.remove("ProductionUnitISOCode");
                if ((value == null)||(!value.equals(getISOCode()))) {
                    setISOCode(((String) value));
                }
            }
            if (values.containsKey("ProductionUnitSAPCode")) {
                final Object value = values.remove("ProductionUnitSAPCode");
                if ((value == null)||(!value.equals(getInternalSAPCode()))) {
                    setInternalSAPCode(((String) value));
                }
            }
            if (values.containsKey("MfgOrderItemPlannedTotalQty")) {
                final Object value = values.remove("MfgOrderItemPlannedTotalQty");
                if ((value == null)||(!value.equals(getTotalQuantity()))) {
                    setTotalQuantity(((BigDecimal) value));
                }
            }
            if (values.containsKey("MfgOrderItemPlannedScrapQty")) {
                final Object value = values.remove("MfgOrderItemPlannedScrapQty");
                if ((value == null)||(!value.equals(getPlannedScrap()))) {
                    setPlannedScrap(((BigDecimal) value));
                }
            }
            if (values.containsKey("MfgOrderItemGoodsReceiptQty")) {
                final Object value = values.remove("MfgOrderItemGoodsReceiptQty");
                if ((value == null)||(!value.equals(getGoodsReceiptQuantity()))) {
                    setGoodsReceiptQuantity(((BigDecimal) value));
                }
            }
            if (values.containsKey("MfgOrderItemActualDeviationQty")) {
                final Object value = values.remove("MfgOrderItemActualDeviationQty");
                if ((value == null)||(!value.equals(getExpectedDeviation()))) {
                    setExpectedDeviation(((BigDecimal) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
            if ((values).containsKey("to_ProdnOrderItemSerialNumber")) {
                final Object value = (values).remove("to_ProdnOrderItemSerialNumber");
                if (value instanceof Iterable) {
                    if (toProdnOrderItemSerialNumber == null) {
                        toProdnOrderItemSerialNumber = Lists.newArrayList();
                    } else {
                        toProdnOrderItemSerialNumber = Lists.newArrayList(toProdnOrderItemSerialNumber);
                    }
                    int i = 0;
                    for (Object item: ((Iterable<?> ) value)) {
                        if (!(item instanceof Map)) {
                            continue;
                        }
                        ProductionOrderSerialNumbers entity;
                        if (toProdnOrderItemSerialNumber.size()>i) {
                            entity = toProdnOrderItemSerialNumber.get(i);
                        } else {
                            entity = new ProductionOrderSerialNumbers();
                            toProdnOrderItemSerialNumber.add(entity);
                        }
                        i = (i + 1);
                        @SuppressWarnings("unchecked")
                        final Map<String, Object> inputMap = ((Map<String, Object> ) item);
                        entity.fromMap(inputMap);
                    }
                }
            }
        }
        super.fromMap(values);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param fieldType
     *     The Java type to use for the extension field when performing value comparisons.
     * @return
     *     A representation of an extension field from this entity.
     */
    @Nonnull
    public static<T >ProductionOrderItemsField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final Class<T> fieldType) {
        return new ProductionOrderItemsField<T>(fieldName);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param typeConverter
     *     A TypeConverter<T, DomainT> instance whose first generic type matches the Java type of the field
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param <DomainT>
     *     The type of the extension field as returned by the OData service.
     * @return
     *     A representation of an extension field from this entity, holding a reference to the given TypeConverter.
     */
    @Nonnull
    public static<T,DomainT >ProductionOrderItemsField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final TypeConverter<T, DomainT> typeConverter) {
        return new ProductionOrderItemsField<T>(fieldName, typeConverter);
    }

    @Override
    @Nullable
    public Destination getDestinationForFetch() {
        return super.getDestinationForFetch();
    }

    @Override
    protected void setServicePathForFetch(
        @Nullable
        final String servicePathForFetch) {
        super.setServicePathForFetch(servicePathForFetch);
    }

    @Override
    public void attachToService(
        @Nullable
        final String servicePath,
        @Nonnull
        final Destination destination) {
        super.attachToService(servicePath, destination);
    }

    @Override
    protected String getDefaultServicePath() {
        return (com.sap.cloud.sdk.tutorial.datamodel.odata.services.APIPRODUCTIONORDER2SRVService.DEFAULT_SERVICE_PATH);
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfNavigationProperties() {
        final Map<String, Object> values = super.toMapOfNavigationProperties();
        if (toProdnOrderItemSerialNumber!= null) {
            (values).put("to_ProdnOrderItemSerialNumber", toProdnOrderItemSerialNumber);
        }
        return values;
    }

    /**
     * Fetches the <b>ProductionOrderSerialNumbers</b> entities (one to many) associated with this entity. This corresponds to the OData navigation property <b>to_ProdnOrderItemSerialNumber</b>.
     * <p>
     * Please note: This method will not cache or persist the query results.
     * 
     * @return
     *     List containing one or more associated <b>ProductionOrderSerialNumbers</b> entities. If no entities are associated then an empty list is returned. 
     * @throws ODataException
     *     If the entity is unmanaged, i.e. it has not been retrieved using the OData VDM's services and therefore has no ERP configuration context assigned. An entity is managed if it has been either retrieved using the VDM's services or returned from the VDM's services as the result of a CREATE or UPDATE call. 
     */
    @Nonnull
    public List<ProductionOrderSerialNumbers> fetchProdnOrderItemSerialNumber() {
        return fetchFieldAsList("to_ProdnOrderItemSerialNumber", ProductionOrderSerialNumbers.class);
    }

    /**
     * Retrieval of associated <b>ProductionOrderSerialNumbers</b> entities (one to many). This corresponds to the OData navigation property <b>to_ProdnOrderItemSerialNumber</b>.
     * <p>
     * If the navigation property <b>to_ProdnOrderItemSerialNumber</b> of a queried <b>ProductionOrderItems</b> is operated lazily, an <b>ODataException</b> can be thrown in case of an OData query error.
     * <p>
     * Please note: <i>Lazy</i> loading of OData entity associations is the process of asynchronous retrieval and persisting of items from a navigation property. If a <i>lazy</i> property is requested by the application for the first time and it has not yet been loaded, an OData query will be run in order to load the missing information and its result will get cached for future invocations.
     * 
     * @return
     *     List of associated <b>ProductionOrderSerialNumbers</b> entities.
     * @throws ODataException
     *     If the entity is unmanaged, i.e. it has not been retrieved using the OData VDM's services and therefore has no ERP configuration context assigned. An entity is managed if it has been either retrieved using the VDM's services or returned from the VDM's services as the result of a CREATE or UPDATE call. 
     */
    @Nonnull
    public List<ProductionOrderSerialNumbers> getProdnOrderItemSerialNumberOrFetch() {
        if (toProdnOrderItemSerialNumber == null) {
            toProdnOrderItemSerialNumber = fetchProdnOrderItemSerialNumber();
        }
        return toProdnOrderItemSerialNumber;
    }

    /**
     * Retrieval of associated <b>ProductionOrderSerialNumbers</b> entities (one to many). This corresponds to the OData navigation property <b>to_ProdnOrderItemSerialNumber</b>.
     * <p>
     * If the navigation property for an entity <b>ProductionOrderItems</b> has not been resolved yet, this method will <b>not query</b> further information. Instead its <code>Option</code> result state will be <code>empty</code>.
     * 
     * @return
     *     If the information for navigation property <b>to_ProdnOrderItemSerialNumber</b> is already loaded, the result will contain the <b>ProductionOrderSerialNumbers</b> entities. If not, an <code>Option</code> with result state <code>empty</code> is returned.
     */
    @Nonnull
    public Option<List<ProductionOrderSerialNumbers>> getProdnOrderItemSerialNumberIfPresent() {
        return Option.of(toProdnOrderItemSerialNumber);
    }

    /**
     * Overwrites the list of associated <b>ProductionOrderSerialNumbers</b> entities for the loaded navigation property <b>to_ProdnOrderItemSerialNumber</b>.
     * <p>
     * If the navigation property <b>to_ProdnOrderItemSerialNumber</b> of a queried <b>ProductionOrderItems</b> is operated lazily, an <b>ODataException</b> can be thrown in case of an OData query error.
     * <p>
     * Please note: <i>Lazy</i> loading of OData entity associations is the process of asynchronous retrieval and persisting of items from a navigation property. If a <i>lazy</i> property is requested by the application for the first time and it has not yet been loaded, an OData query will be run in order to load the missing information and its result will get cached for future invocations.
     * 
     * @param value
     *     List of <b>ProductionOrderSerialNumbers</b> entities.
     */
    public void setProdnOrderItemSerialNumber(
        @Nonnull
        final List<ProductionOrderSerialNumbers> value) {
        if (toProdnOrderItemSerialNumber == null) {
            toProdnOrderItemSerialNumber = Lists.newArrayList();
        }
        toProdnOrderItemSerialNumber.clear();
        toProdnOrderItemSerialNumber.addAll(value);
    }

    /**
     * Adds elements to the list of associated <b>ProductionOrderSerialNumbers</b> entities. This corresponds to the OData navigation property <b>to_ProdnOrderItemSerialNumber</b>.
     * <p>
     * If the navigation property <b>to_ProdnOrderItemSerialNumber</b> of a queried <b>ProductionOrderItems</b> is operated lazily, an <b>ODataException</b> can be thrown in case of an OData query error.
     * <p>
     * Please note: <i>Lazy</i> loading of OData entity associations is the process of asynchronous retrieval and persisting of items from a navigation property. If a <i>lazy</i> property is requested by the application for the first time and it has not yet been loaded, an OData query will be run in order to load the missing information and its result will get cached for future invocations.
     * 
     * @param entity
     *     Array of <b>ProductionOrderSerialNumbers</b> entities.
     */
    public void addProdnOrderItemSerialNumber(ProductionOrderSerialNumbers... entity) {
        if (toProdnOrderItemSerialNumber == null) {
            toProdnOrderItemSerialNumber = Lists.newArrayList();
        }
        toProdnOrderItemSerialNumber.addAll(Lists.newArrayList(entity));
    }


    /**
     * Helper class to allow for fluent creation of ProductionOrderItems instances.
     * 
     */
    public final static class ProductionOrderItemsBuilder {

        private List<ProductionOrderSerialNumbers> toProdnOrderItemSerialNumber = Lists.newArrayList();

        private ProductionOrderItems.ProductionOrderItemsBuilder toProdnOrderItemSerialNumber(final List<ProductionOrderSerialNumbers> value) {
            toProdnOrderItemSerialNumber.addAll(value);
            return this;
        }

        /**
         * Navigation property <b>to_ProdnOrderItemSerialNumber</b> for <b>ProductionOrderItems</b> to multiple <b>ProductionOrderSerialNumbers</b>.
         * 
         * @param value
         *     The ProductionOrderSerialNumberss to build this ProductionOrderItems with.
         * @return
         *     This Builder to allow for a fluent interface.
         */
        @Nonnull
        public ProductionOrderItems.ProductionOrderItemsBuilder prodnOrderItemSerialNumber(ProductionOrderSerialNumbers... value) {
            return toProdnOrderItemSerialNumber(Lists.newArrayList(value));
        }

    }

}
