
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv;

import java.time.LocalDateTime;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.cloudplatform.connectivity.Destination;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmEntity;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import com.sap.cloud.sdk.s4hana.datamodel.odata.annotation.Key;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.field.ProductionOrderSerialNumbersField;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.selectable.ProductionOrderSerialNumbersSelectable;
import com.sap.cloud.sdk.typeconverter.TypeConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * Production Order Serial Numbers<p></p><p>Original entity name from the Odata EDM: <b>A_ProdnOrderItemSerialNumberType</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class ProductionOrderSerialNumbers
    extends VdmEntity<ProductionOrderSerialNumbers>
{

    /**
     * Selector for all available fields of ProductionOrderSerialNumbers.
     * 
     */
    public final static ProductionOrderSerialNumbersSelectable ALL_FIELDS = () -> "*";
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>ManufacturingOrder</b></p>
     * 
     * @return
     *     Manufacturing Order ID
     */
    @Key
    @SerializedName("ManufacturingOrder")
    @JsonProperty("ManufacturingOrder")
    @Nullable
    @ODataField(odataName = "ManufacturingOrder")
    private String manufacturingOrder;
    /**
     * Use with available fluent helpers to apply the <b>ManufacturingOrder</b> field to query operations.
     * 
     */
    public final static ProductionOrderSerialNumbersField<String> MANUFACTURING_ORDER = new ProductionOrderSerialNumbersField<String>("ManufacturingOrder");
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>ManufacturingOrderItem</b></p>
     * 
     * @return
     *     Manufacturing Order Item ID
     */
    @Key
    @SerializedName("ManufacturingOrderItem")
    @JsonProperty("ManufacturingOrderItem")
    @Nullable
    @ODataField(odataName = "ManufacturingOrderItem")
    private String manufacturingOrderItem;
    /**
     * Use with available fluent helpers to apply the <b>ManufacturingOrderItem</b> field to query operations.
     * 
     */
    public final static ProductionOrderSerialNumbersField<String> MANUFACTURING_ORDER_ITEM = new ProductionOrderSerialNumbersField<String>("ManufacturingOrderItem");
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 18 <p>Original property name from the Odata EDM: <b>SerialNumber</b></p>
     * 
     * @return
     *     Serial Number
     */
    @Key
    @SerializedName("SerialNumber")
    @JsonProperty("SerialNumber")
    @Nullable
    @ODataField(odataName = "SerialNumber")
    private String serialNumber;
    /**
     * Use with available fluent helpers to apply the <b>SerialNumber</b> field to query operations.
     * 
     */
    public final static ProductionOrderSerialNumbersField<String> SERIAL_NUMBER = new ProductionOrderSerialNumbersField<String>("SerialNumber");
    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>SerialNumberProfile</b></p>
     * 
     * @return
     *     Serial Number Profile
     */
    @SerializedName("SerialNumberProfile")
    @JsonProperty("SerialNumberProfile")
    @Nullable
    @ODataField(odataName = "SerialNumberProfile")
    private String serialNumberProfile;
    /**
     * Use with available fluent helpers to apply the <b>SerialNumberProfile</b> field to query operations.
     * 
     */
    public final static ProductionOrderSerialNumbersField<String> SERIAL_NUMBER_PROFILE = new ProductionOrderSerialNumbersField<String>("SerialNumberProfile");
    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>Product</b></p>
     * 
     * @return
     *     Product Number
     */
    @SerializedName("Product")
    @JsonProperty("Product")
    @Nullable
    @ODataField(odataName = "Product")
    private String product;
    /**
     * Use with available fluent helpers to apply the <b>Product</b> field to query operations.
     * 
     */
    public final static ProductionOrderSerialNumbersField<String> PRODUCT = new ProductionOrderSerialNumbersField<String>("Product");
    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>ProductionPlant</b></p>
     * 
     * @return
     *     Production Plant
     */
    @SerializedName("ProductionPlant")
    @JsonProperty("ProductionPlant")
    @Nullable
    @ODataField(odataName = "ProductionPlant")
    private String productionPlant;
    /**
     * Use with available fluent helpers to apply the <b>ProductionPlant</b> field to query operations.
     * 
     */
    public final static ProductionOrderSerialNumbersField<String> PRODUCTION_PLANT = new ProductionOrderSerialNumbersField<String>("ProductionPlant");
    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>ManufacturingOrderCategory</b></p>
     * 
     * @return
     *     Manufacturing Order Category
     */
    @SerializedName("ManufacturingOrderCategory")
    @JsonProperty("ManufacturingOrderCategory")
    @Nullable
    @ODataField(odataName = "ManufacturingOrderCategory")
    private String orderCategory;
    /**
     * Use with available fluent helpers to apply the <b>ManufacturingOrderCategory</b> field to query operations.
     * 
     */
    public final static ProductionOrderSerialNumbersField<String> ORDER_CATEGORY = new ProductionOrderSerialNumbersField<String>("ManufacturingOrderCategory");
    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>ManufacturingOrderType</b></p>
     * 
     * @return
     *     Manufacturing Order Type
     */
    @SerializedName("ManufacturingOrderType")
    @JsonProperty("ManufacturingOrderType")
    @Nullable
    @ODataField(odataName = "ManufacturingOrderType")
    private String orderType;
    /**
     * Use with available fluent helpers to apply the <b>ManufacturingOrderType</b> field to query operations.
     * 
     */
    public final static ProductionOrderSerialNumbersField<String> ORDER_TYPE = new ProductionOrderSerialNumbersField<String>("ManufacturingOrderType");
    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>DocumentDate</b></p>
     * 
     * @return
     *     Date
     */
    @SerializedName("DocumentDate")
    @JsonProperty("DocumentDate")
    @Nullable
    @JsonSerialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeSerializer.class)
    @JsonDeserialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeDeserializer.class)
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeAdapter.class)
    @ODataField(odataName = "DocumentDate", converter = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeCalendarConverter.class)
    private LocalDateTime date;
    /**
     * Use with available fluent helpers to apply the <b>DocumentDate</b> field to query operations.
     * 
     */
    public final static ProductionOrderSerialNumbersField<LocalDateTime> DATE = new ProductionOrderSerialNumbersField<LocalDateTime>("DocumentDate");

    @Nonnull
    @Override
    public Class<ProductionOrderSerialNumbers> getType() {
        return ProductionOrderSerialNumbers.class;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>ManufacturingOrder</b></p>
     * 
     * @param manufacturingOrder
     *     Manufacturing Order ID
     */
    public void setManufacturingOrder(
        @Nullable
        final String manufacturingOrder) {
        rememberChangedField("ManufacturingOrder", this.manufacturingOrder);
        this.manufacturingOrder = manufacturingOrder;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>ManufacturingOrderItem</b></p>
     * 
     * @param manufacturingOrderItem
     *     Manufacturing Order Item ID
     */
    public void setManufacturingOrderItem(
        @Nullable
        final String manufacturingOrderItem) {
        rememberChangedField("ManufacturingOrderItem", this.manufacturingOrderItem);
        this.manufacturingOrderItem = manufacturingOrderItem;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 18 <p>Original property name from the Odata EDM: <b>SerialNumber</b></p>
     * 
     * @param serialNumber
     *     Serial Number
     */
    public void setSerialNumber(
        @Nullable
        final String serialNumber) {
        rememberChangedField("SerialNumber", this.serialNumber);
        this.serialNumber = serialNumber;
    }

    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>SerialNumberProfile</b></p>
     * 
     * @param serialNumberProfile
     *     Serial Number Profile
     */
    public void setSerialNumberProfile(
        @Nullable
        final String serialNumberProfile) {
        rememberChangedField("SerialNumberProfile", this.serialNumberProfile);
        this.serialNumberProfile = serialNumberProfile;
    }

    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>Product</b></p>
     * 
     * @param product
     *     Product Number
     */
    public void setProduct(
        @Nullable
        final String product) {
        rememberChangedField("Product", this.product);
        this.product = product;
    }

    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>ProductionPlant</b></p>
     * 
     * @param productionPlant
     *     Production Plant
     */
    public void setProductionPlant(
        @Nullable
        final String productionPlant) {
        rememberChangedField("ProductionPlant", this.productionPlant);
        this.productionPlant = productionPlant;
    }

    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>ManufacturingOrderCategory</b></p>
     * 
     * @param orderCategory
     *     Manufacturing Order Category
     */
    public void setOrderCategory(
        @Nullable
        final String orderCategory) {
        rememberChangedField("ManufacturingOrderCategory", this.orderCategory);
        this.orderCategory = orderCategory;
    }

    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>ManufacturingOrderType</b></p>
     * 
     * @param orderType
     *     Manufacturing Order Type
     */
    public void setOrderType(
        @Nullable
        final String orderType) {
        rememberChangedField("ManufacturingOrderType", this.orderType);
        this.orderType = orderType;
    }

    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>DocumentDate</b></p>
     * 
     * @param date
     *     Date
     */
    public void setDate(
        @Nullable
        final LocalDateTime date) {
        rememberChangedField("DocumentDate", this.date);
        this.date = date;
    }

    @Override
    protected String getEntityCollection() {
        return "A_ProdnOrderItemSerialNumber";
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        result.put("ManufacturingOrder", getManufacturingOrder());
        result.put("ManufacturingOrderItem", getManufacturingOrderItem());
        result.put("SerialNumber", getSerialNumber());
        return result;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("ManufacturingOrder", getManufacturingOrder());
        values.put("ManufacturingOrderItem", getManufacturingOrderItem());
        values.put("SerialNumber", getSerialNumber());
        values.put("SerialNumberProfile", getSerialNumberProfile());
        values.put("Product", getProduct());
        values.put("ProductionPlant", getProductionPlant());
        values.put("ManufacturingOrderCategory", getOrderCategory());
        values.put("ManufacturingOrderType", getOrderType());
        values.put("DocumentDate", getDate());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("ManufacturingOrder")) {
                final Object value = values.remove("ManufacturingOrder");
                if ((value == null)||(!value.equals(getManufacturingOrder()))) {
                    setManufacturingOrder(((String) value));
                }
            }
            if (values.containsKey("ManufacturingOrderItem")) {
                final Object value = values.remove("ManufacturingOrderItem");
                if ((value == null)||(!value.equals(getManufacturingOrderItem()))) {
                    setManufacturingOrderItem(((String) value));
                }
            }
            if (values.containsKey("SerialNumber")) {
                final Object value = values.remove("SerialNumber");
                if ((value == null)||(!value.equals(getSerialNumber()))) {
                    setSerialNumber(((String) value));
                }
            }
            if (values.containsKey("SerialNumberProfile")) {
                final Object value = values.remove("SerialNumberProfile");
                if ((value == null)||(!value.equals(getSerialNumberProfile()))) {
                    setSerialNumberProfile(((String) value));
                }
            }
            if (values.containsKey("Product")) {
                final Object value = values.remove("Product");
                if ((value == null)||(!value.equals(getProduct()))) {
                    setProduct(((String) value));
                }
            }
            if (values.containsKey("ProductionPlant")) {
                final Object value = values.remove("ProductionPlant");
                if ((value == null)||(!value.equals(getProductionPlant()))) {
                    setProductionPlant(((String) value));
                }
            }
            if (values.containsKey("ManufacturingOrderCategory")) {
                final Object value = values.remove("ManufacturingOrderCategory");
                if ((value == null)||(!value.equals(getOrderCategory()))) {
                    setOrderCategory(((String) value));
                }
            }
            if (values.containsKey("ManufacturingOrderType")) {
                final Object value = values.remove("ManufacturingOrderType");
                if ((value == null)||(!value.equals(getOrderType()))) {
                    setOrderType(((String) value));
                }
            }
            if (values.containsKey("DocumentDate")) {
                final Object value = values.remove("DocumentDate");
                if ((value == null)||(!value.equals(getDate()))) {
                    setDate(((LocalDateTime) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param fieldType
     *     The Java type to use for the extension field when performing value comparisons.
     * @return
     *     A representation of an extension field from this entity.
     */
    @Nonnull
    public static<T >ProductionOrderSerialNumbersField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final Class<T> fieldType) {
        return new ProductionOrderSerialNumbersField<T>(fieldName);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param typeConverter
     *     A TypeConverter<T, DomainT> instance whose first generic type matches the Java type of the field
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param <DomainT>
     *     The type of the extension field as returned by the OData service.
     * @return
     *     A representation of an extension field from this entity, holding a reference to the given TypeConverter.
     */
    @Nonnull
    public static<T,DomainT >ProductionOrderSerialNumbersField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final TypeConverter<T, DomainT> typeConverter) {
        return new ProductionOrderSerialNumbersField<T>(fieldName, typeConverter);
    }

    @Override
    @Nullable
    public Destination getDestinationForFetch() {
        return super.getDestinationForFetch();
    }

    @Override
    protected void setServicePathForFetch(
        @Nullable
        final String servicePathForFetch) {
        super.setServicePathForFetch(servicePathForFetch);
    }

    @Override
    public void attachToService(
        @Nullable
        final String servicePath,
        @Nonnull
        final Destination destination) {
        super.attachToService(servicePath, destination);
    }

    @Override
    protected String getDefaultServicePath() {
        return (com.sap.cloud.sdk.tutorial.datamodel.odata.services.APIPRODUCTIONORDER2SRVService.DEFAULT_SERVICE_PATH);
    }

}
