
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv;

import java.util.Map;
import javax.annotation.Nonnull;
import com.google.common.collect.Maps;
import com.sap.cloud.sdk.datamodel.odata.helper.FluentHelperByKey;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.selectable.ProductionResourcesToolsSelectable;


/**
 * Fluent helper to fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionResourcesTools ProductionResourcesTools} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. 
 * 
 */
public class ProductionResourcesToolsByKeyFluentHelper
    extends FluentHelperByKey<ProductionResourcesToolsByKeyFluentHelper, ProductionResourcesTools, ProductionResourcesToolsSelectable>
{

    private final Map<String, Object> key = Maps.newHashMap();

    /**
     * Creates a fluent helper object that will fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionResourcesTools ProductionResourcesTools} entity with the provided key field values. To perform execution, call the {@link #executeRequest executeRequest} method on the fluent helper object.
     * 
     * @param entityCollection
     *     Entity Collection to be used to fetch a single {@code ProductionResourcesTools}
     * @param servicePath
     *     Service path to be used to fetch a single {@code ProductionResourcesTools}
     * @param orderInternalID
     *     Order Internal ID<p>Constraints: Not nullable, Maximum length: 10</p>
     * @param pRTItemCounter
     *     Item Counter for Production Resources/Tools<p>Constraints: Not nullable, Maximum length: 8</p>
     */
    public ProductionResourcesToolsByKeyFluentHelper(
        @Nonnull
        final String servicePath,
        @Nonnull
        final String entityCollection, final String orderInternalID, final String pRTItemCounter) {
        super(servicePath, entityCollection);
        this.key.put("OrderInternalBillOfOperations", orderInternalID);
        this.key.put("MfgOrderOpProdnRsceToolIntID", pRTItemCounter);
    }

    @Override
    @Nonnull
    protected Class<ProductionResourcesTools> getEntityClass() {
        return ProductionResourcesTools.class;
    }

    @Override
    @Nonnull
    protected Map<String, Object> getKey() {
        return key;
    }

}
