
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv;

import java.net.URI;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.google.common.collect.Maps;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.sap.cloud.sdk.cloudplatform.connectivity.Destination;
import com.sap.cloud.sdk.datamodel.odata.helper.SingleValuedFluentHelperFunction;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.client.methods.HttpUriRequest;


/**
 * Fluent helper for the <b>ScheduleProductionOrderOperation</b> OData function import.
 * 
 */
public class ScheduleProductionOrderOperationFluentHelper
    extends SingleValuedFluentHelperFunction<ScheduleProductionOrderOperationFluentHelper, SchedldProdOrdOpMessage, SchedldProdOrdOpMessage>
{

    private final Map<String, Object> values = Maps.newHashMap();

    /**
     * Creates a fluent helper object that will execute the <b>ScheduleProductionOrderOperation</b> OData function import with the provided parameters. To perform execution, call the {@link #executeRequest executeRequest} method on the fluent helper object.
     * 
     * @param schedulingType
     *     Scheduling type<p></p><p>Constraints: Not nullable, Maximum length: 1</p><p>Original parameter name from the Odata EDM: <b>OpSchedulingMode</b></p>
     * @param componentOfTheVersionNumber
     *     Component of the Version Number<p></p><p>Constraints: Not nullable, Maximum length: 4</p><p>Original parameter name from the Odata EDM: <b>OpSchedulingStrategy</b></p>
     * @param executionEndDate
     *     Execution End Date<p></p><p>Constraints: Nullable, Precision: 0</p><p>Original parameter name from the Odata EDM: <b>OpSchedldEndDate</b></p>
     * @param servicePath
     *     Service path to be used to call the functions against.
     * @param orderInternalID
     *     Order Internal ID<p></p><p>Constraints: Not nullable, Maximum length: 10</p><p>Original parameter name from the Odata EDM: <b>OrderInternalBillOfOperations</b></p>
     * @param executionStartTime
     *     Execution Start Time<p></p><p>Constraints: Nullable, Precision: 0</p><p>Original parameter name from the Odata EDM: <b>OpSchedldStartTime</b></p>
     * @param operationInternalID
     *     Operation Internal ID<p></p><p>Constraints: Not nullable, Maximum length: 8</p><p>Original parameter name from the Odata EDM: <b>OrderIntBillOfOperationsItem</b></p>
     * @param executionEndTime
     *     Execution End Time<p></p><p>Constraints: Nullable, Precision: 0</p><p>Original parameter name from the Odata EDM: <b>OpSchedldEndTime</b></p>
     * @param executionStartDate
     *     Execution Start Date<p></p><p>Constraints: Nullable, Precision: 0</p><p>Original parameter name from the Odata EDM: <b>OpSchedldStartDate</b></p>
     * @param order
     *     Order<p></p><p>Constraints: Not nullable, Maximum length: 12</p><p>Original parameter name from the Odata EDM: <b>ManufacturingOrder</b></p>
     * @param status
     *     Status<p></p><p>Constraints: Nullable, Maximum length: 4</p><p>Original parameter name from the Odata EDM: <b>OpSchedulingStatus</b></p>
     */
    public ScheduleProductionOrderOperationFluentHelper(
        @Nonnull
        final String servicePath,
        @Nonnull
        final String order,
        @Nonnull
        final String orderInternalID,
        @Nonnull
        final String operationInternalID,
        @Nullable
        final LocalDateTime executionStartDate,
        @Nullable
        final LocalTime executionStartTime,
        @Nullable
        final LocalDateTime executionEndDate,
        @Nullable
        final LocalTime executionEndTime,
        @Nonnull
        final String schedulingType,
        @Nullable
        final String status,
        @Nonnull
        final String componentOfTheVersionNumber) {
        super(servicePath);
        values.put("ManufacturingOrder", order);
        values.put("OrderInternalBillOfOperations", orderInternalID);
        values.put("OrderIntBillOfOperationsItem", operationInternalID);
        if (executionStartDate!= null) {
            values.put("OpSchedldStartDate", executionStartDate);
        }
        if (executionStartTime!= null) {
            values.put("OpSchedldStartTime", executionStartTime);
        }
        if (executionEndDate!= null) {
            values.put("OpSchedldEndDate", executionEndDate);
        }
        if (executionEndTime!= null) {
            values.put("OpSchedldEndTime", executionEndTime);
        }
        values.put("OpSchedulingMode", schedulingType);
        if (status!= null) {
            values.put("OpSchedulingStatus", status);
        }
        values.put("OpSchedulingStrategy", componentOfTheVersionNumber);
    }

    @Override
    @Nonnull
    protected Class<SchedldProdOrdOpMessage> getEntityClass() {
        return SchedldProdOrdOpMessage.class;
    }

    @Override
    @Nonnull
    protected String getFunctionName() {
        return "ScheduleProductionOrderOperation";
    }

    @Override
    @Nullable
    protected JsonElement refineJsonResponse(
        @Nullable
        JsonElement jsonElement) {
        if ((jsonElement instanceof JsonObject)&&((JsonObject) jsonElement).has(getFunctionName())) {
            jsonElement = ((JsonObject) jsonElement).get(getFunctionName());
        }
        return super.refineJsonResponse(jsonElement);
    }

    @Override
    @Nonnull
    protected Map<String, Object> getParameters() {
        return values;
    }

    @Override
    @Nonnull
    protected HttpUriRequest createRequest(
        @Nonnull
        final URI uri) {
        return new HttpPost(uri);
    }

    /**
     * Execute this function import.
     * 
     */
    @Override
    @Nullable
    public SchedldProdOrdOpMessage executeRequest(
        @Nonnull
        final Destination destination) {
        return super.executeSingle(destination);
    }

}
