
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.selectable;

import com.sap.cloud.sdk.datamodel.odata.helper.EntitySelectable;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder;


/**
 * Interface to enable OData entity selectors for {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder ProductionOrder}. This interface is used by {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.field.ProductionOrderField ProductionOrderField} and {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.link.ProductionOrderLink ProductionOrderLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#PRODUCTION_ORDER PRODUCTION_ORDER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#ORDER_CATEGORY ORDER_CATEGORY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#ORDER_TYPE ORDER_TYPE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#LONG_TEXT LONG_TEXT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#ORDER_IMPORTANCE ORDER_IMPORTANCE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#ORDER_IS_CREATED ORDER_IS_CREATED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#ORDER_IS_RELEASED ORDER_IS_RELEASED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#ORDER_IS_PRINTED ORDER_IS_PRINTED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#ORDER_IS_CONFIRMED ORDER_IS_CONFIRMED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#ORDER_IS_PARTIALLY_CONFIRMED ORDER_IS_PARTIALLY_CONFIRMED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#ORDER_IS_DELIVERED ORDER_IS_DELIVERED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#ORDER_IS_DELETED ORDER_IS_DELETED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#ORDER_IS_PRE_COSTED ORDER_IS_PRE_COSTED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#SETTLEMENT_RULE_IS_CREATED SETTLEMENT_RULE_IS_CREATED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#ORDER_IS_PARTIALLY_RELEASED ORDER_IS_PARTIALLY_RELEASED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#ORDER_IS_LOCKED ORDER_IS_LOCKED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#ORDER_IS_TECHNICALLY_COMPLETED ORDER_IS_TECHNICALLY_COMPLETED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#ORDER_IS_CLOSED ORDER_IS_CLOSED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#ORDER_IS_PARTIALLY_DELIVERED ORDER_IS_PARTIALLY_DELIVERED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#ORDER_IS_MARKED_FOR_DELETION ORDER_IS_MARKED_FOR_DELETION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#SETTLEMENT_RULE_IS_CRTED_MANUALLY SETTLEMENT_RULE_IS_CRTED_MANUALLY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#ORDER_IS_SCHEDULED ORDER_IS_SCHEDULED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#ORDER_HAS_GENERATED_OPERATIONS ORDER_HAS_GENERATED_OPERATIONS}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#ORDER_IS_TO_BE_HANDLED_IN_BATCHES ORDER_IS_TO_BE_HANDLED_IN_BATCHES}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#MATERIAL_AVAILY_IS_NOT_CHECKED MATERIAL_AVAILY_IS_NOT_CHECKED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#ORDER_CREATION_DATE ORDER_CREATION_DATE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#ORDER_CREATION_TIME ORDER_CREATION_TIME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#LAST_CHANGE_DATE_TIME LAST_CHANGE_DATE_TIME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#MATERIAL MATERIAL}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#STORAGE_LOCATION STORAGE_LOCATION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#GOODS_RECIPIENT GOODS_RECIPIENT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#UNLOADING_POINT UNLOADING_POINT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#INVENTORY_USABILITY INVENTORY_USABILITY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#GR_PROCESSING_TIME GR_PROCESSING_TIME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#DISTRIBUTION_KEY DISTRIBUTION_KEY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#STOCK_SEGMENT STOCK_SEGMENT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#ORDER_INTERNAL_ID ORDER_INTERNAL_ID}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#PRODUCTION_PLANT PRODUCTION_PLANT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#PLANNING_PLANT PLANNING_PLANT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#MRP_AREA MRP_AREA}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#MRP_CONTROLLER MRP_CONTROLLER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#PRODUCTION_SUPERVISOR PRODUCTION_SUPERVISOR}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#PRODUCTION_VERSION PRODUCTION_VERSION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#PLANNED_ORDER PLANNED_ORDER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#SALES_ORDER SALES_ORDER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#SALES_ORDER_ITEM SALES_ORDER_ITEM}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#BASIC_SCHEDULING_TYPE BASIC_SCHEDULING_TYPE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#OBJECT_NUMBER OBJECT_NUMBER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#PROD_CONFIGURATION PROD_CONFIGURATION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#SEQUENCE_NUMBER SEQUENCE_NUMBER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#BUSINESS_AREA BUSINESS_AREA}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#COMPANY_CODE COMPANY_CODE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#PROFIT_CENTER PROFIT_CENTER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#ACTUAL_COSTING_VARIANT ACTUAL_COSTING_VARIANT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#PLANNED_COSTING_VARIANT PLANNED_COSTING_VARIANT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#FUNCTIONAL_AREA FUNCTIONAL_AREA}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#PLANNED_START_DATE PLANNED_START_DATE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#PLANNED_START_TIME PLANNED_START_TIME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#PLANNED_END_DATE PLANNED_END_DATE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#PLANNED_END_TIME PLANNED_END_TIME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#SCHEDULED_START_DATE SCHEDULED_START_DATE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#SCHEDULED_START_TIME SCHEDULED_START_TIME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#SCHEDULED_END_DATE SCHEDULED_END_DATE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#SCHEDULED_END_TIME SCHEDULED_END_TIME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#ACTUAL_RELEASE_DATE ACTUAL_RELEASE_DATE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#PRODUCTION_UNIT PRODUCTION_UNIT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#ISO_CODE ISO_CODE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#INTERNAL_SAP_CODE INTERNAL_SAP_CODE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#TOTAL_QUANTITY TOTAL_QUANTITY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#SCRAP_QUANTITY SCRAP_QUANTITY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#CONFIRMED_YIELD CONFIRMED_YIELD}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#NAME_OF_CUSTOMER NAME_OF_CUSTOMER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#WBS_ELEMENT WBS_ELEMENT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#TO_PRODN_ORD_HEADER_SERIAL_NUMBER TO_PRODN_ORD_HEADER_SERIAL_NUMBER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#TO_PRODUCTION_ORDER_COMPONENT TO_PRODUCTION_ORDER_COMPONENT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#TO_PRODUCTION_ORDER_COMPONENT_EXT TO_PRODUCTION_ORDER_COMPONENT_EXT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#TO_PRODUCTION_ORDER_COMPONENT_EXT4 TO_PRODUCTION_ORDER_COMPONENT_EXT4}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#TO_PRODUCTION_ORDER_ITEM TO_PRODUCTION_ORDER_ITEM}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#TO_PRODUCTION_ORDER_OPERATION TO_PRODUCTION_ORDER_OPERATION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#TO_PRODUCTION_ORDER_STATUS TO_PRODUCTION_ORDER_STATUS}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder#TO_PRODUCTION_RSCE_TOOLS TO_PRODUCTION_RSCE_TOOLS}</li>
 * </ul>
 * 
 */
public interface ProductionOrderSelectable
    extends EntitySelectable<ProductionOrder>
{


}
