
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.selectable;

import com.sap.cloud.sdk.datamodel.odata.helper.EntitySelectable;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools;


/**
 * Interface to enable OData entity selectors for {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools ProductionResourcesTools}. This interface is used by {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.field.ProductionResourcesToolsField ProductionResourcesToolsField} and {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.link.ProductionResourcesToolsLink ProductionResourcesToolsLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#ORDER_INTERNAL_ID ORDER_INTERNAL_ID}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#PRT_ITEM_COUNTER PRT_ITEM_COUNTER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#PRODUCTION_RESOURCE_TOOL PRODUCTION_RESOURCE_TOOL}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#PRT_CATEGORY PRT_CATEGORY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#PRT_CATEGORY_NAME PRT_CATEGORY_NAME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#PRT_CONTROL_PROFILE PRT_CONTROL_PROFILE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#PLANT PLANT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#OPERATION_INTERNAL_ID OPERATION_INTERNAL_ID}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#PRODUCTION_ORDER PRODUCTION_ORDER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#OPERATION_OR_PHASE OPERATION_OR_PHASE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#ORDER_CATEGORY ORDER_CATEGORY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#ORDER_TYPE ORDER_TYPE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#PRODUCTION_PLANT PRODUCTION_PLANT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#TASK_LIST_TYPE TASK_LIST_TYPE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#GROUP GROUP}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#EARLIEST_START_DATE EARLIEST_START_DATE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#EARLIEST_START_TIME EARLIEST_START_TIME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#EARLIEST_END_DATE EARLIEST_END_DATE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#EARLIEST_END_TIME EARLIEST_END_TIME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#LATEST_START_DATE LATEST_START_DATE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#LATEST_START_TIME LATEST_START_TIME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#LATEST_END_DATE LATEST_END_DATE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#LATEST_END_TIME LATEST_END_TIME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#ACTUAL_START_DATE ACTUAL_START_DATE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#ACTUAL_START_TIME ACTUAL_START_TIME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#ACTUAL_END_DATE ACTUAL_END_DATE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#ACTUAL_END_TIME ACTUAL_END_TIME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#USAGE_DURATION_UNIT USAGE_DURATION_UNIT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#USAGE_DURATION USAGE_DURATION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#ISO_CODE ISO_CODE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#INTERNAL_SAP_CODE INTERNAL_SAP_CODE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#QUANTITY_FORMULA QUANTITY_FORMULA}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#USAGE_VALUE_FORMULA USAGE_VALUE_FORMULA}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#UNIT_FOR_QUANTITY UNIT_FOR_QUANTITY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#QUANTITY QUANTITY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#ISO_CODE_2 ISO_CODE_2}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#INTERNAL_SAP_CODE_2 INTERNAL_SAP_CODE_2}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#PRT_PLANNED_QUANTITY_UNIT PRT_PLANNED_QUANTITY_UNIT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#PLANNED_QUANTITY PLANNED_QUANTITY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#ISO_CODE_3 ISO_CODE_3}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#INTERNAL_SAP_CODE_3 INTERNAL_SAP_CODE_3}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#PRT_ACTUAL_QUANTITY_UNIT PRT_ACTUAL_QUANTITY_UNIT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#ACTUAL_QUANTITY ACTUAL_QUANTITY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#ISO_CODE_4 ISO_CODE_4}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#INTERNAL_SAP_CODE_4 INTERNAL_SAP_CODE_4}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#USAGE_VALUE_UNIT USAGE_VALUE_UNIT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#STANDARD_USAGE_VALUE STANDARD_USAGE_VALUE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#ISO_CODE_5 ISO_CODE_5}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#INTERNAL_SAP_CODE_5 INTERNAL_SAP_CODE_5}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#PLANNED_USAGE_QUANTITY_UNIT PLANNED_USAGE_QUANTITY_UNIT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#PLANNED_USAGE_VALUE PLANNED_USAGE_VALUE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#ISO_CODE_6 ISO_CODE_6}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#INTERNAL_SAP_CODE_6 INTERNAL_SAP_CODE_6}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#ACTUAL_USAGE_QUANTITY_UNIT ACTUAL_USAGE_QUANTITY_UNIT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#ACTUAL_USAGE_VALUE ACTUAL_USAGE_VALUE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#ISO_CODE_7 ISO_CODE_7}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#INTERNAL_SAP_CODE_7 INTERNAL_SAP_CODE_7}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#BASE_UNIT_OF_MEASURE BASE_UNIT_OF_MEASURE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#ISO_CODE_8 ISO_CODE_8}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionResourcesTools#INTERNAL_SAP_CODE_8 INTERNAL_SAP_CODE_8}</li>
 * </ul>
 * 
 */
public interface ProductionResourcesToolsSelectable
    extends EntitySelectable<ProductionResourcesTools>
{


}
