
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.batch;

import javax.annotation.Nonnull;
import com.sap.cloud.sdk.datamodel.odata.helper.batch.FluentHelperBatchChangeSet;
import com.sap.cloud.sdk.datamodel.odata.helper.batch.FluentHelperBatchEndChangeSet;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrderComponentsExtended;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrderComponentsUsingRAPBO;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrderOperations;


/**
 * This interface enables you to combine multiple operations into one change set. For further information have a look into the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.services.APIPRODUCTIONORDER2SRVService APIPRODUCTIONORDER2SRVService}.
 * 
 */
public interface APIPRODUCTIONORDER2SRVServiceBatchChangeSet
    extends FluentHelperBatchChangeSet<APIPRODUCTIONORDER2SRVServiceBatchChangeSet> , FluentHelperBatchEndChangeSet<APIPRODUCTIONORDER2SRVServiceBatch>
{


    /**
     * Update an existing {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrderComponentsExtended ProductionOrderComponentsExtended} entity and save it to the S/4HANA system.
     * 
     * @param productionOrderComponentsExtended
     *     {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrderComponentsExtended ProductionOrderComponentsExtended} entity object that will be updated in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    APIPRODUCTIONORDER2SRVServiceBatchChangeSet updateProductionOrderComponentsExtended(
        @Nonnull
        final ProductionOrderComponentsExtended productionOrderComponentsExtended);

    /**
     * Update an existing {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrderComponentsUsingRAPBO ProductionOrderComponentsUsingRAPBO} entity and save it to the S/4HANA system.
     * 
     * @param productionOrderComponentsUsingRAPBO
     *     {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrderComponentsUsingRAPBO ProductionOrderComponentsUsingRAPBO} entity object that will be updated in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    APIPRODUCTIONORDER2SRVServiceBatchChangeSet updateProductionOrderComponentsUsingRAPBO(
        @Nonnull
        final ProductionOrderComponentsUsingRAPBO productionOrderComponentsUsingRAPBO);

    /**
     * Deletes an existing {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrderComponentsUsingRAPBO ProductionOrderComponentsUsingRAPBO} entity in the S/4HANA system.
     * 
     * @param productionOrderComponentsUsingRAPBO
     *     {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrderComponentsUsingRAPBO ProductionOrderComponentsUsingRAPBO} entity object that will be deleted in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    APIPRODUCTIONORDER2SRVServiceBatchChangeSet deleteProductionOrderComponentsUsingRAPBO(
        @Nonnull
        final ProductionOrderComponentsUsingRAPBO productionOrderComponentsUsingRAPBO);

    /**
     * Update an existing {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrderOperations ProductionOrderOperations} entity and save it to the S/4HANA system.
     * 
     * @param productionOrderOperations
     *     {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrderOperations ProductionOrderOperations} entity object that will be updated in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    APIPRODUCTIONORDER2SRVServiceBatchChangeSet updateProductionOrderOperations(
        @Nonnull
        final ProductionOrderOperations productionOrderOperations);

    /**
     * Create a new {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder ProductionOrder} entity and save it to the S/4HANA system.
     * 
     * @param productionOrder
     *     {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder ProductionOrder} entity object that will be created in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    APIPRODUCTIONORDER2SRVServiceBatchChangeSet createProductionOrder(
        @Nonnull
        final ProductionOrder productionOrder);

    /**
     * Update an existing {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder ProductionOrder} entity and save it to the S/4HANA system.
     * 
     * @param productionOrder
     *     {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrder ProductionOrder} entity object that will be updated in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    APIPRODUCTIONORDER2SRVServiceBatchChangeSet updateProductionOrder(
        @Nonnull
        final ProductionOrder productionOrder);

}
