
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.batch;

import javax.annotation.Nonnull;
import com.sap.cloud.sdk.datamodel.odata.helper.batch.BatchFluentHelperBasic;


/**
 * Default implementation of the {@link APIPRODUCTIONORDER2SRVServiceBatch} interface exposed in the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.services.APIPRODUCTIONORDER2SRVService APIPRODUCTIONORDER2SRVService}, allowing you to create multiple changesets and finally execute the batch request.
 * 
 */
public class DefaultAPIPRODUCTIONORDER2SRVServiceBatch
    extends BatchFluentHelperBasic<APIPRODUCTIONORDER2SRVServiceBatch, APIPRODUCTIONORDER2SRVServiceBatchChangeSet>
    implements APIPRODUCTIONORDER2SRVServiceBatch
{

    @Nonnull
    private final com.sap.cloud.sdk.tutorial.datamodel.odata.services.APIPRODUCTIONORDER2SRVService service;
    @Nonnull
    private final String servicePath;

    /**
     * Creates a new instance of this DefaultAPIPRODUCTIONORDER2SRVServiceBatch.
     * 
     * @param service
     *     The service to execute all operations in this changeset on.
     */
    public DefaultAPIPRODUCTIONORDER2SRVServiceBatch(
        @Nonnull
        final com.sap.cloud.sdk.tutorial.datamodel.odata.services.APIPRODUCTIONORDER2SRVService service) {
        this(service, com.sap.cloud.sdk.tutorial.datamodel.odata.services.APIPRODUCTIONORDER2SRVService.DEFAULT_SERVICE_PATH);
    }

    /**
     * Creates a new instance of this DefaultAPIPRODUCTIONORDER2SRVServiceBatch.
     * 
     * @param service
     *     The service to execute all operations in this changeset on.
     * @param servicePath
     *     The custom service path to operate on.
     */
    public DefaultAPIPRODUCTIONORDER2SRVServiceBatch(
        @Nonnull
        final com.sap.cloud.sdk.tutorial.datamodel.odata.services.APIPRODUCTIONORDER2SRVService service,
        @Nonnull
        final String servicePath) {
        this.service = service;
        this.servicePath = servicePath;
    }

    @Nonnull
    @Override
    protected String getServicePathForBatchRequest() {
        return servicePath;
    }

    @Nonnull
    @Override
    protected DefaultAPIPRODUCTIONORDER2SRVServiceBatch getThis() {
        return this;
    }

    @Nonnull
    @Override
    public APIPRODUCTIONORDER2SRVServiceBatchChangeSet beginChangeSet() {
        return new DefaultAPIPRODUCTIONORDER2SRVServiceBatchChangeSet(this, service);
    }

}
