
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.services;

import java.time.LocalDateTime;
import java.time.LocalTime;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.sap.cloud.sdk.datamodel.odata.helper.batch.BatchService;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.CloseOrderFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ConvertPlndOrderFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.DeletionFlagOrderFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.DeletionIndOrderFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.DeliveryCompletedOrderFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.DiscardOrderFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.OrderReleasedByMESFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrder;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderByKeyFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsByKeyFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtendedByKeyFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtendedFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtendedUpdateFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBOByKeyFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBODeleteFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBOFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBOUpdateFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderCreateFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderItemsByKeyFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderItemsFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperationsByKeyFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperationsFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperationsUpdateFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderSerialNumbersByKeyFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderSerialNumbersFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderStatusByKeyFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderStatusFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderUpdateFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionResourcesToolsByKeyFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionResourcesToolsFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ReleaseOperationFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ReleaseOrderFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ScheduleProductionOrderOperationFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.TechlyCmpltOrderFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.batch.APIPRODUCTIONORDER2SRVServiceBatch;


/**
 * <h3>Details:</h3><table summary='Details'><tr><td align='right'>OData Service:</td><td>API_PRODUCTION_ORDER_2_SRV</td></tr></table>
 * 
 */
public interface APIPRODUCTIONORDER2SRVService
    extends BatchService<APIPRODUCTIONORDER2SRVServiceBatch>
{

    /**
     * If no other path was provided via the {@link #withServicePath(String)} method, this is the default service path used to access the endpoint.
     * 
     */
    String DEFAULT_SERVICE_PATH = "/sap/opu/odata/sap/API_PRODUCTION_ORDER_2_SRV";

    /**
     * Overrides the default service path and returns a new service instance with the specified service path. Also adjusts the respective entity URLs.
     * 
     * @param servicePath
     *     Service path that will override the default.
     * @return
     *     A new service instance with the specified service path.
     */
    @Nonnull
    APIPRODUCTIONORDER2SRVService withServicePath(
        @Nonnull
        final String servicePath);

    /**
     * Fetch multiple {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderSerialNumbers ProductionOrderSerialNumbers} entities.
     * 
     * @return
     *     A fluent helper to fetch multiple {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderSerialNumbers ProductionOrderSerialNumbers} entities. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderSerialNumbersFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ProductionOrderSerialNumbersFluentHelper getAllProductionOrderSerialNumbers();

    /**
     * Fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderSerialNumbers ProductionOrderSerialNumbers} entity using key fields.
     * 
     * @param serialNumber
     *     Serial Number<p>Constraints: Not nullable, Maximum length: 18</p>
     * @param manufacturingOrderItem
     *     Manufacturing Order Item ID<p>Constraints: Not nullable, Maximum length: 4</p>
     * @param manufacturingOrder
     *     Manufacturing Order ID<p>Constraints: Not nullable, Maximum length: 12</p>
     * @return
     *     A fluent helper to fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderSerialNumbers ProductionOrderSerialNumbers} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderSerialNumbersByKeyFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ProductionOrderSerialNumbersByKeyFluentHelper getProductionOrderSerialNumbersByKey(final String manufacturingOrder, final String manufacturingOrderItem, final String serialNumber);

    /**
     * Fetch multiple {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponents ProductionOrderComponents} entities.
     * 
     * @return
     *     A fluent helper to fetch multiple {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponents ProductionOrderComponents} entities. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ProductionOrderComponentsFluentHelper getAllProductionOrderComponents();

    /**
     * Fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponents ProductionOrderComponents} entity using key fields.
     * 
     * @param reservationItem
     *     Reservation Item<p>Constraints: Not nullable, Maximum length: 4</p>
     * @param reservation
     *     Number of reservation/dependent requirements<p>Constraints: Not nullable, Maximum length: 10</p>
     * @return
     *     A fluent helper to fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponents ProductionOrderComponents} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsByKeyFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ProductionOrderComponentsByKeyFluentHelper getProductionOrderComponentsByKey(final String reservation, final String reservationItem);

    /**
     * Fetch multiple {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended ProductionOrderComponentsExtended} entities.
     * 
     * @return
     *     A fluent helper to fetch multiple {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended ProductionOrderComponentsExtended} entities. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtendedFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ProductionOrderComponentsExtendedFluentHelper getAllProductionOrderComponentsExtended();

    /**
     * Fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended ProductionOrderComponentsExtended} entity using key fields.
     * 
     * @param reservationItem
     *     Reservation Item<p>Constraints: Not nullable, Maximum length: 4</p>
     * @param reservation
     *     Number of reservation/dependent requirements<p>Constraints: Not nullable, Maximum length: 10</p>
     * @param reservationRecordType
     *     Reservation Record Type<p>Constraints: Not nullable, Maximum length: 1</p>
     * @return
     *     A fluent helper to fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended ProductionOrderComponentsExtended} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtendedByKeyFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ProductionOrderComponentsExtendedByKeyFluentHelper getProductionOrderComponentsExtendedByKey(final String reservation, final String reservationItem, final String reservationRecordType);

    /**
     * Update an existing {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended ProductionOrderComponentsExtended} entity and save it to the S/4HANA system.
     * 
     * @param productionOrderComponentsExtended
     *     {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended ProductionOrderComponentsExtended} entity object that will be updated in the S/4HANA system.
     * @return
     *     A fluent helper to update an existing {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended ProductionOrderComponentsExtended} entity. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtendedUpdateFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ProductionOrderComponentsExtendedUpdateFluentHelper updateProductionOrderComponentsExtended(
        @Nonnull
        final ProductionOrderComponentsExtended productionOrderComponentsExtended);

    /**
     * Fetch multiple {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO ProductionOrderComponentsUsingRAPBO} entities.
     * 
     * @return
     *     A fluent helper to fetch multiple {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO ProductionOrderComponentsUsingRAPBO} entities. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBOFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ProductionOrderComponentsUsingRAPBOFluentHelper getAllProductionOrderComponentsUsingRAPBO();

    /**
     * Fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO ProductionOrderComponentsUsingRAPBO} entity using key fields.
     * 
     * @param reservationItem
     *     Reservation Item<p>Constraints: Not nullable, Maximum length: 4</p>
     * @param reservation
     *     Number of reservation/dependent requirements<p>Constraints: Not nullable, Maximum length: 10</p>
     * @param reservationRecordType
     *     Reservation Record Type<p>Constraints: Not nullable, Maximum length: 1</p>
     * @return
     *     A fluent helper to fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO ProductionOrderComponentsUsingRAPBO} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBOByKeyFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ProductionOrderComponentsUsingRAPBOByKeyFluentHelper getProductionOrderComponentsUsingRAPBOByKey(final String reservation, final String reservationItem, final String reservationRecordType);

    /**
     * Update an existing {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO ProductionOrderComponentsUsingRAPBO} entity and save it to the S/4HANA system.
     * 
     * @param productionOrderComponentsUsingRAPBO
     *     {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO ProductionOrderComponentsUsingRAPBO} entity object that will be updated in the S/4HANA system.
     * @return
     *     A fluent helper to update an existing {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO ProductionOrderComponentsUsingRAPBO} entity. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBOUpdateFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ProductionOrderComponentsUsingRAPBOUpdateFluentHelper updateProductionOrderComponentsUsingRAPBO(
        @Nonnull
        final ProductionOrderComponentsUsingRAPBO productionOrderComponentsUsingRAPBO);

    /**
     * Deletes an existing {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO ProductionOrderComponentsUsingRAPBO} entity in the S/4HANA system.
     * 
     * @param productionOrderComponentsUsingRAPBO
     *     {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO ProductionOrderComponentsUsingRAPBO} entity object that will be deleted in the S/4HANA system.
     * @return
     *     A fluent helper to delete an existing {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO ProductionOrderComponentsUsingRAPBO} entity. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBODeleteFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ProductionOrderComponentsUsingRAPBODeleteFluentHelper deleteProductionOrderComponentsUsingRAPBO(
        @Nonnull
        final ProductionOrderComponentsUsingRAPBO productionOrderComponentsUsingRAPBO);

    /**
     * Fetch multiple {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderItems ProductionOrderItems} entities.
     * 
     * @return
     *     A fluent helper to fetch multiple {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderItems ProductionOrderItems} entities. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderItemsFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ProductionOrderItemsFluentHelper getAllProductionOrderItems();

    /**
     * Fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderItems ProductionOrderItems} entity using key fields.
     * 
     * @param manufacturingOrderItem
     *     Manufacturing Order Item ID<p>Constraints: Not nullable, Maximum length: 4</p>
     * @param productionOrder
     *     Production Order<p>Constraints: Not nullable, Maximum length: 12</p>
     * @return
     *     A fluent helper to fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderItems ProductionOrderItems} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderItemsByKeyFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ProductionOrderItemsByKeyFluentHelper getProductionOrderItemsByKey(final String productionOrder, final String manufacturingOrderItem);

    /**
     * Fetch multiple {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations ProductionOrderOperations} entities.
     * 
     * @return
     *     A fluent helper to fetch multiple {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations ProductionOrderOperations} entities. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperationsFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ProductionOrderOperationsFluentHelper getAllProductionOrderOperations();

    /**
     * Fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations ProductionOrderOperations} entity using key fields.
     * 
     * @param orderInternalID
     *     Order Internal ID<p>Constraints: Not nullable, Maximum length: 10</p>
     * @param operationInternalID
     *     Internal Identifier of an Operation or Activity<p>Constraints: Not nullable, Maximum length: 8</p>
     * @return
     *     A fluent helper to fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations ProductionOrderOperations} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperationsByKeyFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ProductionOrderOperationsByKeyFluentHelper getProductionOrderOperationsByKey(final String orderInternalID, final String operationInternalID);

    /**
     * Update an existing {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations ProductionOrderOperations} entity and save it to the S/4HANA system.
     * 
     * @param productionOrderOperations
     *     {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations ProductionOrderOperations} entity object that will be updated in the S/4HANA system.
     * @return
     *     A fluent helper to update an existing {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations ProductionOrderOperations} entity. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperationsUpdateFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ProductionOrderOperationsUpdateFluentHelper updateProductionOrderOperations(
        @Nonnull
        final ProductionOrderOperations productionOrderOperations);

    /**
     * Fetch multiple {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderStatus ProductionOrderStatus} entities.
     * 
     * @return
     *     A fluent helper to fetch multiple {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderStatus ProductionOrderStatus} entities. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderStatusFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ProductionOrderStatusFluentHelper getAllProductionOrderStatus();

    /**
     * Fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderStatus ProductionOrderStatus} entity using key fields.
     * 
     * @param productionOrder
     *     Production Order<p>Constraints: Not nullable, Maximum length: 12</p>
     * @param status
     *     Object status<p>Constraints: Not nullable, Maximum length: 5</p>
     * @return
     *     A fluent helper to fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderStatus ProductionOrderStatus} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderStatusByKeyFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ProductionOrderStatusByKeyFluentHelper getProductionOrderStatusByKey(final String productionOrder, final String status);

    /**
     * Fetch multiple {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrder ProductionOrder} entities.
     * 
     * @return
     *     A fluent helper to fetch multiple {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrder ProductionOrder} entities. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ProductionOrderFluentHelper getAllProductionOrder();

    /**
     * Fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrder ProductionOrder} entity using key fields.
     * 
     * @param productionOrder
     *     Production Order<p>Constraints: Not nullable, Maximum length: 12</p>
     * @return
     *     A fluent helper to fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrder ProductionOrder} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderByKeyFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ProductionOrderByKeyFluentHelper getProductionOrderByKey(final String productionOrder);

    /**
     * Create a new {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrder ProductionOrder} entity and save it to the S/4HANA system.
     * 
     * @param productionOrder
     *     {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrder ProductionOrder} entity object that will be created in the S/4HANA system.
     * @return
     *     A fluent helper to create a new {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrder ProductionOrder} entity. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderCreateFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ProductionOrderCreateFluentHelper createProductionOrder(
        @Nonnull
        final ProductionOrder productionOrder);

    /**
     * Update an existing {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrder ProductionOrder} entity and save it to the S/4HANA system.
     * 
     * @param productionOrder
     *     {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrder ProductionOrder} entity object that will be updated in the S/4HANA system.
     * @return
     *     A fluent helper to update an existing {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrder ProductionOrder} entity. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderUpdateFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ProductionOrderUpdateFluentHelper updateProductionOrder(
        @Nonnull
        final ProductionOrder productionOrder);

    /**
     * Fetch multiple {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionResourcesTools ProductionResourcesTools} entities.
     * 
     * @return
     *     A fluent helper to fetch multiple {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionResourcesTools ProductionResourcesTools} entities. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionResourcesToolsFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ProductionResourcesToolsFluentHelper getAllProductionResourcesTools();

    /**
     * Fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionResourcesTools ProductionResourcesTools} entity using key fields.
     * 
     * @param orderInternalID
     *     Order Internal ID<p>Constraints: Not nullable, Maximum length: 10</p>
     * @param pRTItemCounter
     *     Item Counter for Production Resources/Tools<p>Constraints: Not nullable, Maximum length: 8</p>
     * @return
     *     A fluent helper to fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionResourcesTools ProductionResourcesTools} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionResourcesToolsByKeyFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ProductionResourcesToolsByKeyFluentHelper getProductionResourcesToolsByKey(final String orderInternalID, final String pRTItemCounter);

    /**
     * <p>Creates a fluent helper for the <b>ReleaseOrder</b> OData function import.</p>
     * 
     * @param manufacturingOrder
     *     Constraints: Not nullable, Maximum length: 12<p>Original parameter name from the Odata EDM: <b>ManufacturingOrder</b></p>
     * @return
     *     A fluent helper object that will execute the <b>ReleaseOrder</b> OData function import with the provided parameters. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ReleaseOrderFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    ReleaseOrderFluentHelper releaseOrder(
        @Nonnull
        final String manufacturingOrder);

    /**
     * <p>Creates a fluent helper for the <b>ReleaseOperation</b> OData function import.</p>
     * 
     * @param manufacturingOrderOperation
     *     Constraints: Not nullable, Maximum length: 4<p>Original parameter name from the Odata EDM: <b>ManufacturingOrderOperation</b></p>
     * @param manufacturingOrder
     *     Constraints: Not nullable, Maximum length: 12<p>Original parameter name from the Odata EDM: <b>ManufacturingOrder</b></p>
     * @param manufacturingOrderSequence
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>ManufacturingOrderSequence</b></p>
     * @return
     *     A fluent helper object that will execute the <b>ReleaseOperation</b> OData function import with the provided parameters. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ReleaseOperationFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    ReleaseOperationFluentHelper releaseOperation(
        @Nonnull
        final String manufacturingOrder,
        @Nonnull
        final String manufacturingOrderOperation,
        @Nonnull
        final String manufacturingOrderSequence);

    /**
     * <p>Creates a fluent helper for the <b>TechlyCmpltOrder</b> OData function import.</p>
     * 
     * @param manufacturingOrder
     *     Constraints: Not nullable, Maximum length: 12<p>Original parameter name from the Odata EDM: <b>ManufacturingOrder</b></p>
     * @return
     *     A fluent helper object that will execute the <b>TechlyCmpltOrder</b> OData function import with the provided parameters. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.TechlyCmpltOrderFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    TechlyCmpltOrderFluentHelper techlyCmpltOrder(
        @Nonnull
        final String manufacturingOrder);

    /**
     * <p>Creates a fluent helper for the <b>CloseOrder</b> OData function import.</p>
     * 
     * @param manufacturingOrder
     *     Constraints: Not nullable, Maximum length: 12<p>Original parameter name from the Odata EDM: <b>ManufacturingOrder</b></p>
     * @return
     *     A fluent helper object that will execute the <b>CloseOrder</b> OData function import with the provided parameters. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.CloseOrderFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    CloseOrderFluentHelper closeOrder(
        @Nonnull
        final String manufacturingOrder);

    /**
     * <p>Creates a fluent helper for the <b>DeletionFlagOrder</b> OData function import.</p>
     * 
     * @param manufacturingOrder
     *     Constraints: Not nullable, Maximum length: 12<p>Original parameter name from the Odata EDM: <b>ManufacturingOrder</b></p>
     * @return
     *     A fluent helper object that will execute the <b>DeletionFlagOrder</b> OData function import with the provided parameters. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.DeletionFlagOrderFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    DeletionFlagOrderFluentHelper deletionFlagOrder(
        @Nonnull
        final String manufacturingOrder);

    /**
     * <p>Creates a fluent helper for the <b>DeletionIndOrder</b> OData function import.</p>
     * 
     * @param manufacturingOrder
     *     Constraints: Not nullable, Maximum length: 12<p>Original parameter name from the Odata EDM: <b>ManufacturingOrder</b></p>
     * @return
     *     A fluent helper object that will execute the <b>DeletionIndOrder</b> OData function import with the provided parameters. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.DeletionIndOrderFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    DeletionIndOrderFluentHelper deletionIndOrder(
        @Nonnull
        final String manufacturingOrder);

    /**
     * <p>Creates a fluent helper for the <b>DiscardOrder</b> OData function import.</p>
     * 
     * @param manufacturingOrder
     *     Constraints: Not nullable, Maximum length: 12<p>Original parameter name from the Odata EDM: <b>ManufacturingOrder</b></p>
     * @return
     *     A fluent helper object that will execute the <b>DiscardOrder</b> OData function import with the provided parameters. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.DiscardOrderFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    DiscardOrderFluentHelper discardOrder(
        @Nonnull
        final String manufacturingOrder);

    /**
     * <p>Creates a fluent helper for the <b>ConvertPlndOrder</b> OData function import.</p>
     * 
     * @param plannedOrder
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>PlannedOrder</b></p>
     * @param manufacturingOrderType
     *     Constraints: Nullable<p>Original parameter name from the Odata EDM: <b>ManufacturingOrderType</b></p>
     * @param manufacturingOrder
     *     Constraints: Nullable, Maximum length: 12<p>Original parameter name from the Odata EDM: <b>ManufacturingOrder</b></p>
     * @return
     *     A fluent helper object that will execute the <b>ConvertPlndOrder</b> OData function import with the provided parameters. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ConvertPlndOrderFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    ConvertPlndOrderFluentHelper convertPlndOrder(
        @Nullable
        final String manufacturingOrder,
        @Nonnull
        final String plannedOrder,
        @Nullable
        final String manufacturingOrderType);

    /**
     * <p>Creates a fluent helper for the <b>ScheduleProductionOrderOperation</b> OData function import.</p>
     * 
     * @param schedulingType
     *     Scheduling type<p></p><p>Constraints: Not nullable, Maximum length: 1</p><p>Original parameter name from the Odata EDM: <b>OpSchedulingMode</b></p>
     * @param componentOfTheVersionNumber
     *     Component of the Version Number<p></p><p>Constraints: Not nullable, Maximum length: 4</p><p>Original parameter name from the Odata EDM: <b>OpSchedulingStrategy</b></p>
     * @param executionEndDate
     *     Execution End Date<p></p><p>Constraints: Nullable, Precision: 0</p><p>Original parameter name from the Odata EDM: <b>OpSchedldEndDate</b></p>
     * @param orderInternalID
     *     Order Internal ID<p></p><p>Constraints: Not nullable, Maximum length: 10</p><p>Original parameter name from the Odata EDM: <b>OrderInternalBillOfOperations</b></p>
     * @param executionStartTime
     *     Execution Start Time<p></p><p>Constraints: Nullable, Precision: 0</p><p>Original parameter name from the Odata EDM: <b>OpSchedldStartTime</b></p>
     * @param operationInternalID
     *     Operation Internal ID<p></p><p>Constraints: Not nullable, Maximum length: 8</p><p>Original parameter name from the Odata EDM: <b>OrderIntBillOfOperationsItem</b></p>
     * @param executionEndTime
     *     Execution End Time<p></p><p>Constraints: Nullable, Precision: 0</p><p>Original parameter name from the Odata EDM: <b>OpSchedldEndTime</b></p>
     * @param executionStartDate
     *     Execution Start Date<p></p><p>Constraints: Nullable, Precision: 0</p><p>Original parameter name from the Odata EDM: <b>OpSchedldStartDate</b></p>
     * @param order
     *     Order<p></p><p>Constraints: Not nullable, Maximum length: 12</p><p>Original parameter name from the Odata EDM: <b>ManufacturingOrder</b></p>
     * @param status
     *     Status<p></p><p>Constraints: Nullable, Maximum length: 4</p><p>Original parameter name from the Odata EDM: <b>OpSchedulingStatus</b></p>
     * @return
     *     A fluent helper object that will execute the <b>ScheduleProductionOrderOperation</b> OData function import with the provided parameters. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ScheduleProductionOrderOperationFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    ScheduleProductionOrderOperationFluentHelper scheduleProductionOrderOperation(
        @Nonnull
        final String order,
        @Nonnull
        final String orderInternalID,
        @Nonnull
        final String operationInternalID,
        @Nullable
        final LocalDateTime executionStartDate,
        @Nullable
        final LocalTime executionStartTime,
        @Nullable
        final LocalDateTime executionEndDate,
        @Nullable
        final LocalTime executionEndTime,
        @Nonnull
        final String schedulingType,
        @Nullable
        final String status,
        @Nonnull
        final String componentOfTheVersionNumber);

    /**
     * <p>Creates a fluent helper for the <b>DeliveryCompletedOrder</b> OData function import.</p>
     * 
     * @param manufacturingOrder
     *     Constraints: Not nullable, Maximum length: 12<p>Original parameter name from the Odata EDM: <b>ManufacturingOrder</b></p>
     * @return
     *     A fluent helper object that will execute the <b>DeliveryCompletedOrder</b> OData function import with the provided parameters. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.DeliveryCompletedOrderFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    DeliveryCompletedOrderFluentHelper deliveryCompletedOrder(
        @Nonnull
        final String manufacturingOrder);

    /**
     * <p>Creates a fluent helper for the <b>OrderReleasedByMES</b> OData function import.</p>
     * 
     * @param manufacturingOrder
     *     Constraints: Not nullable, Maximum length: 12<p>Original parameter name from the Odata EDM: <b>ManufacturingOrder</b></p>
     * @return
     *     A fluent helper object that will execute the <b>OrderReleasedByMES</b> OData function import with the provided parameters. To perform execution, call the {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.OrderReleasedByMESFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    OrderReleasedByMESFluentHelper orderReleasedByMES(
        @Nonnull
        final String manufacturingOrder);

}
