
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.services;

import java.time.LocalDateTime;
import java.time.LocalTime;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.CloseOrderFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ConvertPlndOrderFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.DeletionFlagOrderFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.DeletionIndOrderFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.DeliveryCompletedOrderFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.DiscardOrderFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.OrderReleasedByMESFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrder;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderByKeyFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsByKeyFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtendedByKeyFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtendedFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtendedUpdateFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBOByKeyFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBODeleteFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBOFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBOUpdateFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderCreateFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderItemsByKeyFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderItemsFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperationsByKeyFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperationsFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperationsUpdateFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderSerialNumbersByKeyFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderSerialNumbersFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderStatusByKeyFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderStatusFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderUpdateFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionResourcesToolsByKeyFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionResourcesToolsFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ReleaseOperationFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ReleaseOrderFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ScheduleProductionOrderOperationFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.TechlyCmpltOrderFluentHelper;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.batch.DefaultAPIPRODUCTIONORDER2SRVServiceBatch;


/**
 * <h3>Details:</h3><table summary='Details'><tr><td align='right'>OData Service:</td><td>API_PRODUCTION_ORDER_2_SRV</td></tr></table>
 * 
 */
public class DefaultAPIPRODUCTIONORDER2SRVService
    implements APIPRODUCTIONORDER2SRVService
{

    @Nonnull
    private final String servicePath;

    /**
     * Creates a service using {@link APIPRODUCTIONORDER2SRVService#DEFAULT_SERVICE_PATH} to send the requests.
     * 
     */
    public DefaultAPIPRODUCTIONORDER2SRVService() {
        servicePath = APIPRODUCTIONORDER2SRVService.DEFAULT_SERVICE_PATH;
    }

    /**
     * Creates a service using the provided service path to send the requests.
     * <p>
     * Used by the fluent {@link #withServicePath(String)} method.
     * 
     */
    private DefaultAPIPRODUCTIONORDER2SRVService(
        @Nonnull
        final String servicePath) {
        this.servicePath = servicePath;
    }

    @Override
    @Nonnull
    public DefaultAPIPRODUCTIONORDER2SRVService withServicePath(
        @Nonnull
        final String servicePath) {
        return new DefaultAPIPRODUCTIONORDER2SRVService(servicePath);
    }

    @Override
    @Nonnull
    public DefaultAPIPRODUCTIONORDER2SRVServiceBatch batch() {
        return new DefaultAPIPRODUCTIONORDER2SRVServiceBatch(this, servicePath);
    }

    @Override
    @Nonnull
    public ProductionOrderSerialNumbersFluentHelper getAllProductionOrderSerialNumbers() {
        return new ProductionOrderSerialNumbersFluentHelper(servicePath, "A_ProdnOrderItemSerialNumber");
    }

    @Override
    @Nonnull
    public ProductionOrderSerialNumbersByKeyFluentHelper getProductionOrderSerialNumbersByKey(final String manufacturingOrder, final String manufacturingOrderItem, final String serialNumber) {
        return new ProductionOrderSerialNumbersByKeyFluentHelper(servicePath, "A_ProdnOrderItemSerialNumber", manufacturingOrder, manufacturingOrderItem, serialNumber);
    }

    @Override
    @Nonnull
    public ProductionOrderComponentsFluentHelper getAllProductionOrderComponents() {
        return new ProductionOrderComponentsFluentHelper(servicePath, "A_ProductionOrderComponent_2");
    }

    @Override
    @Nonnull
    public ProductionOrderComponentsByKeyFluentHelper getProductionOrderComponentsByKey(final String reservation, final String reservationItem) {
        return new ProductionOrderComponentsByKeyFluentHelper(servicePath, "A_ProductionOrderComponent_2", reservation, reservationItem);
    }

    @Override
    @Nonnull
    public ProductionOrderComponentsExtendedFluentHelper getAllProductionOrderComponentsExtended() {
        return new ProductionOrderComponentsExtendedFluentHelper(servicePath, "A_ProductionOrderComponent_3");
    }

    @Override
    @Nonnull
    public ProductionOrderComponentsExtendedByKeyFluentHelper getProductionOrderComponentsExtendedByKey(final String reservation, final String reservationItem, final String reservationRecordType) {
        return new ProductionOrderComponentsExtendedByKeyFluentHelper(servicePath, "A_ProductionOrderComponent_3", reservation, reservationItem, reservationRecordType);
    }

    @Override
    @Nonnull
    public ProductionOrderComponentsExtendedUpdateFluentHelper updateProductionOrderComponentsExtended(
        @Nonnull
        final ProductionOrderComponentsExtended productionOrderComponentsExtended) {
        return new ProductionOrderComponentsExtendedUpdateFluentHelper(servicePath, productionOrderComponentsExtended, "A_ProductionOrderComponent_3");
    }

    @Override
    @Nonnull
    public ProductionOrderComponentsUsingRAPBOFluentHelper getAllProductionOrderComponentsUsingRAPBO() {
        return new ProductionOrderComponentsUsingRAPBOFluentHelper(servicePath, "A_ProductionOrderComponent_4");
    }

    @Override
    @Nonnull
    public ProductionOrderComponentsUsingRAPBOByKeyFluentHelper getProductionOrderComponentsUsingRAPBOByKey(final String reservation, final String reservationItem, final String reservationRecordType) {
        return new ProductionOrderComponentsUsingRAPBOByKeyFluentHelper(servicePath, "A_ProductionOrderComponent_4", reservation, reservationItem, reservationRecordType);
    }

    @Override
    @Nonnull
    public ProductionOrderComponentsUsingRAPBOUpdateFluentHelper updateProductionOrderComponentsUsingRAPBO(
        @Nonnull
        final ProductionOrderComponentsUsingRAPBO productionOrderComponentsUsingRAPBO) {
        return new ProductionOrderComponentsUsingRAPBOUpdateFluentHelper(servicePath, productionOrderComponentsUsingRAPBO, "A_ProductionOrderComponent_4");
    }

    @Override
    @Nonnull
    public ProductionOrderComponentsUsingRAPBODeleteFluentHelper deleteProductionOrderComponentsUsingRAPBO(
        @Nonnull
        final ProductionOrderComponentsUsingRAPBO productionOrderComponentsUsingRAPBO) {
        return new ProductionOrderComponentsUsingRAPBODeleteFluentHelper(servicePath, productionOrderComponentsUsingRAPBO, "A_ProductionOrderComponent_4");
    }

    @Override
    @Nonnull
    public ProductionOrderItemsFluentHelper getAllProductionOrderItems() {
        return new ProductionOrderItemsFluentHelper(servicePath, "A_ProductionOrderItem_2");
    }

    @Override
    @Nonnull
    public ProductionOrderItemsByKeyFluentHelper getProductionOrderItemsByKey(final String productionOrder, final String manufacturingOrderItem) {
        return new ProductionOrderItemsByKeyFluentHelper(servicePath, "A_ProductionOrderItem_2", productionOrder, manufacturingOrderItem);
    }

    @Override
    @Nonnull
    public ProductionOrderOperationsFluentHelper getAllProductionOrderOperations() {
        return new ProductionOrderOperationsFluentHelper(servicePath, "A_ProductionOrderOperation_2");
    }

    @Override
    @Nonnull
    public ProductionOrderOperationsByKeyFluentHelper getProductionOrderOperationsByKey(final String orderInternalID, final String operationInternalID) {
        return new ProductionOrderOperationsByKeyFluentHelper(servicePath, "A_ProductionOrderOperation_2", orderInternalID, operationInternalID);
    }

    @Override
    @Nonnull
    public ProductionOrderOperationsUpdateFluentHelper updateProductionOrderOperations(
        @Nonnull
        final ProductionOrderOperations productionOrderOperations) {
        return new ProductionOrderOperationsUpdateFluentHelper(servicePath, productionOrderOperations, "A_ProductionOrderOperation_2");
    }

    @Override
    @Nonnull
    public ProductionOrderStatusFluentHelper getAllProductionOrderStatus() {
        return new ProductionOrderStatusFluentHelper(servicePath, "A_ProductionOrderStatus_2");
    }

    @Override
    @Nonnull
    public ProductionOrderStatusByKeyFluentHelper getProductionOrderStatusByKey(final String productionOrder, final String status) {
        return new ProductionOrderStatusByKeyFluentHelper(servicePath, "A_ProductionOrderStatus_2", productionOrder, status);
    }

    @Override
    @Nonnull
    public ProductionOrderFluentHelper getAllProductionOrder() {
        return new ProductionOrderFluentHelper(servicePath, "A_ProductionOrder_2");
    }

    @Override
    @Nonnull
    public ProductionOrderByKeyFluentHelper getProductionOrderByKey(final String productionOrder) {
        return new ProductionOrderByKeyFluentHelper(servicePath, "A_ProductionOrder_2", productionOrder);
    }

    @Override
    @Nonnull
    public ProductionOrderCreateFluentHelper createProductionOrder(
        @Nonnull
        final ProductionOrder productionOrder) {
        return new ProductionOrderCreateFluentHelper(servicePath, productionOrder, "A_ProductionOrder_2");
    }

    @Override
    @Nonnull
    public ProductionOrderUpdateFluentHelper updateProductionOrder(
        @Nonnull
        final ProductionOrder productionOrder) {
        return new ProductionOrderUpdateFluentHelper(servicePath, productionOrder, "A_ProductionOrder_2");
    }

    @Override
    @Nonnull
    public ProductionResourcesToolsFluentHelper getAllProductionResourcesTools() {
        return new ProductionResourcesToolsFluentHelper(servicePath, "A_ProductionRsceTools_2");
    }

    @Override
    @Nonnull
    public ProductionResourcesToolsByKeyFluentHelper getProductionResourcesToolsByKey(final String orderInternalID, final String pRTItemCounter) {
        return new ProductionResourcesToolsByKeyFluentHelper(servicePath, "A_ProductionRsceTools_2", orderInternalID, pRTItemCounter);
    }

    @Override
    @Nonnull
    public ReleaseOrderFluentHelper releaseOrder(
        @Nonnull
        final String manufacturingOrder) {
        return new ReleaseOrderFluentHelper(servicePath, manufacturingOrder);
    }

    @Override
    @Nonnull
    public ReleaseOperationFluentHelper releaseOperation(
        @Nonnull
        final String manufacturingOrder,
        @Nonnull
        final String manufacturingOrderOperation,
        @Nonnull
        final String manufacturingOrderSequence) {
        return new ReleaseOperationFluentHelper(servicePath, manufacturingOrder, manufacturingOrderOperation, manufacturingOrderSequence);
    }

    @Override
    @Nonnull
    public TechlyCmpltOrderFluentHelper techlyCmpltOrder(
        @Nonnull
        final String manufacturingOrder) {
        return new TechlyCmpltOrderFluentHelper(servicePath, manufacturingOrder);
    }

    @Override
    @Nonnull
    public CloseOrderFluentHelper closeOrder(
        @Nonnull
        final String manufacturingOrder) {
        return new CloseOrderFluentHelper(servicePath, manufacturingOrder);
    }

    @Override
    @Nonnull
    public DeletionFlagOrderFluentHelper deletionFlagOrder(
        @Nonnull
        final String manufacturingOrder) {
        return new DeletionFlagOrderFluentHelper(servicePath, manufacturingOrder);
    }

    @Override
    @Nonnull
    public DeletionIndOrderFluentHelper deletionIndOrder(
        @Nonnull
        final String manufacturingOrder) {
        return new DeletionIndOrderFluentHelper(servicePath, manufacturingOrder);
    }

    @Override
    @Nonnull
    public DiscardOrderFluentHelper discardOrder(
        @Nonnull
        final String manufacturingOrder) {
        return new DiscardOrderFluentHelper(servicePath, manufacturingOrder);
    }

    @Override
    @Nonnull
    public ConvertPlndOrderFluentHelper convertPlndOrder(
        @Nullable
        final String manufacturingOrder,
        @Nonnull
        final String plannedOrder,
        @Nullable
        final String manufacturingOrderType) {
        return new ConvertPlndOrderFluentHelper(servicePath, manufacturingOrder, plannedOrder, manufacturingOrderType);
    }

    @Override
    @Nonnull
    public ScheduleProductionOrderOperationFluentHelper scheduleProductionOrderOperation(
        @Nonnull
        final String order,
        @Nonnull
        final String orderInternalID,
        @Nonnull
        final String operationInternalID,
        @Nullable
        final LocalDateTime executionStartDate,
        @Nullable
        final LocalTime executionStartTime,
        @Nullable
        final LocalDateTime executionEndDate,
        @Nullable
        final LocalTime executionEndTime,
        @Nonnull
        final String schedulingType,
        @Nullable
        final String status,
        @Nonnull
        final String componentOfTheVersionNumber) {
        return new ScheduleProductionOrderOperationFluentHelper(servicePath, order, orderInternalID, operationInternalID, executionStartDate, executionStartTime, executionEndDate, executionEndTime, schedulingType, status, componentOfTheVersionNumber);
    }

    @Override
    @Nonnull
    public DeliveryCompletedOrderFluentHelper deliveryCompletedOrder(
        @Nonnull
        final String manufacturingOrder) {
        return new DeliveryCompletedOrderFluentHelper(servicePath, manufacturingOrder);
    }

    @Override
    @Nonnull
    public OrderReleasedByMESFluentHelper orderReleasedByMES(
        @Nonnull
        final String manufacturingOrder) {
        return new OrderReleasedByMESFluentHelper(servicePath, manufacturingOrder);
    }

}
