
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv;

import java.net.URI;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.google.common.collect.Maps;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.sap.cloud.sdk.cloudplatform.connectivity.Destination;
import com.sap.cloud.sdk.datamodel.odata.helper.SingleValuedFluentHelperFunction;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.client.methods.HttpUriRequest;


/**
 * Fluent helper for the <b>ConvertPlndOrder</b> OData function import.
 * 
 */
public class ConvertPlndOrderFluentHelper
    extends SingleValuedFluentHelperFunction<ConvertPlndOrderFluentHelper, ProductionOrder, ProductionOrder>
{

    private final Map<String, Object> values = Maps.newHashMap();

    /**
     * Creates a fluent helper object that will execute the <b>ConvertPlndOrder</b> OData function import with the provided parameters. To perform execution, call the {@link #executeRequest executeRequest} method on the fluent helper object.
     * 
     * @param plannedOrder
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>PlannedOrder</b></p>
     * @param manufacturingOrderType
     *     Constraints: Nullable<p>Original parameter name from the Odata EDM: <b>ManufacturingOrderType</b></p>
     * @param servicePath
     *     Service path to be used to call the functions against.
     * @param manufacturingOrder
     *     Constraints: Nullable, Maximum length: 12<p>Original parameter name from the Odata EDM: <b>ManufacturingOrder</b></p>
     */
    public ConvertPlndOrderFluentHelper(
        @Nonnull
        final String servicePath,
        @Nullable
        final String manufacturingOrder,
        @Nonnull
        final String plannedOrder,
        @Nullable
        final String manufacturingOrderType) {
        super(servicePath);
        if (manufacturingOrder!= null) {
            values.put("ManufacturingOrder", manufacturingOrder);
        }
        values.put("PlannedOrder", plannedOrder);
        if (manufacturingOrderType!= null) {
            values.put("ManufacturingOrderType", manufacturingOrderType);
        }
    }

    @Override
    @Nonnull
    protected Class<ProductionOrder> getEntityClass() {
        return ProductionOrder.class;
    }

    @Override
    @Nonnull
    protected String getFunctionName() {
        return "ConvertPlndOrder";
    }

    @Override
    @Nullable
    protected JsonElement refineJsonResponse(
        @Nullable
        JsonElement jsonElement) {
        if ((jsonElement instanceof JsonObject)&&((JsonObject) jsonElement).has(getFunctionName())) {
            jsonElement = ((JsonObject) jsonElement).get(getFunctionName());
        }
        return super.refineJsonResponse(jsonElement);
    }

    @Override
    @Nonnull
    protected Map<String, Object> getParameters() {
        return values;
    }

    @Override
    @Nonnull
    protected HttpUriRequest createRequest(
        @Nonnull
        final URI uri) {
        return new HttpPost(uri);
    }

    /**
     * Execute this function import.
     * 
     */
    @Override
    @Nullable
    public ProductionOrder executeRequest(
        @Nonnull
        final Destination destination) {
        return super.executeSingle(destination);
    }

}
