
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv;

import java.util.Map;
import javax.annotation.Nonnull;
import com.google.common.collect.Maps;
import com.sap.cloud.sdk.datamodel.odata.helper.FluentHelperByKey;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.selectable.ProductionOrderSerialNumbersSelectable;


/**
 * Fluent helper to fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrderSerialNumbers ProductionOrderSerialNumbers} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. 
 * 
 */
public class ProductionOrderSerialNumbersByKeyFluentHelper
    extends FluentHelperByKey<ProductionOrderSerialNumbersByKeyFluentHelper, ProductionOrderSerialNumbers, ProductionOrderSerialNumbersSelectable>
{

    private final Map<String, Object> key = Maps.newHashMap();

    /**
     * Creates a fluent helper object that will fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrderSerialNumbers ProductionOrderSerialNumbers} entity with the provided key field values. To perform execution, call the {@link #executeRequest executeRequest} method on the fluent helper object.
     * 
     * @param entityCollection
     *     Entity Collection to be used to fetch a single {@code ProductionOrderSerialNumbers}
     * @param serialNumber
     *     Serial Number<p>Constraints: Not nullable, Maximum length: 18</p>
     * @param servicePath
     *     Service path to be used to fetch a single {@code ProductionOrderSerialNumbers}
     * @param manufacturingOrderItem
     *     Manufacturing Order Item ID<p>Constraints: Not nullable, Maximum length: 4</p>
     * @param manufacturingOrder
     *     Manufacturing Order ID<p>Constraints: Not nullable, Maximum length: 12</p>
     */
    public ProductionOrderSerialNumbersByKeyFluentHelper(
        @Nonnull
        final String servicePath,
        @Nonnull
        final String entityCollection, final String manufacturingOrder, final String manufacturingOrderItem, final String serialNumber) {
        super(servicePath, entityCollection);
        this.key.put("ManufacturingOrder", manufacturingOrder);
        this.key.put("ManufacturingOrderItem", manufacturingOrderItem);
        this.key.put("SerialNumber", serialNumber);
    }

    @Override
    @Nonnull
    protected Class<ProductionOrderSerialNumbers> getEntityClass() {
        return ProductionOrderSerialNumbers.class;
    }

    @Override
    @Nonnull
    protected Map<String, Object> getKey() {
        return key;
    }

}
