
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv;

import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.cloudplatform.connectivity.Destination;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmEntity;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import com.sap.cloud.sdk.s4hana.datamodel.odata.annotation.Key;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.field.ProductionOrderStatusField;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.selectable.ProductionOrderStatusSelectable;
import com.sap.cloud.sdk.typeconverter.TypeConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * Production Order Status<p></p><p>Original entity name from the Odata EDM: <b>A_ProductionOrderStatus_2Type</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class ProductionOrderStatus
    extends VdmEntity<ProductionOrderStatus>
{

    /**
     * Selector for all available fields of ProductionOrderStatus.
     * 
     */
    public final static ProductionOrderStatusSelectable ALL_FIELDS = () -> "*";
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>ManufacturingOrder</b></p>
     * 
     * @return
     *     Production Order
     */
    @Key
    @SerializedName("ManufacturingOrder")
    @JsonProperty("ManufacturingOrder")
    @Nullable
    @ODataField(odataName = "ManufacturingOrder")
    private String productionOrder;
    /**
     * Use with available fluent helpers to apply the <b>ManufacturingOrder</b> field to query operations.
     * 
     */
    public final static ProductionOrderStatusField<String> PRODUCTION_ORDER = new ProductionOrderStatusField<String>("ManufacturingOrder");
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 5 <p>Original property name from the Odata EDM: <b>StatusCode</b></p>
     * 
     * @return
     *     Object status
     */
    @Key
    @SerializedName("StatusCode")
    @JsonProperty("StatusCode")
    @Nullable
    @ODataField(odataName = "StatusCode")
    private String status;
    /**
     * Use with available fluent helpers to apply the <b>StatusCode</b> field to query operations.
     * 
     */
    public final static ProductionOrderStatusField<String> STATUS = new ProductionOrderStatusField<String>("StatusCode");
    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>IsUserStatus</b></p>
     * 
     * @return
     *     Is User Status
     */
    @SerializedName("IsUserStatus")
    @JsonProperty("IsUserStatus")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "IsUserStatus")
    private Boolean isUserStatus;
    /**
     * Use with available fluent helpers to apply the <b>IsUserStatus</b> field to query operations.
     * 
     */
    public final static ProductionOrderStatusField<Boolean> IS_USER_STATUS = new ProductionOrderStatusField<Boolean>("IsUserStatus");
    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>StatusShortName</b></p>
     * 
     * @return
     *     Individual status of an object (short form)
     */
    @SerializedName("StatusShortName")
    @JsonProperty("StatusShortName")
    @Nullable
    @ODataField(odataName = "StatusShortName")
    private String status_2;
    /**
     * Use with available fluent helpers to apply the <b>StatusShortName</b> field to query operations.
     * 
     */
    public final static ProductionOrderStatusField<String> STATUS_2 = new ProductionOrderStatusField<String>("StatusShortName");
    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>StatusName</b></p>
     * 
     * @return
     *     Individual Status of an Object
     */
    @SerializedName("StatusName")
    @JsonProperty("StatusName")
    @Nullable
    @ODataField(odataName = "StatusName")
    private String status_3;
    /**
     * Use with available fluent helpers to apply the <b>StatusName</b> field to query operations.
     * 
     */
    public final static ProductionOrderStatusField<String> STATUS_3 = new ProductionOrderStatusField<String>("StatusName");

    @Nonnull
    @Override
    public Class<ProductionOrderStatus> getType() {
        return ProductionOrderStatus.class;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>ManufacturingOrder</b></p>
     * 
     * @param productionOrder
     *     Production Order
     */
    public void setProductionOrder(
        @Nullable
        final String productionOrder) {
        rememberChangedField("ManufacturingOrder", this.productionOrder);
        this.productionOrder = productionOrder;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 5 <p>Original property name from the Odata EDM: <b>StatusCode</b></p>
     * 
     * @param status
     *     Object status
     */
    public void setStatus(
        @Nullable
        final String status) {
        rememberChangedField("StatusCode", this.status);
        this.status = status;
    }

    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>IsUserStatus</b></p>
     * 
     * @param isUserStatus
     *     Is User Status
     */
    public void setIsUserStatus(
        @Nullable
        final Boolean isUserStatus) {
        rememberChangedField("IsUserStatus", this.isUserStatus);
        this.isUserStatus = isUserStatus;
    }

    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>StatusShortName</b></p>
     * 
     * @param status_2
     *     Individual status of an object (short form)
     */
    public void setStatus_2(
        @Nullable
        final String status_2) {
        rememberChangedField("StatusShortName", this.status_2);
        this.status_2 = status_2;
    }

    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>StatusName</b></p>
     * 
     * @param status_3
     *     Individual Status of an Object
     */
    public void setStatus_3(
        @Nullable
        final String status_3) {
        rememberChangedField("StatusName", this.status_3);
        this.status_3 = status_3;
    }

    @Override
    protected String getEntityCollection() {
        return "A_ProductionOrderStatus_2";
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        result.put("ManufacturingOrder", getProductionOrder());
        result.put("StatusCode", getStatus());
        return result;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("ManufacturingOrder", getProductionOrder());
        values.put("StatusCode", getStatus());
        values.put("IsUserStatus", getIsUserStatus());
        values.put("StatusShortName", getStatus_2());
        values.put("StatusName", getStatus_3());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("ManufacturingOrder")) {
                final Object value = values.remove("ManufacturingOrder");
                if ((value == null)||(!value.equals(getProductionOrder()))) {
                    setProductionOrder(((String) value));
                }
            }
            if (values.containsKey("StatusCode")) {
                final Object value = values.remove("StatusCode");
                if ((value == null)||(!value.equals(getStatus()))) {
                    setStatus(((String) value));
                }
            }
            if (values.containsKey("IsUserStatus")) {
                final Object value = values.remove("IsUserStatus");
                if ((value == null)||(!value.equals(getIsUserStatus()))) {
                    setIsUserStatus(((Boolean) value));
                }
            }
            if (values.containsKey("StatusShortName")) {
                final Object value = values.remove("StatusShortName");
                if ((value == null)||(!value.equals(getStatus_2()))) {
                    setStatus_2(((String) value));
                }
            }
            if (values.containsKey("StatusName")) {
                final Object value = values.remove("StatusName");
                if ((value == null)||(!value.equals(getStatus_3()))) {
                    setStatus_3(((String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param fieldType
     *     The Java type to use for the extension field when performing value comparisons.
     * @return
     *     A representation of an extension field from this entity.
     */
    @Nonnull
    public static<T >ProductionOrderStatusField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final Class<T> fieldType) {
        return new ProductionOrderStatusField<T>(fieldName);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param typeConverter
     *     A TypeConverter<T, DomainT> instance whose first generic type matches the Java type of the field
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param <DomainT>
     *     The type of the extension field as returned by the OData service.
     * @return
     *     A representation of an extension field from this entity, holding a reference to the given TypeConverter.
     */
    @Nonnull
    public static<T,DomainT >ProductionOrderStatusField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final TypeConverter<T, DomainT> typeConverter) {
        return new ProductionOrderStatusField<T>(fieldName, typeConverter);
    }

    @Override
    @Nullable
    public Destination getDestinationForFetch() {
        return super.getDestinationForFetch();
    }

    @Override
    protected void setServicePathForFetch(
        @Nullable
        final String servicePathForFetch) {
        super.setServicePathForFetch(servicePathForFetch);
    }

    @Override
    public void attachToService(
        @Nullable
        final String servicePath,
        @Nonnull
        final Destination destination) {
        super.attachToService(servicePath, destination);
    }

    @Override
    protected String getDefaultServicePath() {
        return (com.sap.cloud.sdk.tutorial.datamodel.odata.services.APIPRODUCTIONORDER2SRVService.DEFAULT_SERVICE_PATH);
    }

}
