
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv;

import java.util.Map;
import javax.annotation.Nonnull;
import com.google.common.collect.Maps;
import com.sap.cloud.sdk.datamodel.odata.helper.FluentHelperByKey;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.selectable.ProductionOrderComponentsSelectable;


/**
 * Fluent helper to fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrderComponents ProductionOrderComponents} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. 
 * 
 */
public class ProductionOrderComponentsByKeyFluentHelper
    extends FluentHelperByKey<ProductionOrderComponentsByKeyFluentHelper, ProductionOrderComponents, ProductionOrderComponentsSelectable>
{

    private final Map<String, Object> key = Maps.newHashMap();

    /**
     * Creates a fluent helper object that will fetch a single {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.ProductionOrderComponents ProductionOrderComponents} entity with the provided key field values. To perform execution, call the {@link #executeRequest executeRequest} method on the fluent helper object.
     * 
     * @param entityCollection
     *     Entity Collection to be used to fetch a single {@code ProductionOrderComponents}
     * @param reservationItem
     *     Reservation Item<p>Constraints: Not nullable, Maximum length: 4</p>
     * @param servicePath
     *     Service path to be used to fetch a single {@code ProductionOrderComponents}
     * @param reservation
     *     Number of reservation/dependent requirements<p>Constraints: Not nullable, Maximum length: 10</p>
     */
    public ProductionOrderComponentsByKeyFluentHelper(
        @Nonnull
        final String servicePath,
        @Nonnull
        final String entityCollection, final String reservation, final String reservationItem) {
        super(servicePath, entityCollection);
        this.key.put("Reservation", reservation);
        this.key.put("ReservationItem", reservationItem);
    }

    @Override
    @Nonnull
    protected Class<ProductionOrderComponents> getEntityClass() {
        return ProductionOrderComponents.class;
    }

    @Override
    @Nonnull
    protected Map<String, Object> getKey() {
        return key;
    }

}
