
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.cloudplatform.connectivity.Destination;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmEntity;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import com.sap.cloud.sdk.s4hana.datamodel.odata.annotation.Key;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.field.ProductionOrderComponentsField;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.apiproductionorder2srv.selectable.ProductionOrderComponentsSelectable;
import com.sap.cloud.sdk.typeconverter.TypeConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * Production Order Components<p></p><p>Original entity name from the Odata EDM: <b>A_ProductionOrderComponent_2Type</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class ProductionOrderComponents
    extends VdmEntity<ProductionOrderComponents>
{

    /**
     * Selector for all available fields of ProductionOrderComponents.
     * 
     */
    public final static ProductionOrderComponentsSelectable ALL_FIELDS = () -> "*";
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>Reservation</b></p>
     * 
     * @return
     *     Number of reservation/dependent requirements
     */
    @Key
    @SerializedName("Reservation")
    @JsonProperty("Reservation")
    @Nullable
    @ODataField(odataName = "Reservation")
    private String reservation;
    /**
     * Use with available fluent helpers to apply the <b>Reservation</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> RESERVATION = new ProductionOrderComponentsField<String>("Reservation");
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>ReservationItem</b></p>
     * 
     * @return
     *     Reservation Item
     */
    @Key
    @SerializedName("ReservationItem")
    @JsonProperty("ReservationItem")
    @Nullable
    @ODataField(odataName = "ReservationItem")
    private String reservationItem;
    /**
     * Use with available fluent helpers to apply the <b>ReservationItem</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> RESERVATION_ITEM = new ProductionOrderComponentsField<String>("ReservationItem");
    /**
     * Constraints: Not nullable, Maximum length: 9 <p>Original property name from the Odata EDM: <b>MaterialGroup</b></p>
     * 
     * @return
     *     Material Group
     */
    @SerializedName("MaterialGroup")
    @JsonProperty("MaterialGroup")
    @Nullable
    @ODataField(odataName = "MaterialGroup")
    private String materialGroup;
    /**
     * Use with available fluent helpers to apply the <b>MaterialGroup</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> MATERIAL_GROUP = new ProductionOrderComponentsField<String>("MaterialGroup");
    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>Material</b></p>
     * 
     * @return
     *     Material Number
     */
    @SerializedName("Material")
    @JsonProperty("Material")
    @Nullable
    @ODataField(odataName = "Material")
    private String material;
    /**
     * Use with available fluent helpers to apply the <b>Material</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> MATERIAL = new ProductionOrderComponentsField<String>("Material");
    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>Plant</b></p>
     * 
     * @return
     *     Plant
     */
    @SerializedName("Plant")
    @JsonProperty("Plant")
    @Nullable
    @ODataField(odataName = "Plant")
    private String plant;
    /**
     * Use with available fluent helpers to apply the <b>Plant</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> PLANT = new ProductionOrderComponentsField<String>("Plant");
    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>ManufacturingOrderCategory</b></p>
     * 
     * @return
     *     Manufacturing Order Category
     */
    @SerializedName("ManufacturingOrderCategory")
    @JsonProperty("ManufacturingOrderCategory")
    @Nullable
    @ODataField(odataName = "ManufacturingOrderCategory")
    private String orderCategory;
    /**
     * Use with available fluent helpers to apply the <b>ManufacturingOrderCategory</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> ORDER_CATEGORY = new ProductionOrderComponentsField<String>("ManufacturingOrderCategory");
    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>ManufacturingOrderType</b></p>
     * 
     * @return
     *     Manufacturing Order Type
     */
    @SerializedName("ManufacturingOrderType")
    @JsonProperty("ManufacturingOrderType")
    @Nullable
    @ODataField(odataName = "ManufacturingOrderType")
    private String orderType;
    /**
     * Use with available fluent helpers to apply the <b>ManufacturingOrderType</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> ORDER_TYPE = new ProductionOrderComponentsField<String>("ManufacturingOrderType");
    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>ManufacturingOrder</b></p>
     * 
     * @return
     *     Production Order
     */
    @SerializedName("ManufacturingOrder")
    @JsonProperty("ManufacturingOrder")
    @Nullable
    @ODataField(odataName = "ManufacturingOrder")
    private String productionOrder;
    /**
     * Use with available fluent helpers to apply the <b>ManufacturingOrder</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> PRODUCTION_ORDER = new ProductionOrderComponentsField<String>("ManufacturingOrder");
    /**
     * Constraints: Not nullable, Maximum length: 6 <p>Original property name from the Odata EDM: <b>ManufacturingOrderSequence</b></p>
     * 
     * @return
     *     Sequence
     */
    @SerializedName("ManufacturingOrderSequence")
    @JsonProperty("ManufacturingOrderSequence")
    @Nullable
    @ODataField(odataName = "ManufacturingOrderSequence")
    private String sequence;
    /**
     * Use with available fluent helpers to apply the <b>ManufacturingOrderSequence</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> SEQUENCE = new ProductionOrderComponentsField<String>("ManufacturingOrderSequence");
    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>ManufacturingOrderOperation</b></p>
     * 
     * @return
     *     Manufacturing Order Operation
     */
    @SerializedName("ManufacturingOrderOperation")
    @JsonProperty("ManufacturingOrderOperation")
    @Nullable
    @ODataField(odataName = "ManufacturingOrderOperation")
    private String operation;
    /**
     * Use with available fluent helpers to apply the <b>ManufacturingOrderOperation</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> OPERATION = new ProductionOrderComponentsField<String>("ManufacturingOrderOperation");
    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>ProductionPlant</b></p>
     * 
     * @return
     *     Production Plant
     */
    @SerializedName("ProductionPlant")
    @JsonProperty("ProductionPlant")
    @Nullable
    @ODataField(odataName = "ProductionPlant")
    private String productionPlant;
    /**
     * Use with available fluent helpers to apply the <b>ProductionPlant</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> PRODUCTION_PLANT = new ProductionOrderComponentsField<String>("ProductionPlant");
    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>OrderInternalBillOfOperations</b></p>
     * 
     * @return
     *     Order Internal ID
     */
    @SerializedName("OrderInternalBillOfOperations")
    @JsonProperty("OrderInternalBillOfOperations")
    @Nullable
    @ODataField(odataName = "OrderInternalBillOfOperations")
    private String orderInternalID;
    /**
     * Use with available fluent helpers to apply the <b>OrderInternalBillOfOperations</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> ORDER_INTERNAL_ID = new ProductionOrderComponentsField<String>("OrderInternalBillOfOperations");
    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>MatlCompRequirementDate</b></p>
     * 
     * @return
     *     Material Component Requirement Date
     */
    @SerializedName("MatlCompRequirementDate")
    @JsonProperty("MatlCompRequirementDate")
    @Nullable
    @JsonSerialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeSerializer.class)
    @JsonDeserialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalDateTimeDeserializer.class)
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeAdapter.class)
    @ODataField(odataName = "MatlCompRequirementDate", converter = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalDateTimeCalendarConverter.class)
    private LocalDateTime requirementDate;
    /**
     * Use with available fluent helpers to apply the <b>MatlCompRequirementDate</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<LocalDateTime> REQUIREMENT_DATE = new ProductionOrderComponentsField<LocalDateTime>("MatlCompRequirementDate");
    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>MatlCompRequirementTime</b></p>
     * 
     * @return
     *     Material Component Requirement Time
     */
    @SerializedName("MatlCompRequirementTime")
    @JsonProperty("MatlCompRequirementTime")
    @Nullable
    @JsonSerialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalTimeSerializer.class)
    @JsonDeserialize(using = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.JacksonLocalTimeDeserializer.class)
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalTimeAdapter.class)
    @ODataField(odataName = "MatlCompRequirementTime", converter = com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.LocalTimeCalendarConverter.class)
    private LocalTime requirementTime;
    /**
     * Use with available fluent helpers to apply the <b>MatlCompRequirementTime</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<LocalTime> REQUIREMENT_TIME = new ProductionOrderComponentsField<LocalTime>("MatlCompRequirementTime");
    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>ReservationIsFinallyIssued</b></p>
     * 
     * @return
     *     Final Issue for Reservation
     */
    @SerializedName("ReservationIsFinallyIssued")
    @JsonProperty("ReservationIsFinallyIssued")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "ReservationIsFinallyIssued")
    private Boolean finalIssue;
    /**
     * Use with available fluent helpers to apply the <b>ReservationIsFinallyIssued</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<Boolean> FINAL_ISSUE = new ProductionOrderComponentsField<Boolean>("ReservationIsFinallyIssued");
    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>MatlCompIsMarkedForDeletion</b></p>
     * 
     * @return
     *     Marked for Deletion
     */
    @SerializedName("MatlCompIsMarkedForDeletion")
    @JsonProperty("MatlCompIsMarkedForDeletion")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "MatlCompIsMarkedForDeletion")
    private Boolean markedForDeletion;
    /**
     * Use with available fluent helpers to apply the <b>MatlCompIsMarkedForDeletion</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<Boolean> MARKED_FOR_DELETION = new ProductionOrderComponentsField<Boolean>("MatlCompIsMarkedForDeletion");
    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>IsBulkMaterialComponent</b></p>
     * 
     * @return
     *     Indicator: Bulk Material
     */
    @SerializedName("IsBulkMaterialComponent")
    @JsonProperty("IsBulkMaterialComponent")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "IsBulkMaterialComponent")
    private Boolean bulkMaterial;
    /**
     * Use with available fluent helpers to apply the <b>IsBulkMaterialComponent</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<Boolean> BULK_MATERIAL = new ProductionOrderComponentsField<Boolean>("IsBulkMaterialComponent");
    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>MatlCompIsMarkedForBackflush</b></p>
     * 
     * @return
     *     Indicator: Backflush
     */
    @SerializedName("MatlCompIsMarkedForBackflush")
    @JsonProperty("MatlCompIsMarkedForBackflush")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "MatlCompIsMarkedForBackflush")
    private Boolean backflush;
    /**
     * Use with available fluent helpers to apply the <b>MatlCompIsMarkedForBackflush</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<Boolean> BACKFLUSH = new ProductionOrderComponentsField<Boolean>("MatlCompIsMarkedForBackflush");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>MaterialCompIsCostRelevant</b></p>
     * 
     * @return
     *     Indicator for Relevancy to Costing
     */
    @SerializedName("MaterialCompIsCostRelevant")
    @JsonProperty("MaterialCompIsCostRelevant")
    @Nullable
    @ODataField(odataName = "MaterialCompIsCostRelevant")
    private String costingRelevncy;
    /**
     * Use with available fluent helpers to apply the <b>MaterialCompIsCostRelevant</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> COSTING_RELEVNCY = new ProductionOrderComponentsField<String>("MaterialCompIsCostRelevant");
    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>OrderComponentLongText</b></p>
     * 
     * @return
     *     Long Text
     */
    @SerializedName("OrderComponentLongText")
    @JsonProperty("OrderComponentLongText")
    @Nullable
    @ODataField(odataName = "OrderComponentLongText")
    private String longText;
    /**
     * Use with available fluent helpers to apply the <b>OrderComponentLongText</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> LONG_TEXT = new ProductionOrderComponentsField<String>("OrderComponentLongText");
    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>SalesOrder</b></p>
     * 
     * @return
     *     Sales Order
     */
    @SerializedName("SalesOrder")
    @JsonProperty("SalesOrder")
    @Nullable
    @ODataField(odataName = "SalesOrder")
    private String salesOrder;
    /**
     * Use with available fluent helpers to apply the <b>SalesOrder</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> SALES_ORDER = new ProductionOrderComponentsField<String>("SalesOrder");
    /**
     * Constraints: Not nullable, Maximum length: 6 <p>Original property name from the Odata EDM: <b>SalesOrderItem</b></p>
     * 
     * @return
     *     Sales Order Item
     */
    @SerializedName("SalesOrderItem")
    @JsonProperty("SalesOrderItem")
    @Nullable
    @ODataField(odataName = "SalesOrderItem")
    private String salesOrderItem;
    /**
     * Use with available fluent helpers to apply the <b>SalesOrderItem</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> SALES_ORDER_ITEM = new ProductionOrderComponentsField<String>("SalesOrderItem");
    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>SortField</b></p>
     * 
     * @return
     *     Sort String
     */
    @SerializedName("SortField")
    @JsonProperty("SortField")
    @Nullable
    @ODataField(odataName = "SortField")
    private String sortString;
    /**
     * Use with available fluent helpers to apply the <b>SortField</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> SORT_STRING = new ProductionOrderComponentsField<String>("SortField");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BillOfMaterialCategory</b></p>
     * 
     * @return
     *     Bill of Material Category Code
     */
    @SerializedName("BillOfMaterialCategory")
    @JsonProperty("BillOfMaterialCategory")
    @Nullable
    @ODataField(odataName = "BillOfMaterialCategory")
    private String bOMCategory;
    /**
     * Use with available fluent helpers to apply the <b>BillOfMaterialCategory</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> BOM_CATEGORY = new ProductionOrderComponentsField<String>("BillOfMaterialCategory");
    /**
     * Constraints: Not nullable, Maximum length: 8 <p>Original property name from the Odata EDM: <b>BOMItem</b></p>
     * 
     * @return
     *     Bill of Material Item
     */
    @SerializedName("BOMItem")
    @JsonProperty("BOMItem")
    @Nullable
    @ODataField(odataName = "BOMItem")
    private String bOMItem;
    /**
     * Use with available fluent helpers to apply the <b>BOMItem</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> BOM_ITEM = new ProductionOrderComponentsField<String>("BOMItem");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BOMItemCategory</b></p>
     * 
     * @return
     *     Bill of Material Item Category
     */
    @SerializedName("BOMItemCategory")
    @JsonProperty("BOMItemCategory")
    @Nullable
    @ODataField(odataName = "BOMItemCategory")
    private String bOMItemCategory;
    /**
     * Use with available fluent helpers to apply the <b>BOMItemCategory</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> BOM_ITEM_CATEGORY = new ProductionOrderComponentsField<String>("BOMItemCategory");
    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>BillOfMaterialItemNumber</b></p>
     * 
     * @return
     *     BOM item number
     */
    @SerializedName("BillOfMaterialItemNumber")
    @JsonProperty("BillOfMaterialItemNumber")
    @Nullable
    @ODataField(odataName = "BillOfMaterialItemNumber")
    private String bOMItem_2;
    /**
     * Use with available fluent helpers to apply the <b>BillOfMaterialItemNumber</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> BOM_ITEM_2 = new ProductionOrderComponentsField<String>("BillOfMaterialItemNumber");
    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>BOMItemDescription</b></p>
     * 
     * @return
     *     BOM Item Text (Line 1)
     */
    @SerializedName("BOMItemDescription")
    @JsonProperty("BOMItemDescription")
    @Nullable
    @ODataField(odataName = "BOMItemDescription")
    private String bOMItemText;
    /**
     * Use with available fluent helpers to apply the <b>BOMItemDescription</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> BOM_ITEM_TEXT = new ProductionOrderComponentsField<String>("BOMItemDescription");
    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>StorageLocation</b></p>
     * 
     * @return
     *     Storage Location
     */
    @SerializedName("StorageLocation")
    @JsonProperty("StorageLocation")
    @Nullable
    @ODataField(odataName = "StorageLocation")
    private String storageLocation;
    /**
     * Use with available fluent helpers to apply the <b>StorageLocation</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> STORAGE_LOCATION = new ProductionOrderComponentsField<String>("StorageLocation");
    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>Batch</b></p>
     * 
     * @return
     *     Batch Number
     */
    @SerializedName("Batch")
    @JsonProperty("Batch")
    @Nullable
    @ODataField(odataName = "Batch")
    private String batch;
    /**
     * Use with available fluent helpers to apply the <b>Batch</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> BATCH = new ProductionOrderComponentsField<String>("Batch");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BatchSplitType</b></p>
     * 
     * @return
     *     The batchSplitType contained in this entity.
     */
    @SerializedName("BatchSplitType")
    @JsonProperty("BatchSplitType")
    @Nullable
    @ODataField(odataName = "BatchSplitType")
    private String batchSplitType;
    /**
     * Use with available fluent helpers to apply the <b>BatchSplitType</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> BATCH_SPLIT_TYPE = new ProductionOrderComponentsField<String>("BatchSplitType");
    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>GoodsMovementType</b></p>
     * 
     * @return
     *     Movement Type (Inventory Management)
     */
    @SerializedName("GoodsMovementType")
    @JsonProperty("GoodsMovementType")
    @Nullable
    @ODataField(odataName = "GoodsMovementType")
    private String movementType;
    /**
     * Use with available fluent helpers to apply the <b>GoodsMovementType</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> MOVEMENT_TYPE = new ProductionOrderComponentsField<String>("GoodsMovementType");
    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>SupplyArea</b></p>
     * 
     * @return
     *     Production Supply Area
     */
    @SerializedName("SupplyArea")
    @JsonProperty("SupplyArea")
    @Nullable
    @ODataField(odataName = "SupplyArea")
    private String productionSupplyArea;
    /**
     * Use with available fluent helpers to apply the <b>SupplyArea</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> PRODUCTION_SUPPLY_AREA = new ProductionOrderComponentsField<String>("SupplyArea");
    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>GoodsRecipientName</b></p>
     * 
     * @return
     *     Goods Recipient
     */
    @SerializedName("GoodsRecipientName")
    @JsonProperty("GoodsRecipientName")
    @Nullable
    @ODataField(odataName = "GoodsRecipientName")
    private String goodsRecipient;
    /**
     * Use with available fluent helpers to apply the <b>GoodsRecipientName</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> GOODS_RECIPIENT = new ProductionOrderComponentsField<String>("GoodsRecipientName");
    /**
     * Constraints: Not nullable, Maximum length: 25 <p>Original property name from the Odata EDM: <b>UnloadingPointName</b></p>
     * 
     * @return
     *     Unloading Point
     */
    @SerializedName("UnloadingPointName")
    @JsonProperty("UnloadingPointName")
    @Nullable
    @ODataField(odataName = "UnloadingPointName")
    private String unloadingPoint;
    /**
     * Use with available fluent helpers to apply the <b>UnloadingPointName</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> UNLOADING_POINT = new ProductionOrderComponentsField<String>("UnloadingPointName");
    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>MaterialCompIsAlternativeItem</b></p>
     * 
     * @return
     *     Alternative Item Indicator
     */
    @SerializedName("MaterialCompIsAlternativeItem")
    @JsonProperty("MaterialCompIsAlternativeItem")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "MaterialCompIsAlternativeItem")
    private Boolean alternativeItem;
    /**
     * Use with available fluent helpers to apply the <b>MaterialCompIsAlternativeItem</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<Boolean> ALTERNATIVE_ITEM = new ProductionOrderComponentsField<Boolean>("MaterialCompIsAlternativeItem");
    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>AlternativeItemGroup</b></p>
     * 
     * @return
     *     Alternative Item Group
     */
    @SerializedName("AlternativeItemGroup")
    @JsonProperty("AlternativeItemGroup")
    @Nullable
    @ODataField(odataName = "AlternativeItemGroup")
    private String alternativeItemGroup;
    /**
     * Use with available fluent helpers to apply the <b>AlternativeItemGroup</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> ALTERNATIVE_ITEM_GROUP = new ProductionOrderComponentsField<String>("AlternativeItemGroup");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>AlternativeItemStrategy</b></p>
     * 
     * @return
     *     Alternative Item Strategy
     */
    @SerializedName("AlternativeItemStrategy")
    @JsonProperty("AlternativeItemStrategy")
    @Nullable
    @ODataField(odataName = "AlternativeItemStrategy")
    private String alternativeItemStrategy;
    /**
     * Use with available fluent helpers to apply the <b>AlternativeItemStrategy</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> ALTERNATIVE_ITEM_STRATEGY = new ProductionOrderComponentsField<String>("AlternativeItemStrategy");
    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>AlternativeItemPriority</b></p>
     * 
     * @return
     *     Alternative Item Priority
     */
    @SerializedName("AlternativeItemPriority")
    @JsonProperty("AlternativeItemPriority")
    @Nullable
    @ODataField(odataName = "AlternativeItemPriority")
    private String alternativeItemPriority;
    /**
     * Use with available fluent helpers to apply the <b>AlternativeItemPriority</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> ALTERNATIVE_ITEM_PRIORITY = new ProductionOrderComponentsField<String>("AlternativeItemPriority");
    /**
     * Constraints: Not nullable, Precision: 3, Scale: 0 <p>Original property name from the Odata EDM: <b>UsageProbabilityPercent</b></p>
     * 
     * @return
     *     Usage Probability in % (Alternative Item)
     */
    @SerializedName("UsageProbabilityPercent")
    @JsonProperty("UsageProbabilityPercent")
    @Nullable
    @ODataField(odataName = "UsageProbabilityPercent")
    private BigDecimal usageProbability;
    /**
     * Use with available fluent helpers to apply the <b>UsageProbabilityPercent</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<BigDecimal> USAGE_PROBABILITY = new ProductionOrderComponentsField<BigDecimal>("UsageProbabilityPercent");
    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>MaterialComponentIsPhantomItem</b></p>
     * 
     * @return
     *     Phantom Item Indicator
     */
    @SerializedName("MaterialComponentIsPhantomItem")
    @JsonProperty("MaterialComponentIsPhantomItem")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "MaterialComponentIsPhantomItem")
    private Boolean phantomItem;
    /**
     * Use with available fluent helpers to apply the <b>MaterialComponentIsPhantomItem</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<Boolean> PHANTOM_ITEM = new ProductionOrderComponentsField<Boolean>("MaterialComponentIsPhantomItem");
    /**
     * Constraints: Not nullable, Precision: 3, Scale: 0 <p>Original property name from the Odata EDM: <b>LeadTimeOffset</b></p>
     * 
     * @return
     *     Lead-Time Offset
     */
    @SerializedName("LeadTimeOffset")
    @JsonProperty("LeadTimeOffset")
    @Nullable
    @ODataField(odataName = "LeadTimeOffset")
    private BigDecimal leadTimeOffset;
    /**
     * Use with available fluent helpers to apply the <b>LeadTimeOffset</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<BigDecimal> LEAD_TIME_OFFSET = new ProductionOrderComponentsField<BigDecimal>("LeadTimeOffset");
    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>QuantityIsFixed</b></p>
     * 
     * @return
     *     Quantity is fixed
     */
    @SerializedName("QuantityIsFixed")
    @JsonProperty("QuantityIsFixed")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "QuantityIsFixed")
    private Boolean quantityIsFixed;
    /**
     * Use with available fluent helpers to apply the <b>QuantityIsFixed</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<Boolean> QUANTITY_IS_FIXED = new ProductionOrderComponentsField<Boolean>("QuantityIsFixed");
    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>IsNetScrap</b></p>
     * 
     * @return
     *     Net Scrap Indicator
     */
    @SerializedName("IsNetScrap")
    @JsonProperty("IsNetScrap")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "IsNetScrap")
    private Boolean netScrapIndicator;
    /**
     * Use with available fluent helpers to apply the <b>IsNetScrap</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<Boolean> NET_SCRAP_INDICATOR = new ProductionOrderComponentsField<Boolean>("IsNetScrap");
    /**
     * Constraints: Not nullable, Precision: 5, Scale: 2 <p>Original property name from the Odata EDM: <b>ComponentScrapInPercent</b></p>
     * 
     * @return
     *     Component Scrap in Percent
     */
    @SerializedName("ComponentScrapInPercent")
    @JsonProperty("ComponentScrapInPercent")
    @Nullable
    @ODataField(odataName = "ComponentScrapInPercent")
    private BigDecimal componentScrap;
    /**
     * Use with available fluent helpers to apply the <b>ComponentScrapInPercent</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<BigDecimal> COMPONENT_SCRAP = new ProductionOrderComponentsField<BigDecimal>("ComponentScrapInPercent");
    /**
     * Constraints: Not nullable, Precision: 5, Scale: 2 <p>Original property name from the Odata EDM: <b>OperationScrapInPercent</b></p>
     * 
     * @return
     *     Operation Scrap
     */
    @SerializedName("OperationScrapInPercent")
    @JsonProperty("OperationScrapInPercent")
    @Nullable
    @ODataField(odataName = "OperationScrapInPercent")
    private BigDecimal operationScrapIn;
    /**
     * Use with available fluent helpers to apply the <b>OperationScrapInPercent</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<BigDecimal> OPERATION_SCRAP_IN = new ProductionOrderComponentsField<BigDecimal>("OperationScrapInPercent");
    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>BaseUnit</b></p>
     * 
     * @return
     *     Base Unit of Measure
     */
    @SerializedName("BaseUnit")
    @JsonProperty("BaseUnit")
    @Nullable
    @ODataField(odataName = "BaseUnit")
    private String baseUnitOfMeasure;
    /**
     * Use with available fluent helpers to apply the <b>BaseUnit</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> BASE_UNIT_OF_MEASURE = new ProductionOrderComponentsField<String>("BaseUnit");
    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>BaseUnitISOCode</b></p>
     * 
     * @return
     *     ISO Code for Unit of Measurement
     */
    @SerializedName("BaseUnitISOCode")
    @JsonProperty("BaseUnitISOCode")
    @Nullable
    @ODataField(odataName = "BaseUnitISOCode")
    private String iSOCode;
    /**
     * Use with available fluent helpers to apply the <b>BaseUnitISOCode</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> ISO_CODE = new ProductionOrderComponentsField<String>("BaseUnitISOCode");
    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>BaseUnitSAPCode</b></p>
     * 
     * @return
     *     Unit of Measurement, Internal SAP Code (No Conversion)
     */
    @SerializedName("BaseUnitSAPCode")
    @JsonProperty("BaseUnitSAPCode")
    @Nullable
    @ODataField(odataName = "BaseUnitSAPCode")
    private String internalSAPCode;
    /**
     * Use with available fluent helpers to apply the <b>BaseUnitSAPCode</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> INTERNAL_SAP_CODE = new ProductionOrderComponentsField<String>("BaseUnitSAPCode");
    /**
     * Constraints: Not nullable, Precision: 13, Scale: 3 <p>Original property name from the Odata EDM: <b>RequiredQuantity</b></p>
     * 
     * @return
     *     Requirement Quantity
     */
    @SerializedName("RequiredQuantity")
    @JsonProperty("RequiredQuantity")
    @Nullable
    @ODataField(odataName = "RequiredQuantity")
    private BigDecimal requirementQuantity;
    /**
     * Use with available fluent helpers to apply the <b>RequiredQuantity</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<BigDecimal> REQUIREMENT_QUANTITY = new ProductionOrderComponentsField<BigDecimal>("RequiredQuantity");
    /**
     * Constraints: Not nullable, Precision: 13, Scale: 3 <p>Original property name from the Odata EDM: <b>WithdrawnQuantity</b></p>
     * 
     * @return
     *     Withdrawn Quantity
     */
    @SerializedName("WithdrawnQuantity")
    @JsonProperty("WithdrawnQuantity")
    @Nullable
    @ODataField(odataName = "WithdrawnQuantity")
    private BigDecimal withdrawnQuantity;
    /**
     * Use with available fluent helpers to apply the <b>WithdrawnQuantity</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<BigDecimal> WITHDRAWN_QUANTITY = new ProductionOrderComponentsField<BigDecimal>("WithdrawnQuantity");
    /**
     * Constraints: Not nullable, Precision: 15, Scale: 3 <p>Original property name from the Odata EDM: <b>ConfirmedAvailableQuantity</b></p>
     * 
     * @return
     *     Available Quantity
     */
    @SerializedName("ConfirmedAvailableQuantity")
    @JsonProperty("ConfirmedAvailableQuantity")
    @Nullable
    @ODataField(odataName = "ConfirmedAvailableQuantity")
    private BigDecimal availableQuantity;
    /**
     * Use with available fluent helpers to apply the <b>ConfirmedAvailableQuantity</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<BigDecimal> AVAILABLE_QUANTITY = new ProductionOrderComponentsField<BigDecimal>("ConfirmedAvailableQuantity");
    /**
     * Constraints: Not nullable, Precision: 13, Scale: 3 <p>Original property name from the Odata EDM: <b>MaterialCompOriginalQuantity</b></p>
     * 
     * @return
     *     Original Quantity of a Material Component
     */
    @SerializedName("MaterialCompOriginalQuantity")
    @JsonProperty("MaterialCompOriginalQuantity")
    @Nullable
    @ODataField(odataName = "MaterialCompOriginalQuantity")
    private BigDecimal originalQuantity;
    /**
     * Use with available fluent helpers to apply the <b>MaterialCompOriginalQuantity</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<BigDecimal> ORIGINAL_QUANTITY = new ProductionOrderComponentsField<BigDecimal>("MaterialCompOriginalQuantity");
    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>EntryUnit</b></p>
     * 
     * @return
     *     Unit of entry
     */
    @SerializedName("EntryUnit")
    @JsonProperty("EntryUnit")
    @Nullable
    @ODataField(odataName = "EntryUnit")
    private String unitOfEntry;
    /**
     * Use with available fluent helpers to apply the <b>EntryUnit</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> UNIT_OF_ENTRY = new ProductionOrderComponentsField<String>("EntryUnit");
    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>EntryUnitISOCode</b></p>
     * 
     * @return
     *     ISO Code for Unit of Measurement
     */
    @SerializedName("EntryUnitISOCode")
    @JsonProperty("EntryUnitISOCode")
    @Nullable
    @ODataField(odataName = "EntryUnitISOCode")
    private String iSOCode_2;
    /**
     * Use with available fluent helpers to apply the <b>EntryUnitISOCode</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> ISO_CODE_2 = new ProductionOrderComponentsField<String>("EntryUnitISOCode");
    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>EntryUnitSAPCode</b></p>
     * 
     * @return
     *     Unit of Measurement, Internal SAP Code (No Conversion)
     */
    @SerializedName("EntryUnitSAPCode")
    @JsonProperty("EntryUnitSAPCode")
    @Nullable
    @ODataField(odataName = "EntryUnitSAPCode")
    private String internalSAPCode_2;
    /**
     * Use with available fluent helpers to apply the <b>EntryUnitSAPCode</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> INTERNAL_SAP_CODE_2 = new ProductionOrderComponentsField<String>("EntryUnitSAPCode");
    /**
     * Constraints: Not nullable, Precision: 13, Scale: 3 <p>Original property name from the Odata EDM: <b>GoodsMovementEntryQty</b></p>
     * 
     * @return
     *     Quantity in Unit of Entry
     */
    @SerializedName("GoodsMovementEntryQty")
    @JsonProperty("GoodsMovementEntryQty")
    @Nullable
    @ODataField(odataName = "GoodsMovementEntryQty")
    private BigDecimal quantityInUnitOfEntry;
    /**
     * Use with available fluent helpers to apply the <b>GoodsMovementEntryQty</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<BigDecimal> QUANTITY_IN_UNIT_OF_ENTRY = new ProductionOrderComponentsField<BigDecimal>("GoodsMovementEntryQty");
    /**
     * Constraints: Not nullable, Maximum length: 5 <p>Original property name from the Odata EDM: <b>Currency</b></p>
     * 
     * @return
     *     Currency Key
     */
    @SerializedName("Currency")
    @JsonProperty("Currency")
    @Nullable
    @ODataField(odataName = "Currency")
    private String currency;
    /**
     * Use with available fluent helpers to apply the <b>Currency</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<String> CURRENCY = new ProductionOrderComponentsField<String>("Currency");
    /**
     * Constraints: Not nullable, Precision: 14, Scale: 3 <p>Original property name from the Odata EDM: <b>WithdrawnQuantityAmount</b></p>
     * 
     * @return
     *     Value Withdrawn
     */
    @SerializedName("WithdrawnQuantityAmount")
    @JsonProperty("WithdrawnQuantityAmount")
    @Nullable
    @ODataField(odataName = "WithdrawnQuantityAmount")
    private BigDecimal valueWithdrawn;
    /**
     * Use with available fluent helpers to apply the <b>WithdrawnQuantityAmount</b> field to query operations.
     * 
     */
    public final static ProductionOrderComponentsField<BigDecimal> VALUE_WITHDRAWN = new ProductionOrderComponentsField<BigDecimal>("WithdrawnQuantityAmount");

    @Nonnull
    @Override
    public Class<ProductionOrderComponents> getType() {
        return ProductionOrderComponents.class;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>Reservation</b></p>
     * 
     * @param reservation
     *     Number of reservation/dependent requirements
     */
    public void setReservation(
        @Nullable
        final String reservation) {
        rememberChangedField("Reservation", this.reservation);
        this.reservation = reservation;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>ReservationItem</b></p>
     * 
     * @param reservationItem
     *     Reservation Item
     */
    public void setReservationItem(
        @Nullable
        final String reservationItem) {
        rememberChangedField("ReservationItem", this.reservationItem);
        this.reservationItem = reservationItem;
    }

    /**
     * Constraints: Not nullable, Maximum length: 9 <p>Original property name from the Odata EDM: <b>MaterialGroup</b></p>
     * 
     * @param materialGroup
     *     Material Group
     */
    public void setMaterialGroup(
        @Nullable
        final String materialGroup) {
        rememberChangedField("MaterialGroup", this.materialGroup);
        this.materialGroup = materialGroup;
    }

    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>Material</b></p>
     * 
     * @param material
     *     Material Number
     */
    public void setMaterial(
        @Nullable
        final String material) {
        rememberChangedField("Material", this.material);
        this.material = material;
    }

    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>Plant</b></p>
     * 
     * @param plant
     *     Plant
     */
    public void setPlant(
        @Nullable
        final String plant) {
        rememberChangedField("Plant", this.plant);
        this.plant = plant;
    }

    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>ManufacturingOrderCategory</b></p>
     * 
     * @param orderCategory
     *     Manufacturing Order Category
     */
    public void setOrderCategory(
        @Nullable
        final String orderCategory) {
        rememberChangedField("ManufacturingOrderCategory", this.orderCategory);
        this.orderCategory = orderCategory;
    }

    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>ManufacturingOrderType</b></p>
     * 
     * @param orderType
     *     Manufacturing Order Type
     */
    public void setOrderType(
        @Nullable
        final String orderType) {
        rememberChangedField("ManufacturingOrderType", this.orderType);
        this.orderType = orderType;
    }

    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>ManufacturingOrder</b></p>
     * 
     * @param productionOrder
     *     Production Order
     */
    public void setProductionOrder(
        @Nullable
        final String productionOrder) {
        rememberChangedField("ManufacturingOrder", this.productionOrder);
        this.productionOrder = productionOrder;
    }

    /**
     * Constraints: Not nullable, Maximum length: 6 <p>Original property name from the Odata EDM: <b>ManufacturingOrderSequence</b></p>
     * 
     * @param sequence
     *     Sequence
     */
    public void setSequence(
        @Nullable
        final String sequence) {
        rememberChangedField("ManufacturingOrderSequence", this.sequence);
        this.sequence = sequence;
    }

    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>ManufacturingOrderOperation</b></p>
     * 
     * @param operation
     *     Manufacturing Order Operation
     */
    public void setOperation(
        @Nullable
        final String operation) {
        rememberChangedField("ManufacturingOrderOperation", this.operation);
        this.operation = operation;
    }

    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>ProductionPlant</b></p>
     * 
     * @param productionPlant
     *     Production Plant
     */
    public void setProductionPlant(
        @Nullable
        final String productionPlant) {
        rememberChangedField("ProductionPlant", this.productionPlant);
        this.productionPlant = productionPlant;
    }

    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>OrderInternalBillOfOperations</b></p>
     * 
     * @param orderInternalID
     *     Order Internal ID
     */
    public void setOrderInternalID(
        @Nullable
        final String orderInternalID) {
        rememberChangedField("OrderInternalBillOfOperations", this.orderInternalID);
        this.orderInternalID = orderInternalID;
    }

    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>MatlCompRequirementDate</b></p>
     * 
     * @param requirementDate
     *     Material Component Requirement Date
     */
    public void setRequirementDate(
        @Nullable
        final LocalDateTime requirementDate) {
        rememberChangedField("MatlCompRequirementDate", this.requirementDate);
        this.requirementDate = requirementDate;
    }

    /**
     * Constraints: Not nullable, Precision: 0 <p>Original property name from the Odata EDM: <b>MatlCompRequirementTime</b></p>
     * 
     * @param requirementTime
     *     Material Component Requirement Time
     */
    public void setRequirementTime(
        @Nullable
        final LocalTime requirementTime) {
        rememberChangedField("MatlCompRequirementTime", this.requirementTime);
        this.requirementTime = requirementTime;
    }

    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>ReservationIsFinallyIssued</b></p>
     * 
     * @param finalIssue
     *     Final Issue for Reservation
     */
    public void setFinalIssue(
        @Nullable
        final Boolean finalIssue) {
        rememberChangedField("ReservationIsFinallyIssued", this.finalIssue);
        this.finalIssue = finalIssue;
    }

    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>MatlCompIsMarkedForDeletion</b></p>
     * 
     * @param markedForDeletion
     *     Marked for Deletion
     */
    public void setMarkedForDeletion(
        @Nullable
        final Boolean markedForDeletion) {
        rememberChangedField("MatlCompIsMarkedForDeletion", this.markedForDeletion);
        this.markedForDeletion = markedForDeletion;
    }

    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>IsBulkMaterialComponent</b></p>
     * 
     * @param bulkMaterial
     *     Indicator: Bulk Material
     */
    public void setBulkMaterial(
        @Nullable
        final Boolean bulkMaterial) {
        rememberChangedField("IsBulkMaterialComponent", this.bulkMaterial);
        this.bulkMaterial = bulkMaterial;
    }

    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>MatlCompIsMarkedForBackflush</b></p>
     * 
     * @param backflush
     *     Indicator: Backflush
     */
    public void setBackflush(
        @Nullable
        final Boolean backflush) {
        rememberChangedField("MatlCompIsMarkedForBackflush", this.backflush);
        this.backflush = backflush;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>MaterialCompIsCostRelevant</b></p>
     * 
     * @param costingRelevncy
     *     Indicator for Relevancy to Costing
     */
    public void setCostingRelevncy(
        @Nullable
        final String costingRelevncy) {
        rememberChangedField("MaterialCompIsCostRelevant", this.costingRelevncy);
        this.costingRelevncy = costingRelevncy;
    }

    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>OrderComponentLongText</b></p>
     * 
     * @param longText
     *     Long Text
     */
    public void setLongText(
        @Nullable
        final String longText) {
        rememberChangedField("OrderComponentLongText", this.longText);
        this.longText = longText;
    }

    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>SalesOrder</b></p>
     * 
     * @param salesOrder
     *     Sales Order
     */
    public void setSalesOrder(
        @Nullable
        final String salesOrder) {
        rememberChangedField("SalesOrder", this.salesOrder);
        this.salesOrder = salesOrder;
    }

    /**
     * Constraints: Not nullable, Maximum length: 6 <p>Original property name from the Odata EDM: <b>SalesOrderItem</b></p>
     * 
     * @param salesOrderItem
     *     Sales Order Item
     */
    public void setSalesOrderItem(
        @Nullable
        final String salesOrderItem) {
        rememberChangedField("SalesOrderItem", this.salesOrderItem);
        this.salesOrderItem = salesOrderItem;
    }

    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>SortField</b></p>
     * 
     * @param sortString
     *     Sort String
     */
    public void setSortString(
        @Nullable
        final String sortString) {
        rememberChangedField("SortField", this.sortString);
        this.sortString = sortString;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BillOfMaterialCategory</b></p>
     * 
     * @param bOMCategory
     *     Bill of Material Category Code
     */
    public void setBOMCategory(
        @Nullable
        final String bOMCategory) {
        rememberChangedField("BillOfMaterialCategory", this.bOMCategory);
        this.bOMCategory = bOMCategory;
    }

    /**
     * Constraints: Not nullable, Maximum length: 8 <p>Original property name from the Odata EDM: <b>BOMItem</b></p>
     * 
     * @param bOMItem
     *     Bill of Material Item
     */
    public void setBOMItem(
        @Nullable
        final String bOMItem) {
        rememberChangedField("BOMItem", this.bOMItem);
        this.bOMItem = bOMItem;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BOMItemCategory</b></p>
     * 
     * @param bOMItemCategory
     *     Bill of Material Item Category
     */
    public void setBOMItemCategory(
        @Nullable
        final String bOMItemCategory) {
        rememberChangedField("BOMItemCategory", this.bOMItemCategory);
        this.bOMItemCategory = bOMItemCategory;
    }

    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>BillOfMaterialItemNumber</b></p>
     * 
     * @param bOMItem_2
     *     BOM item number
     */
    public void setBOMItem_2(
        @Nullable
        final String bOMItem_2) {
        rememberChangedField("BillOfMaterialItemNumber", this.bOMItem_2);
        this.bOMItem_2 = bOMItem_2;
    }

    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>BOMItemDescription</b></p>
     * 
     * @param bOMItemText
     *     BOM Item Text (Line 1)
     */
    public void setBOMItemText(
        @Nullable
        final String bOMItemText) {
        rememberChangedField("BOMItemDescription", this.bOMItemText);
        this.bOMItemText = bOMItemText;
    }

    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>StorageLocation</b></p>
     * 
     * @param storageLocation
     *     Storage Location
     */
    public void setStorageLocation(
        @Nullable
        final String storageLocation) {
        rememberChangedField("StorageLocation", this.storageLocation);
        this.storageLocation = storageLocation;
    }

    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>Batch</b></p>
     * 
     * @param batch
     *     Batch Number
     */
    public void setBatch(
        @Nullable
        final String batch) {
        rememberChangedField("Batch", this.batch);
        this.batch = batch;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>BatchSplitType</b></p>
     * 
     * @param batchSplitType
     *     The batchSplitType to set.
     */
    public void setBatchSplitType(
        @Nullable
        final String batchSplitType) {
        rememberChangedField("BatchSplitType", this.batchSplitType);
        this.batchSplitType = batchSplitType;
    }

    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>GoodsMovementType</b></p>
     * 
     * @param movementType
     *     Movement Type (Inventory Management)
     */
    public void setMovementType(
        @Nullable
        final String movementType) {
        rememberChangedField("GoodsMovementType", this.movementType);
        this.movementType = movementType;
    }

    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>SupplyArea</b></p>
     * 
     * @param productionSupplyArea
     *     Production Supply Area
     */
    public void setProductionSupplyArea(
        @Nullable
        final String productionSupplyArea) {
        rememberChangedField("SupplyArea", this.productionSupplyArea);
        this.productionSupplyArea = productionSupplyArea;
    }

    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>GoodsRecipientName</b></p>
     * 
     * @param goodsRecipient
     *     Goods Recipient
     */
    public void setGoodsRecipient(
        @Nullable
        final String goodsRecipient) {
        rememberChangedField("GoodsRecipientName", this.goodsRecipient);
        this.goodsRecipient = goodsRecipient;
    }

    /**
     * Constraints: Not nullable, Maximum length: 25 <p>Original property name from the Odata EDM: <b>UnloadingPointName</b></p>
     * 
     * @param unloadingPoint
     *     Unloading Point
     */
    public void setUnloadingPoint(
        @Nullable
        final String unloadingPoint) {
        rememberChangedField("UnloadingPointName", this.unloadingPoint);
        this.unloadingPoint = unloadingPoint;
    }

    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>MaterialCompIsAlternativeItem</b></p>
     * 
     * @param alternativeItem
     *     Alternative Item Indicator
     */
    public void setAlternativeItem(
        @Nullable
        final Boolean alternativeItem) {
        rememberChangedField("MaterialCompIsAlternativeItem", this.alternativeItem);
        this.alternativeItem = alternativeItem;
    }

    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>AlternativeItemGroup</b></p>
     * 
     * @param alternativeItemGroup
     *     Alternative Item Group
     */
    public void setAlternativeItemGroup(
        @Nullable
        final String alternativeItemGroup) {
        rememberChangedField("AlternativeItemGroup", this.alternativeItemGroup);
        this.alternativeItemGroup = alternativeItemGroup;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>AlternativeItemStrategy</b></p>
     * 
     * @param alternativeItemStrategy
     *     Alternative Item Strategy
     */
    public void setAlternativeItemStrategy(
        @Nullable
        final String alternativeItemStrategy) {
        rememberChangedField("AlternativeItemStrategy", this.alternativeItemStrategy);
        this.alternativeItemStrategy = alternativeItemStrategy;
    }

    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>AlternativeItemPriority</b></p>
     * 
     * @param alternativeItemPriority
     *     Alternative Item Priority
     */
    public void setAlternativeItemPriority(
        @Nullable
        final String alternativeItemPriority) {
        rememberChangedField("AlternativeItemPriority", this.alternativeItemPriority);
        this.alternativeItemPriority = alternativeItemPriority;
    }

    /**
     * Constraints: Not nullable, Precision: 3, Scale: 0 <p>Original property name from the Odata EDM: <b>UsageProbabilityPercent</b></p>
     * 
     * @param usageProbability
     *     Usage Probability in % (Alternative Item)
     */
    public void setUsageProbability(
        @Nullable
        final BigDecimal usageProbability) {
        rememberChangedField("UsageProbabilityPercent", this.usageProbability);
        this.usageProbability = usageProbability;
    }

    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>MaterialComponentIsPhantomItem</b></p>
     * 
     * @param phantomItem
     *     Phantom Item Indicator
     */
    public void setPhantomItem(
        @Nullable
        final Boolean phantomItem) {
        rememberChangedField("MaterialComponentIsPhantomItem", this.phantomItem);
        this.phantomItem = phantomItem;
    }

    /**
     * Constraints: Not nullable, Precision: 3, Scale: 0 <p>Original property name from the Odata EDM: <b>LeadTimeOffset</b></p>
     * 
     * @param leadTimeOffset
     *     Lead-Time Offset
     */
    public void setLeadTimeOffset(
        @Nullable
        final BigDecimal leadTimeOffset) {
        rememberChangedField("LeadTimeOffset", this.leadTimeOffset);
        this.leadTimeOffset = leadTimeOffset;
    }

    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>QuantityIsFixed</b></p>
     * 
     * @param quantityIsFixed
     *     Quantity is fixed
     */
    public void setQuantityIsFixed(
        @Nullable
        final Boolean quantityIsFixed) {
        rememberChangedField("QuantityIsFixed", this.quantityIsFixed);
        this.quantityIsFixed = quantityIsFixed;
    }

    /**
     * Constraints: none<p>Original property name from the Odata EDM: <b>IsNetScrap</b></p>
     * 
     * @param netScrapIndicator
     *     Net Scrap Indicator
     */
    public void setNetScrapIndicator(
        @Nullable
        final Boolean netScrapIndicator) {
        rememberChangedField("IsNetScrap", this.netScrapIndicator);
        this.netScrapIndicator = netScrapIndicator;
    }

    /**
     * Constraints: Not nullable, Precision: 5, Scale: 2 <p>Original property name from the Odata EDM: <b>ComponentScrapInPercent</b></p>
     * 
     * @param componentScrap
     *     Component Scrap in Percent
     */
    public void setComponentScrap(
        @Nullable
        final BigDecimal componentScrap) {
        rememberChangedField("ComponentScrapInPercent", this.componentScrap);
        this.componentScrap = componentScrap;
    }

    /**
     * Constraints: Not nullable, Precision: 5, Scale: 2 <p>Original property name from the Odata EDM: <b>OperationScrapInPercent</b></p>
     * 
     * @param operationScrapIn
     *     Operation Scrap
     */
    public void setOperationScrapIn(
        @Nullable
        final BigDecimal operationScrapIn) {
        rememberChangedField("OperationScrapInPercent", this.operationScrapIn);
        this.operationScrapIn = operationScrapIn;
    }

    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>BaseUnit</b></p>
     * 
     * @param baseUnitOfMeasure
     *     Base Unit of Measure
     */
    public void setBaseUnitOfMeasure(
        @Nullable
        final String baseUnitOfMeasure) {
        rememberChangedField("BaseUnit", this.baseUnitOfMeasure);
        this.baseUnitOfMeasure = baseUnitOfMeasure;
    }

    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>BaseUnitISOCode</b></p>
     * 
     * @param iSOCode
     *     ISO Code for Unit of Measurement
     */
    public void setISOCode(
        @Nullable
        final String iSOCode) {
        rememberChangedField("BaseUnitISOCode", this.iSOCode);
        this.iSOCode = iSOCode;
    }

    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>BaseUnitSAPCode</b></p>
     * 
     * @param internalSAPCode
     *     Unit of Measurement, Internal SAP Code (No Conversion)
     */
    public void setInternalSAPCode(
        @Nullable
        final String internalSAPCode) {
        rememberChangedField("BaseUnitSAPCode", this.internalSAPCode);
        this.internalSAPCode = internalSAPCode;
    }

    /**
     * Constraints: Not nullable, Precision: 13, Scale: 3 <p>Original property name from the Odata EDM: <b>RequiredQuantity</b></p>
     * 
     * @param requirementQuantity
     *     Requirement Quantity
     */
    public void setRequirementQuantity(
        @Nullable
        final BigDecimal requirementQuantity) {
        rememberChangedField("RequiredQuantity", this.requirementQuantity);
        this.requirementQuantity = requirementQuantity;
    }

    /**
     * Constraints: Not nullable, Precision: 13, Scale: 3 <p>Original property name from the Odata EDM: <b>WithdrawnQuantity</b></p>
     * 
     * @param withdrawnQuantity
     *     Withdrawn Quantity
     */
    public void setWithdrawnQuantity(
        @Nullable
        final BigDecimal withdrawnQuantity) {
        rememberChangedField("WithdrawnQuantity", this.withdrawnQuantity);
        this.withdrawnQuantity = withdrawnQuantity;
    }

    /**
     * Constraints: Not nullable, Precision: 15, Scale: 3 <p>Original property name from the Odata EDM: <b>ConfirmedAvailableQuantity</b></p>
     * 
     * @param availableQuantity
     *     Available Quantity
     */
    public void setAvailableQuantity(
        @Nullable
        final BigDecimal availableQuantity) {
        rememberChangedField("ConfirmedAvailableQuantity", this.availableQuantity);
        this.availableQuantity = availableQuantity;
    }

    /**
     * Constraints: Not nullable, Precision: 13, Scale: 3 <p>Original property name from the Odata EDM: <b>MaterialCompOriginalQuantity</b></p>
     * 
     * @param originalQuantity
     *     Original Quantity of a Material Component
     */
    public void setOriginalQuantity(
        @Nullable
        final BigDecimal originalQuantity) {
        rememberChangedField("MaterialCompOriginalQuantity", this.originalQuantity);
        this.originalQuantity = originalQuantity;
    }

    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>EntryUnit</b></p>
     * 
     * @param unitOfEntry
     *     Unit of entry
     */
    public void setUnitOfEntry(
        @Nullable
        final String unitOfEntry) {
        rememberChangedField("EntryUnit", this.unitOfEntry);
        this.unitOfEntry = unitOfEntry;
    }

    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>EntryUnitISOCode</b></p>
     * 
     * @param iSOCode_2
     *     ISO Code for Unit of Measurement
     */
    public void setISOCode_2(
        @Nullable
        final String iSOCode_2) {
        rememberChangedField("EntryUnitISOCode", this.iSOCode_2);
        this.iSOCode_2 = iSOCode_2;
    }

    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>EntryUnitSAPCode</b></p>
     * 
     * @param internalSAPCode_2
     *     Unit of Measurement, Internal SAP Code (No Conversion)
     */
    public void setInternalSAPCode_2(
        @Nullable
        final String internalSAPCode_2) {
        rememberChangedField("EntryUnitSAPCode", this.internalSAPCode_2);
        this.internalSAPCode_2 = internalSAPCode_2;
    }

    /**
     * Constraints: Not nullable, Precision: 13, Scale: 3 <p>Original property name from the Odata EDM: <b>GoodsMovementEntryQty</b></p>
     * 
     * @param quantityInUnitOfEntry
     *     Quantity in Unit of Entry
     */
    public void setQuantityInUnitOfEntry(
        @Nullable
        final BigDecimal quantityInUnitOfEntry) {
        rememberChangedField("GoodsMovementEntryQty", this.quantityInUnitOfEntry);
        this.quantityInUnitOfEntry = quantityInUnitOfEntry;
    }

    /**
     * Constraints: Not nullable, Maximum length: 5 <p>Original property name from the Odata EDM: <b>Currency</b></p>
     * 
     * @param currency
     *     Currency Key
     */
    public void setCurrency(
        @Nullable
        final String currency) {
        rememberChangedField("Currency", this.currency);
        this.currency = currency;
    }

    /**
     * Constraints: Not nullable, Precision: 14, Scale: 3 <p>Original property name from the Odata EDM: <b>WithdrawnQuantityAmount</b></p>
     * 
     * @param valueWithdrawn
     *     Value Withdrawn
     */
    public void setValueWithdrawn(
        @Nullable
        final BigDecimal valueWithdrawn) {
        rememberChangedField("WithdrawnQuantityAmount", this.valueWithdrawn);
        this.valueWithdrawn = valueWithdrawn;
    }

    @Override
    protected String getEntityCollection() {
        return "A_ProductionOrderComponent_2";
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        result.put("Reservation", getReservation());
        result.put("ReservationItem", getReservationItem());
        return result;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("Reservation", getReservation());
        values.put("ReservationItem", getReservationItem());
        values.put("MaterialGroup", getMaterialGroup());
        values.put("Material", getMaterial());
        values.put("Plant", getPlant());
        values.put("ManufacturingOrderCategory", getOrderCategory());
        values.put("ManufacturingOrderType", getOrderType());
        values.put("ManufacturingOrder", getProductionOrder());
        values.put("ManufacturingOrderSequence", getSequence());
        values.put("ManufacturingOrderOperation", getOperation());
        values.put("ProductionPlant", getProductionPlant());
        values.put("OrderInternalBillOfOperations", getOrderInternalID());
        values.put("MatlCompRequirementDate", getRequirementDate());
        values.put("MatlCompRequirementTime", getRequirementTime());
        values.put("ReservationIsFinallyIssued", getFinalIssue());
        values.put("MatlCompIsMarkedForDeletion", getMarkedForDeletion());
        values.put("IsBulkMaterialComponent", getBulkMaterial());
        values.put("MatlCompIsMarkedForBackflush", getBackflush());
        values.put("MaterialCompIsCostRelevant", getCostingRelevncy());
        values.put("OrderComponentLongText", getLongText());
        values.put("SalesOrder", getSalesOrder());
        values.put("SalesOrderItem", getSalesOrderItem());
        values.put("SortField", getSortString());
        values.put("BillOfMaterialCategory", getBOMCategory());
        values.put("BOMItem", getBOMItem());
        values.put("BOMItemCategory", getBOMItemCategory());
        values.put("BillOfMaterialItemNumber", getBOMItem_2());
        values.put("BOMItemDescription", getBOMItemText());
        values.put("StorageLocation", getStorageLocation());
        values.put("Batch", getBatch());
        values.put("BatchSplitType", getBatchSplitType());
        values.put("GoodsMovementType", getMovementType());
        values.put("SupplyArea", getProductionSupplyArea());
        values.put("GoodsRecipientName", getGoodsRecipient());
        values.put("UnloadingPointName", getUnloadingPoint());
        values.put("MaterialCompIsAlternativeItem", getAlternativeItem());
        values.put("AlternativeItemGroup", getAlternativeItemGroup());
        values.put("AlternativeItemStrategy", getAlternativeItemStrategy());
        values.put("AlternativeItemPriority", getAlternativeItemPriority());
        values.put("UsageProbabilityPercent", getUsageProbability());
        values.put("MaterialComponentIsPhantomItem", getPhantomItem());
        values.put("LeadTimeOffset", getLeadTimeOffset());
        values.put("QuantityIsFixed", getQuantityIsFixed());
        values.put("IsNetScrap", getNetScrapIndicator());
        values.put("ComponentScrapInPercent", getComponentScrap());
        values.put("OperationScrapInPercent", getOperationScrapIn());
        values.put("BaseUnit", getBaseUnitOfMeasure());
        values.put("BaseUnitISOCode", getISOCode());
        values.put("BaseUnitSAPCode", getInternalSAPCode());
        values.put("RequiredQuantity", getRequirementQuantity());
        values.put("WithdrawnQuantity", getWithdrawnQuantity());
        values.put("ConfirmedAvailableQuantity", getAvailableQuantity());
        values.put("MaterialCompOriginalQuantity", getOriginalQuantity());
        values.put("EntryUnit", getUnitOfEntry());
        values.put("EntryUnitISOCode", getISOCode_2());
        values.put("EntryUnitSAPCode", getInternalSAPCode_2());
        values.put("GoodsMovementEntryQty", getQuantityInUnitOfEntry());
        values.put("Currency", getCurrency());
        values.put("WithdrawnQuantityAmount", getValueWithdrawn());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("Reservation")) {
                final Object value = values.remove("Reservation");
                if ((value == null)||(!value.equals(getReservation()))) {
                    setReservation(((String) value));
                }
            }
            if (values.containsKey("ReservationItem")) {
                final Object value = values.remove("ReservationItem");
                if ((value == null)||(!value.equals(getReservationItem()))) {
                    setReservationItem(((String) value));
                }
            }
            if (values.containsKey("MaterialGroup")) {
                final Object value = values.remove("MaterialGroup");
                if ((value == null)||(!value.equals(getMaterialGroup()))) {
                    setMaterialGroup(((String) value));
                }
            }
            if (values.containsKey("Material")) {
                final Object value = values.remove("Material");
                if ((value == null)||(!value.equals(getMaterial()))) {
                    setMaterial(((String) value));
                }
            }
            if (values.containsKey("Plant")) {
                final Object value = values.remove("Plant");
                if ((value == null)||(!value.equals(getPlant()))) {
                    setPlant(((String) value));
                }
            }
            if (values.containsKey("ManufacturingOrderCategory")) {
                final Object value = values.remove("ManufacturingOrderCategory");
                if ((value == null)||(!value.equals(getOrderCategory()))) {
                    setOrderCategory(((String) value));
                }
            }
            if (values.containsKey("ManufacturingOrderType")) {
                final Object value = values.remove("ManufacturingOrderType");
                if ((value == null)||(!value.equals(getOrderType()))) {
                    setOrderType(((String) value));
                }
            }
            if (values.containsKey("ManufacturingOrder")) {
                final Object value = values.remove("ManufacturingOrder");
                if ((value == null)||(!value.equals(getProductionOrder()))) {
                    setProductionOrder(((String) value));
                }
            }
            if (values.containsKey("ManufacturingOrderSequence")) {
                final Object value = values.remove("ManufacturingOrderSequence");
                if ((value == null)||(!value.equals(getSequence()))) {
                    setSequence(((String) value));
                }
            }
            if (values.containsKey("ManufacturingOrderOperation")) {
                final Object value = values.remove("ManufacturingOrderOperation");
                if ((value == null)||(!value.equals(getOperation()))) {
                    setOperation(((String) value));
                }
            }
            if (values.containsKey("ProductionPlant")) {
                final Object value = values.remove("ProductionPlant");
                if ((value == null)||(!value.equals(getProductionPlant()))) {
                    setProductionPlant(((String) value));
                }
            }
            if (values.containsKey("OrderInternalBillOfOperations")) {
                final Object value = values.remove("OrderInternalBillOfOperations");
                if ((value == null)||(!value.equals(getOrderInternalID()))) {
                    setOrderInternalID(((String) value));
                }
            }
            if (values.containsKey("MatlCompRequirementDate")) {
                final Object value = values.remove("MatlCompRequirementDate");
                if ((value == null)||(!value.equals(getRequirementDate()))) {
                    setRequirementDate(((LocalDateTime) value));
                }
            }
            if (values.containsKey("MatlCompRequirementTime")) {
                final Object value = values.remove("MatlCompRequirementTime");
                if ((value == null)||(!value.equals(getRequirementTime()))) {
                    setRequirementTime(((LocalTime) value));
                }
            }
            if (values.containsKey("ReservationIsFinallyIssued")) {
                final Object value = values.remove("ReservationIsFinallyIssued");
                if ((value == null)||(!value.equals(getFinalIssue()))) {
                    setFinalIssue(((Boolean) value));
                }
            }
            if (values.containsKey("MatlCompIsMarkedForDeletion")) {
                final Object value = values.remove("MatlCompIsMarkedForDeletion");
                if ((value == null)||(!value.equals(getMarkedForDeletion()))) {
                    setMarkedForDeletion(((Boolean) value));
                }
            }
            if (values.containsKey("IsBulkMaterialComponent")) {
                final Object value = values.remove("IsBulkMaterialComponent");
                if ((value == null)||(!value.equals(getBulkMaterial()))) {
                    setBulkMaterial(((Boolean) value));
                }
            }
            if (values.containsKey("MatlCompIsMarkedForBackflush")) {
                final Object value = values.remove("MatlCompIsMarkedForBackflush");
                if ((value == null)||(!value.equals(getBackflush()))) {
                    setBackflush(((Boolean) value));
                }
            }
            if (values.containsKey("MaterialCompIsCostRelevant")) {
                final Object value = values.remove("MaterialCompIsCostRelevant");
                if ((value == null)||(!value.equals(getCostingRelevncy()))) {
                    setCostingRelevncy(((String) value));
                }
            }
            if (values.containsKey("OrderComponentLongText")) {
                final Object value = values.remove("OrderComponentLongText");
                if ((value == null)||(!value.equals(getLongText()))) {
                    setLongText(((String) value));
                }
            }
            if (values.containsKey("SalesOrder")) {
                final Object value = values.remove("SalesOrder");
                if ((value == null)||(!value.equals(getSalesOrder()))) {
                    setSalesOrder(((String) value));
                }
            }
            if (values.containsKey("SalesOrderItem")) {
                final Object value = values.remove("SalesOrderItem");
                if ((value == null)||(!value.equals(getSalesOrderItem()))) {
                    setSalesOrderItem(((String) value));
                }
            }
            if (values.containsKey("SortField")) {
                final Object value = values.remove("SortField");
                if ((value == null)||(!value.equals(getSortString()))) {
                    setSortString(((String) value));
                }
            }
            if (values.containsKey("BillOfMaterialCategory")) {
                final Object value = values.remove("BillOfMaterialCategory");
                if ((value == null)||(!value.equals(getBOMCategory()))) {
                    setBOMCategory(((String) value));
                }
            }
            if (values.containsKey("BOMItem")) {
                final Object value = values.remove("BOMItem");
                if ((value == null)||(!value.equals(getBOMItem()))) {
                    setBOMItem(((String) value));
                }
            }
            if (values.containsKey("BOMItemCategory")) {
                final Object value = values.remove("BOMItemCategory");
                if ((value == null)||(!value.equals(getBOMItemCategory()))) {
                    setBOMItemCategory(((String) value));
                }
            }
            if (values.containsKey("BillOfMaterialItemNumber")) {
                final Object value = values.remove("BillOfMaterialItemNumber");
                if ((value == null)||(!value.equals(getBOMItem_2()))) {
                    setBOMItem_2(((String) value));
                }
            }
            if (values.containsKey("BOMItemDescription")) {
                final Object value = values.remove("BOMItemDescription");
                if ((value == null)||(!value.equals(getBOMItemText()))) {
                    setBOMItemText(((String) value));
                }
            }
            if (values.containsKey("StorageLocation")) {
                final Object value = values.remove("StorageLocation");
                if ((value == null)||(!value.equals(getStorageLocation()))) {
                    setStorageLocation(((String) value));
                }
            }
            if (values.containsKey("Batch")) {
                final Object value = values.remove("Batch");
                if ((value == null)||(!value.equals(getBatch()))) {
                    setBatch(((String) value));
                }
            }
            if (values.containsKey("BatchSplitType")) {
                final Object value = values.remove("BatchSplitType");
                if ((value == null)||(!value.equals(getBatchSplitType()))) {
                    setBatchSplitType(((String) value));
                }
            }
            if (values.containsKey("GoodsMovementType")) {
                final Object value = values.remove("GoodsMovementType");
                if ((value == null)||(!value.equals(getMovementType()))) {
                    setMovementType(((String) value));
                }
            }
            if (values.containsKey("SupplyArea")) {
                final Object value = values.remove("SupplyArea");
                if ((value == null)||(!value.equals(getProductionSupplyArea()))) {
                    setProductionSupplyArea(((String) value));
                }
            }
            if (values.containsKey("GoodsRecipientName")) {
                final Object value = values.remove("GoodsRecipientName");
                if ((value == null)||(!value.equals(getGoodsRecipient()))) {
                    setGoodsRecipient(((String) value));
                }
            }
            if (values.containsKey("UnloadingPointName")) {
                final Object value = values.remove("UnloadingPointName");
                if ((value == null)||(!value.equals(getUnloadingPoint()))) {
                    setUnloadingPoint(((String) value));
                }
            }
            if (values.containsKey("MaterialCompIsAlternativeItem")) {
                final Object value = values.remove("MaterialCompIsAlternativeItem");
                if ((value == null)||(!value.equals(getAlternativeItem()))) {
                    setAlternativeItem(((Boolean) value));
                }
            }
            if (values.containsKey("AlternativeItemGroup")) {
                final Object value = values.remove("AlternativeItemGroup");
                if ((value == null)||(!value.equals(getAlternativeItemGroup()))) {
                    setAlternativeItemGroup(((String) value));
                }
            }
            if (values.containsKey("AlternativeItemStrategy")) {
                final Object value = values.remove("AlternativeItemStrategy");
                if ((value == null)||(!value.equals(getAlternativeItemStrategy()))) {
                    setAlternativeItemStrategy(((String) value));
                }
            }
            if (values.containsKey("AlternativeItemPriority")) {
                final Object value = values.remove("AlternativeItemPriority");
                if ((value == null)||(!value.equals(getAlternativeItemPriority()))) {
                    setAlternativeItemPriority(((String) value));
                }
            }
            if (values.containsKey("UsageProbabilityPercent")) {
                final Object value = values.remove("UsageProbabilityPercent");
                if ((value == null)||(!value.equals(getUsageProbability()))) {
                    setUsageProbability(((BigDecimal) value));
                }
            }
            if (values.containsKey("MaterialComponentIsPhantomItem")) {
                final Object value = values.remove("MaterialComponentIsPhantomItem");
                if ((value == null)||(!value.equals(getPhantomItem()))) {
                    setPhantomItem(((Boolean) value));
                }
            }
            if (values.containsKey("LeadTimeOffset")) {
                final Object value = values.remove("LeadTimeOffset");
                if ((value == null)||(!value.equals(getLeadTimeOffset()))) {
                    setLeadTimeOffset(((BigDecimal) value));
                }
            }
            if (values.containsKey("QuantityIsFixed")) {
                final Object value = values.remove("QuantityIsFixed");
                if ((value == null)||(!value.equals(getQuantityIsFixed()))) {
                    setQuantityIsFixed(((Boolean) value));
                }
            }
            if (values.containsKey("IsNetScrap")) {
                final Object value = values.remove("IsNetScrap");
                if ((value == null)||(!value.equals(getNetScrapIndicator()))) {
                    setNetScrapIndicator(((Boolean) value));
                }
            }
            if (values.containsKey("ComponentScrapInPercent")) {
                final Object value = values.remove("ComponentScrapInPercent");
                if ((value == null)||(!value.equals(getComponentScrap()))) {
                    setComponentScrap(((BigDecimal) value));
                }
            }
            if (values.containsKey("OperationScrapInPercent")) {
                final Object value = values.remove("OperationScrapInPercent");
                if ((value == null)||(!value.equals(getOperationScrapIn()))) {
                    setOperationScrapIn(((BigDecimal) value));
                }
            }
            if (values.containsKey("BaseUnit")) {
                final Object value = values.remove("BaseUnit");
                if ((value == null)||(!value.equals(getBaseUnitOfMeasure()))) {
                    setBaseUnitOfMeasure(((String) value));
                }
            }
            if (values.containsKey("BaseUnitISOCode")) {
                final Object value = values.remove("BaseUnitISOCode");
                if ((value == null)||(!value.equals(getISOCode()))) {
                    setISOCode(((String) value));
                }
            }
            if (values.containsKey("BaseUnitSAPCode")) {
                final Object value = values.remove("BaseUnitSAPCode");
                if ((value == null)||(!value.equals(getInternalSAPCode()))) {
                    setInternalSAPCode(((String) value));
                }
            }
            if (values.containsKey("RequiredQuantity")) {
                final Object value = values.remove("RequiredQuantity");
                if ((value == null)||(!value.equals(getRequirementQuantity()))) {
                    setRequirementQuantity(((BigDecimal) value));
                }
            }
            if (values.containsKey("WithdrawnQuantity")) {
                final Object value = values.remove("WithdrawnQuantity");
                if ((value == null)||(!value.equals(getWithdrawnQuantity()))) {
                    setWithdrawnQuantity(((BigDecimal) value));
                }
            }
            if (values.containsKey("ConfirmedAvailableQuantity")) {
                final Object value = values.remove("ConfirmedAvailableQuantity");
                if ((value == null)||(!value.equals(getAvailableQuantity()))) {
                    setAvailableQuantity(((BigDecimal) value));
                }
            }
            if (values.containsKey("MaterialCompOriginalQuantity")) {
                final Object value = values.remove("MaterialCompOriginalQuantity");
                if ((value == null)||(!value.equals(getOriginalQuantity()))) {
                    setOriginalQuantity(((BigDecimal) value));
                }
            }
            if (values.containsKey("EntryUnit")) {
                final Object value = values.remove("EntryUnit");
                if ((value == null)||(!value.equals(getUnitOfEntry()))) {
                    setUnitOfEntry(((String) value));
                }
            }
            if (values.containsKey("EntryUnitISOCode")) {
                final Object value = values.remove("EntryUnitISOCode");
                if ((value == null)||(!value.equals(getISOCode_2()))) {
                    setISOCode_2(((String) value));
                }
            }
            if (values.containsKey("EntryUnitSAPCode")) {
                final Object value = values.remove("EntryUnitSAPCode");
                if ((value == null)||(!value.equals(getInternalSAPCode_2()))) {
                    setInternalSAPCode_2(((String) value));
                }
            }
            if (values.containsKey("GoodsMovementEntryQty")) {
                final Object value = values.remove("GoodsMovementEntryQty");
                if ((value == null)||(!value.equals(getQuantityInUnitOfEntry()))) {
                    setQuantityInUnitOfEntry(((BigDecimal) value));
                }
            }
            if (values.containsKey("Currency")) {
                final Object value = values.remove("Currency");
                if ((value == null)||(!value.equals(getCurrency()))) {
                    setCurrency(((String) value));
                }
            }
            if (values.containsKey("WithdrawnQuantityAmount")) {
                final Object value = values.remove("WithdrawnQuantityAmount");
                if ((value == null)||(!value.equals(getValueWithdrawn()))) {
                    setValueWithdrawn(((BigDecimal) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param fieldType
     *     The Java type to use for the extension field when performing value comparisons.
     * @return
     *     A representation of an extension field from this entity.
     */
    @Nonnull
    public static<T >ProductionOrderComponentsField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final Class<T> fieldType) {
        return new ProductionOrderComponentsField<T>(fieldName);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param typeConverter
     *     A TypeConverter<T, DomainT> instance whose first generic type matches the Java type of the field
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param <DomainT>
     *     The type of the extension field as returned by the OData service.
     * @return
     *     A representation of an extension field from this entity, holding a reference to the given TypeConverter.
     */
    @Nonnull
    public static<T,DomainT >ProductionOrderComponentsField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final TypeConverter<T, DomainT> typeConverter) {
        return new ProductionOrderComponentsField<T>(fieldName, typeConverter);
    }

    @Override
    @Nullable
    public Destination getDestinationForFetch() {
        return super.getDestinationForFetch();
    }

    @Override
    protected void setServicePathForFetch(
        @Nullable
        final String servicePathForFetch) {
        super.setServicePathForFetch(servicePathForFetch);
    }

    @Override
    public void attachToService(
        @Nullable
        final String servicePath,
        @Nonnull
        final Destination destination) {
        super.attachToService(servicePath, destination);
    }

    @Override
    protected String getDefaultServicePath() {
        return (com.sap.cloud.sdk.tutorial.datamodel.odata.services.APIPRODUCTIONORDER2SRVService.DEFAULT_SERVICE_PATH);
    }

}
