
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.selectable;

import com.sap.cloud.sdk.datamodel.odata.helper.EntitySelectable;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended;


/**
 * Interface to enable OData entity selectors for {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended ProductionOrderComponentsExtended}. This interface is used by {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.field.ProductionOrderComponentsExtendedField ProductionOrderComponentsExtendedField} and {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.link.ProductionOrderComponentsExtendedLink ProductionOrderComponentsExtendedLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#RESERVATION RESERVATION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#RESERVATION_ITEM RESERVATION_ITEM}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#RESERVATION_RECORD_TYPE RESERVATION_RECORD_TYPE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#MATERIAL_GROUP MATERIAL_GROUP}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#MATERIAL MATERIAL}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#PLANT PLANT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#ORDER_CATEGORY ORDER_CATEGORY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#ORDER_TYPE ORDER_TYPE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#PRODUCTION_ORDER PRODUCTION_ORDER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#SEQUENCE SEQUENCE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#OPERATION_OR_PHASE OPERATION_OR_PHASE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#PRODUCTION_PLANT PRODUCTION_PLANT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#ORDER_INTERNAL_ID ORDER_INTERNAL_ID}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#REQUIREMENT_DATE REQUIREMENT_DATE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#REQUIREMENT_TIME REQUIREMENT_TIME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#FINAL_ISSUE FINAL_ISSUE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#MARKED_FOR_DELETION MARKED_FOR_DELETION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#BULK_MATERIAL BULK_MATERIAL}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#BACKFLUSH BACKFLUSH}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#COSTING_RELEVNCY COSTING_RELEVNCY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#LONG_TEXT LONG_TEXT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#SALES_ORDER SALES_ORDER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#SALES_ORDER_ITEM SALES_ORDER_ITEM}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#SORT_STRING SORT_STRING}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#BOM_CATEGORY BOM_CATEGORY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#BOM_ITEM BOM_ITEM}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#BOM_ITEM_CATEGORY BOM_ITEM_CATEGORY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#BILL_OF_MATERIAL_ITEM_NUMBER BILL_OF_MATERIAL_ITEM_NUMBER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#BOM_ITEM_TEXT BOM_ITEM_TEXT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#STORAGE_LOCATION STORAGE_LOCATION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#BATCH BATCH}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#BATCH_SPLIT_TYPE BATCH_SPLIT_TYPE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#MOVEMENT_TYPE MOVEMENT_TYPE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#PRODUCTION_SUPPLY_AREA PRODUCTION_SUPPLY_AREA}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#GOODS_RECIPIENT GOODS_RECIPIENT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#UNLOADING_POINT UNLOADING_POINT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#ALTERNATIVE_ITEM ALTERNATIVE_ITEM}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#ALTERNATIVE_ITEM_GROUP ALTERNATIVE_ITEM_GROUP}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#ALTERNATIVE_ITEM_STRATEGY ALTERNATIVE_ITEM_STRATEGY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#ALTERNATIVE_ITEM_PRIORITY ALTERNATIVE_ITEM_PRIORITY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#USAGE_PROBABILITY USAGE_PROBABILITY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#PHANTOM_ITEM PHANTOM_ITEM}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#LEAD_TIME_OFFSET LEAD_TIME_OFFSET}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#QUANTITY_IS_FIXED QUANTITY_IS_FIXED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#NET_SCRAP_INDICATOR NET_SCRAP_INDICATOR}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#COMPONENT_SCRAP COMPONENT_SCRAP}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#OPERATION_SCRAP_IN OPERATION_SCRAP_IN}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#BASE_UNIT_OF_MEASURE BASE_UNIT_OF_MEASURE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#ISO_CODE ISO_CODE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#INTERNAL_SAP_CODE INTERNAL_SAP_CODE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#REQUIREMENT_QUANTITY REQUIREMENT_QUANTITY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#WITHDRAWN_QUANTITY WITHDRAWN_QUANTITY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#AVAILABLE_QUANTITY AVAILABLE_QUANTITY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#ORIGINAL_QUANTITY ORIGINAL_QUANTITY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#UNIT_OF_ENTRY UNIT_OF_ENTRY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#ISO_CODE_2 ISO_CODE_2}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#INTERNAL_SAP_CODE_2 INTERNAL_SAP_CODE_2}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#QUANTITY_IN_UNIT_OF_ENTRY QUANTITY_IN_UNIT_OF_ENTRY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#CURRENCY CURRENCY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#VALUE_WITHDRAWN VALUE_WITHDRAWN}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsExtended#LAST_CHANGE_DATE_TIME LAST_CHANGE_DATE_TIME}</li>
 * </ul>
 * 
 */
public interface ProductionOrderComponentsExtendedSelectable
    extends EntitySelectable<ProductionOrderComponentsExtended>
{


}
