
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.selectable;

import com.sap.cloud.sdk.datamodel.odata.helper.EntitySelectable;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO;


/**
 * Interface to enable OData entity selectors for {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO ProductionOrderComponentsUsingRAPBO}. This interface is used by {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.field.ProductionOrderComponentsUsingRAPBOField ProductionOrderComponentsUsingRAPBOField} and {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.link.ProductionOrderComponentsUsingRAPBOLink ProductionOrderComponentsUsingRAPBOLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#RESERVATION RESERVATION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#RESERVATION_ITEM RESERVATION_ITEM}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#RESERVATION_RECORD_TYPE RESERVATION_RECORD_TYPE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#MATERIAL_GROUP MATERIAL_GROUP}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#MATERIAL MATERIAL}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#PLANT PLANT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#ORDER_CATEGORY ORDER_CATEGORY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#ORDER_TYPE ORDER_TYPE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#PRODUCTION_ORDER PRODUCTION_ORDER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#SEQUENCE SEQUENCE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#OPERATION_OR_PHASE OPERATION_OR_PHASE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#PRODUCTION_PLANT PRODUCTION_PLANT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#ORDER_INTERNAL_ID ORDER_INTERNAL_ID}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#REQUIREMENT_DATE REQUIREMENT_DATE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#REQUIREMENT_TIME REQUIREMENT_TIME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#FINAL_ISSUE FINAL_ISSUE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#MARKED_FOR_DELETION MARKED_FOR_DELETION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#BULK_MATERIAL BULK_MATERIAL}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#BACKFLUSH BACKFLUSH}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#COSTING_RELEVNCY COSTING_RELEVNCY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#LONG_TEXT LONG_TEXT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#SALES_ORDER SALES_ORDER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#SALES_ORDER_ITEM SALES_ORDER_ITEM}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#SORT_STRING SORT_STRING}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#BOM_CATEGORY BOM_CATEGORY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#BOM_ITEM BOM_ITEM}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#BOM_ITEM_CATEGORY BOM_ITEM_CATEGORY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#BILL_OF_MATERIAL_ITEM_NUMBER BILL_OF_MATERIAL_ITEM_NUMBER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#BOM_ITEM_TEXT BOM_ITEM_TEXT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#STORAGE_LOCATION STORAGE_LOCATION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#BATCH BATCH}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#BATCH_SPLIT_TYPE BATCH_SPLIT_TYPE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#MOVEMENT_TYPE MOVEMENT_TYPE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#PRODUCTION_SUPPLY_AREA PRODUCTION_SUPPLY_AREA}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#GOODS_RECIPIENT GOODS_RECIPIENT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#UNLOADING_POINT UNLOADING_POINT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#ALTERNATIVE_ITEM ALTERNATIVE_ITEM}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#ALTERNATIVE_ITEM_GROUP ALTERNATIVE_ITEM_GROUP}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#ALTERNATIVE_ITEM_STRATEGY ALTERNATIVE_ITEM_STRATEGY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#ALTERNATIVE_ITEM_PRIORITY ALTERNATIVE_ITEM_PRIORITY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#USAGE_PROBABILITY USAGE_PROBABILITY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#PHANTOM_ITEM PHANTOM_ITEM}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#LEAD_TIME_OFFSET LEAD_TIME_OFFSET}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#QUANTITY_IS_FIXED QUANTITY_IS_FIXED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#NET_SCRAP_INDICATOR NET_SCRAP_INDICATOR}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#COMPONENT_SCRAP COMPONENT_SCRAP}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#OPERATION_SCRAP_IN OPERATION_SCRAP_IN}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#BASE_UNIT_OF_MEASURE BASE_UNIT_OF_MEASURE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#ISO_CODE ISO_CODE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#INTERNAL_SAP_CODE INTERNAL_SAP_CODE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#REQUIREMENT_QUANTITY REQUIREMENT_QUANTITY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#WITHDRAWN_QUANTITY WITHDRAWN_QUANTITY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#AVAILABLE_QUANTITY AVAILABLE_QUANTITY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#ORIGINAL_QUANTITY ORIGINAL_QUANTITY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#UNIT_OF_ENTRY UNIT_OF_ENTRY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#ISO_CODE_2 ISO_CODE_2}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#INTERNAL_SAP_CODE_2 INTERNAL_SAP_CODE_2}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#QUANTITY_IN_UNIT_OF_ENTRY QUANTITY_IN_UNIT_OF_ENTRY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#CURRENCY CURRENCY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#VALUE_WITHDRAWN VALUE_WITHDRAWN}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderComponentsUsingRAPBO#LAST_CHANGE_DATE_TIME LAST_CHANGE_DATE_TIME}</li>
 * </ul>
 * 
 */
public interface ProductionOrderComponentsUsingRAPBOSelectable
    extends EntitySelectable<ProductionOrderComponentsUsingRAPBO>
{


}
