
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.selectable;

import com.sap.cloud.sdk.datamodel.odata.helper.EntitySelectable;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations;


/**
 * Interface to enable OData entity selectors for {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations ProductionOrderOperations}. This interface is used by {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.field.ProductionOrderOperationsField ProductionOrderOperationsField} and {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.link.ProductionOrderOperationsLink ProductionOrderOperationsLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#ORDER_INTERNAL_ID ORDER_INTERNAL_ID}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#OPERATION_INTERNAL_ID OPERATION_INTERNAL_ID}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#PRODUCTION_ORDER PRODUCTION_ORDER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#SEQUENCE SEQUENCE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#SEQUENCE_TEXT SEQUENCE_TEXT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#OPERATION OPERATION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#SUBOPERATION SUBOPERATION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#ORDER_CATEGORY ORDER_CATEGORY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#ORDER_TYPE ORDER_TYPE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#OPERATION_TEXT OPERATION_TEXT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#LONG_TEXT LONG_TEXT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#LONG_TEXT_2 LONG_TEXT_2}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#OPERATION_IS_CREATED OPERATION_IS_CREATED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#OPERATION_IS_RELEASED OPERATION_IS_RELEASED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#OPERATION_IS_PRINTED OPERATION_IS_PRINTED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#OPERATION_IS_CONFIRMED OPERATION_IS_CONFIRMED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#OPERATION_IS_PARTIALLY_CONFIRMED OPERATION_IS_PARTIALLY_CONFIRMED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#OPERATION_IS_DELETED OPERATION_IS_DELETED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#OPERATION_IS_TECHLY_COMPLETED OPERATION_IS_TECHLY_COMPLETED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#OPERATION_IS_CLOSED OPERATION_IS_CLOSED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#OPERATION_IS_SCHEDULED OPERATION_IS_SCHEDULED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#OPERATION_IS_PARTIALLY_DELIVERED OPERATION_IS_PARTIALLY_DELIVERED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#OPERATION_IS_DELIVERED OPERATION_IS_DELIVERED}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#PRODUCTION_PLANT PRODUCTION_PLANT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#WORK_CENTER_INTERNAL WORK_CENTER_INTERNAL}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#WORK_CENTER_TYPE_CODE WORK_CENTER_TYPE_CODE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#WORK_CENTER WORK_CENTER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#CONTROL_PROFILE CONTROL_PROFILE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#EXECUTION_START_DATE EXECUTION_START_DATE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#EXECUTION_START_TIME EXECUTION_START_TIME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#EXECUTION_END_DATE EXECUTION_END_DATE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#EXECUTION_END_TIME EXECUTION_END_TIME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#CONFIRMED_EXECUTION_START_DATE CONFIRMED_EXECUTION_START_DATE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#CONFIRMED_EXECUTION_START_TIME CONFIRMED_EXECUTION_START_TIME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#CONFIRMED_EXECUTION_END_DATE CONFIRMED_EXECUTION_END_DATE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#CONFIRMED_EXECUTION_END_TIME CONFIRMED_EXECUTION_END_TIME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#PROCESSING_START_DTE PROCESSING_START_DTE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#PROCESSING_START_TME PROCESSING_START_TME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#TEARDOWN_START_DATE TEARDOWN_START_DATE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#TEARDOWN_START_TIME TEARDOWN_START_TIME}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#SCHEDULED_EXECUTION_DURATION SCHEDULED_EXECUTION_DURATION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#ACTUAL_EXECUTION_DURATION ACTUAL_EXECUTION_DURATION}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#OPERATION_UNIT OPERATION_UNIT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#ISO_CODE ISO_CODE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#INTERNAL_SAP_CODE INTERNAL_SAP_CODE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#OPERATION_QUANTITY OPERATION_QUANTITY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#CONFIRMED_YIELD CONFIRMED_YIELD}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#WORK_QUANTITY_UNIT1 WORK_QUANTITY_UNIT1}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#ISO_CODE_2 ISO_CODE_2}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#INTERNAL_SAP_CODE_2 INTERNAL_SAP_CODE_2}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#STANDARD_VALUE STANDARD_VALUE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#WORK_QUANTITY_UNIT2 WORK_QUANTITY_UNIT2}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#ISO_CODE_3 ISO_CODE_3}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#INTERNAL_SAP_CODE_3 INTERNAL_SAP_CODE_3}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#STANDARD_VALUE_2 STANDARD_VALUE_2}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#WORK_QUANTITY_UNIT3 WORK_QUANTITY_UNIT3}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#ISO_CODE_4 ISO_CODE_4}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#INTERNAL_SAP_CODE_4 INTERNAL_SAP_CODE_4}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#STANDARD_VALUE_3 STANDARD_VALUE_3}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#WORK_QUANTITY_UNIT4 WORK_QUANTITY_UNIT4}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#ISO_CODE_5 ISO_CODE_5}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#INTERNAL_SAP_CODE_5 INTERNAL_SAP_CODE_5}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#STANDARD_VALUE_4 STANDARD_VALUE_4}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#WORK_QUANTITY_UNIT5 WORK_QUANTITY_UNIT5}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#ISO_CODE_6 ISO_CODE_6}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#INTERNAL_SAP_CODE_6 INTERNAL_SAP_CODE_6}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#STANDARD_VALUE_5 STANDARD_VALUE_5}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#WORK_QUANTITY_UNIT6 WORK_QUANTITY_UNIT6}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#ISO_CODE_7 ISO_CODE_7}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#INTERNAL_SAP_CODE_7 INTERNAL_SAP_CODE_7}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#STANDARD_VALUE_6 STANDARD_VALUE_6}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderOperations#LAST_CHANGE_DATE_TIME LAST_CHANGE_DATE_TIME}</li>
 * </ul>
 * 
 */
public interface ProductionOrderOperationsSelectable
    extends EntitySelectable<ProductionOrderOperations>
{


}
