
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.selectable;

import com.sap.cloud.sdk.datamodel.odata.helper.EntitySelectable;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderSerialNumbers;


/**
 * Interface to enable OData entity selectors for {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderSerialNumbers ProductionOrderSerialNumbers}. This interface is used by {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.field.ProductionOrderSerialNumbersField ProductionOrderSerialNumbersField} and {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.link.ProductionOrderSerialNumbersLink ProductionOrderSerialNumbersLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderSerialNumbers#MANUFACTURING_ORDER MANUFACTURING_ORDER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderSerialNumbers#MANUFACTURING_ORDER_ITEM MANUFACTURING_ORDER_ITEM}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderSerialNumbers#SERIAL_NUMBER SERIAL_NUMBER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderSerialNumbers#SERIAL_NUMBER_PROFILE SERIAL_NUMBER_PROFILE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderSerialNumbers#PRODUCT PRODUCT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderSerialNumbers#PRODUCTION_PLANT PRODUCTION_PLANT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderSerialNumbers#ORDER_CATEGORY ORDER_CATEGORY}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderSerialNumbers#ORDER_TYPE ORDER_TYPE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderSerialNumbers#DATE DATE}</li>
 * </ul>
 * 
 */
public interface ProductionOrderSerialNumbersSelectable
    extends EntitySelectable<ProductionOrderSerialNumbers>
{


}
