
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.10.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.selectable;

import com.sap.cloud.sdk.datamodel.odata.helper.EntitySelectable;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderStatus;


/**
 * Interface to enable OData entity selectors for {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderStatus ProductionOrderStatus}. This interface is used by {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.field.ProductionOrderStatusField ProductionOrderStatusField} and {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.link.ProductionOrderStatusLink ProductionOrderStatusLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderStatus#PRODUCTION_ORDER PRODUCTION_ORDER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderStatus#STATUS STATUS}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderStatus#IS_USER_STATUS IS_USER_STATUS}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderStatus#STATUS_2 STATUS_2}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.productionorder2srv.ProductionOrderStatus#STATUS_3 STATUS_3}</li>
 * </ul>
 * 
 */
public interface ProductionOrderStatusSelectable
    extends EntitySelectable<ProductionOrderStatus>
{


}
